In [1]:
import psi4
import pandas as pd
import os
import numpy as np
from lps_uscf import lps_solver

In [2]:
csv_file = 'open_shell_10atoms_vs_uhf.csv'

if os.path.exists(csv_file):
    df = pd.read_csv(csv_file)
    print(f"-> Loaded existing results: {len(df)} rows found.")
else:
    df = pd.DataFrame()
    print("-> No existing file found. Starting fresh.")

-> No existing file found. Starting fresh.

In [47]:
psi4.core.set_output_file('output.dat', False)

ATOMS = {
    'H':  {'mult': 2}, 
    'He': {'mult': 1},
    'Li': {'mult': 2}, 
    'Be': {'mult': 1},
    'B':  {'mult': 2}, 
    'C':  {'mult': 3},
    'N':  {'mult': 4}, 
    'O':  {'mult': 3},
    'F':  {'mult': 2}, 
    'Ne': {'mult': 1},
}

METHOD = "TF0.111111W PBE"
TP = ['LDA_K_TF', 1.0]
LAMBDA = 0.111111
# EXC = ['LDA_X', 1.0, 'LDA_C_VWN', 0.0]
EXC = ['GGA_X_PBE', 1.0, 'LDA_C_VWN', 0.0]
FA = [False, 1.0]
DIIS = True
MAX_ITER = 20000
DAMPING = [0.99, 0.99, 0.0001]
D_guess = None
verbose=True

psi4.set_options({'basis': 'UGBS_S', 
                  'DFT_SPHERICAL_POINTS': 6, 
                  'DFT_RADIAL_POINTS': 1000})

for atom in ATOMS:
    
    if not df.empty:
        exists = df[
            (df['Atom'] == atom) & 
            (df['Method'] == METHOD) & 
            (df['Basis'] == psi4.core.get_global_option("BASIS"))
        ]
        if not exists.empty:
            print(f"Skipping {atom} (Already exists for {METHOD}/{psi4.core.get_global_option("BASIS")})")
            continue

    print(f"Calculating {atom} with {METHOD}...")
    MOL = psi4.geometry(f"0 {ATOMS[atom]['mult']}\n {atom}\nsymmetry c1")
    try:
        E, Da, Db, iterations = lps_solver(MAX_ITER,TP,EXC,LAMBDA,MOL,DAMPING,FA,D_guess,DIIS,verbose)
        if iterations >= MAX_ITER:
            print("  !!! SCF failed to converge (Max cycles exceeded).")
        else:
            print(f"Calculated Energy: {E:.4f} Hartree")
            row = {
                "Method": METHOD,
                "Atom": atom,
                "Basis": psi4.core.get_global_option("BASIS"),
                "Grid_Sph": psi4.core.get_global_option("DFT_SPHERICAL_POINTS"),
                "Grid_Rad": psi4.core.get_global_option("DFT_RADIAL_POINTS"),
                "Energy,Ha": round(E, 6),
                "Iterations": iterations,
                "DIIS": DIIS,
                "Damp_Start": DAMPING[0],
                "Damp_End": DAMPING[1],
                "Damp_Cutoff": DAMPING[2]
            }
            
            df = pd.concat([df, pd.DataFrame([row])], ignore_index=True)
    
    except Exception as e:
        print(f"  !!! Failed {atom}. Error: {e}")
        continue

Skipping H (Already exists for TF0.111111W PBE/UGBS_S)
Skipping He (Already exists for TF0.111111W PBE/UGBS_S)
Skipping Li (Already exists for TF0.111111W PBE/UGBS_S)
Skipping Be (Already exists for TF0.111111W PBE/UGBS_S)
Skipping B (Already exists for TF0.111111W PBE/UGBS_S)
Skipping C (Already exists for TF0.111111W PBE/UGBS_S)
Skipping N (Already exists for TF0.111111W PBE/UGBS_S)
Calculating O with TF0.111111W PBE...
Number of basis functions:   31

Starting SCF iterations:

    Iter            Energy            Delta E         dRMS

SCF Iter  1:       259.68860167    2.59689E+02    2.85351E+01
SCF Iter  2:       251.54283100   -8.14577E+00    2.79875E+01
SCF Iter  3:       243.57480197   -7.96803E+00    2.74505E+01
SCF Iter  4:       237.32092800   -6.25387E+00    2.75230E+01
SCF Iter  5:       231.17153072   -6.14940E+00    2.87275E+01
SCF Iter  6:       225.15476833   -6.01676E+00    3.08635E+01
SCF Iter  7:       219.27331763   -5.88145E+00    3.36998E+01
SCF Iter  8:       212.96109940   -6.31222E+00    3.34202E+01
SCF Iter  9:       210.50475843   -2.45634E+00    3.29179E+01
SCF Iter 10:       203.86579196   -6.63897E+00    3.24183E+01
SCF Iter 11:       197.28241376   -6.58338E+00    3.19287E+01
SCF Iter 12:       190.81040514   -6.47201E+00    3.14484E+01
SCF Iter 13:       185.26499454   -5.54541E+00    3.09749E+01
SCF Iter 14:       179.58245888   -5.68254E+00    3.05117E+01
SCF Iter 15:       173.78189992   -5.80056E+00    3.00578E+01
SCF Iter 16:       168.86958191   -4.91232E+00    2.96068E+01
SCF Iter 17:       163.83171933   -5.03786E+00    2.91644E+01
SCF Iter 18:       158.79713405   -5.03459E+00    2.87357E+01
SCF Iter 19:       153.86135493   -4.93578E+00    2.83140E+01
SCF Iter 20:       149.86715277   -3.99420E+00    2.78932E+01
SCF Iter 21:       146.33834734   -3.52881E+00    2.74748E+01
SCF Iter 22:       142.59256643   -3.74578E+00    2.70652E+01
SCF Iter 23:       138.46339251   -4.12917E+00    2.66659E+01
SCF Iter 24:       134.81125305   -3.65214E+00    2.62743E+01
SCF Iter 25:       131.25922701   -3.55203E+00    2.58927E+01
SCF Iter 26:       128.15755826   -3.10167E+00    2.55188E+01
SCF Iter 27:       124.22671764   -3.93084E+00    2.51533E+01
SCF Iter 28:       120.40325918   -3.82346E+00    2.47909E+01
SCF Iter 29:       116.74384213   -3.65942E+00    2.44352E+01
SCF Iter 30:       113.39714699   -3.34670E+00    2.40858E+01
SCF Iter 31:       109.51999720   -3.87715E+00    2.37444E+01
SCF Iter 32:       105.75339273   -3.76660E+00    2.34093E+01
SCF Iter 33:       101.95366436   -3.79973E+00    2.30801E+01
SCF Iter 34:       100.48746271   -1.46620E+00    2.28771E+01
SCF Iter 35:        98.76196558   -1.72550E+00    2.26768E+01
SCF Iter 36:        95.93193339   -2.83003E+00    2.24188E+01
SCF Iter 37:        92.48077205   -3.45116E+00    2.21318E+01
SCF Iter 38:        88.50929528   -3.97148E+00    2.18236E+01
SCF Iter 39:        84.61925760   -3.89004E+00    2.15208E+01
SCF Iter 40:        81.28915933   -3.33010E+00    2.12455E+01
SCF Iter 41:        79.00075992   -2.28840E+00    2.10192E+01
SCF Iter 42:        76.89722635   -2.10353E+00    2.08138E+01
SCF Iter 43:        74.56207920   -2.33515E+00    2.05965E+01
SCF Iter 44:        70.95812675   -3.60395E+00    2.03136E+01
SCF Iter 45:        67.43764836   -3.52048E+00    2.00357E+01
SCF Iter 46:        66.00936039   -1.42829E+00    1.98806E+01
SCF Iter 47:        64.63777779   -1.37158E+00    1.97244E+01
SCF Iter 48:        62.63928341   -1.99849E+00    1.95277E+01
SCF Iter 49:        60.42707747   -2.21221E+00    1.93194E+01
SCF Iter 50:        66.52466571    6.09759E+00    1.95505E+01
SCF Iter 51:        70.91900439    4.39434E+00    1.96980E+01
SCF Iter 52:        67.62716671   -3.29184E+00    1.94256E+01
SCF Iter 53:        64.41332028   -3.21385E+00    1.91579E+01
SCF Iter 54:        61.52511239   -2.88821E+00    1.88954E+01
SCF Iter 55:        58.94814860   -2.57696E+00    1.86375E+01
SCF Iter 56:        56.68989613   -2.25825E+00    1.83849E+01
SCF Iter 57:        54.45557903   -2.23432E+00    1.81357E+01
SCF Iter 58:        52.00524982   -2.45033E+00    1.78905E+01
SCF Iter 59:        49.66271265   -2.34254E+00    1.76501E+01
SCF Iter 60:        47.32553072   -2.33718E+00    1.74140E+01
SCF Iter 61:        47.15219118   -1.73340E-01    1.72446E+01
SCF Iter 62:        45.00250243   -2.14969E+00    1.70152E+01
SCF Iter 63:        42.59045631   -2.41205E+00    1.67900E+01
SCF Iter 64:        40.79251572   -1.79794E+00    1.66084E+01
SCF Iter 65:        38.99290358   -1.79961E+00    1.64345E+01
SCF Iter 66:        37.00580645   -1.98710E+00    1.62516E+01
SCF Iter 67:        35.35683426   -1.64897E+00    1.60903E+01
SCF Iter 68:        33.08501345   -2.27182E+00    1.58896E+01
SCF Iter 69:        30.79948145   -2.28553E+00    1.56814E+01
SCF Iter 70:        33.46629367    2.66681E+00    1.57370E+01
SCF Iter 71:        35.10812228    1.64183E+00    1.57453E+01
SCF Iter 72:        36.92799119    1.81987E+00    1.57648E+01
SCF Iter 73:        37.71466416    7.86673E-01    1.56830E+01
SCF Iter 74:        36.24417124   -1.47049E+00    1.54747E+01
SCF Iter 75:        34.62414904   -1.62002E+00    1.52710E+01
SCF Iter 76:        32.40424338   -2.21991E+00    1.50712E+01
SCF Iter 77:        31.21394309   -1.19030E+00    1.49464E+01
SCF Iter 78:        30.17144139   -1.04250E+00    1.48348E+01
SCF Iter 79:        30.03342093   -1.38020E-01    1.47785E+01
SCF Iter 80:        27.68702448   -2.34640E+00    1.45834E+01
SCF Iter 81:        25.56750366   -2.11952E+00    1.43912E+01
SCF Iter 82:        23.52614772   -2.04136E+00    1.42053E+01
SCF Iter 83:        21.44810698   -2.07804E+00    1.40199E+01
SCF Iter 84:        19.52856156   -1.91955E+00    1.38377E+01
SCF Iter 85:        17.79091011   -1.73765E+00    1.36585E+01
SCF Iter 86:        16.28341833   -1.50749E+00    1.34849E+01
SCF Iter 87:        15.04105136   -1.24237E+00    1.33112E+01
SCF Iter 88:        13.68517589   -1.35588E+00    1.31397E+01
SCF Iter 89:        12.19779461   -1.48738E+00    1.29721E+01
SCF Iter 90:        11.73740872   -4.60386E-01    1.28791E+01
SCF Iter 91:        11.09409440   -6.43314E-01    1.27838E+01
SCF Iter 92:        10.39496561   -6.99129E-01    1.26767E+01
SCF Iter 93:         9.05968405   -1.33528E+00    1.25167E+01
SCF Iter 94:         7.72040756   -1.33928E+00    1.23594E+01
SCF Iter 95:         7.05870907   -6.61698E-01    1.22471E+01
SCF Iter 96:         6.41600470   -6.42704E-01    1.21387E+01
SCF Iter 97:         5.81083066   -6.05174E-01    1.20425E+01
SCF Iter 98:         5.23004767   -5.80783E-01    1.19516E+01
SCF Iter 99:         3.81413601   -1.41591E+00    1.18023E+01
SCF Iter100:         2.49870032   -1.31544E+00    1.16555E+01
SCF Iter101:         1.16927897   -1.32942E+00    1.15113E+01
SCF Iter102:         0.72573086   -4.43548E-01    1.14266E+01
SCF Iter103:         0.02801861   -6.97712E-01    1.13464E+01
SCF Iter104:        -0.39398381   -4.22002E-01    1.12712E+01
SCF Iter105:        -1.28670390   -8.92720E-01    1.11823E+01
SCF Iter106:         1.12935016    2.41605E+00    1.12868E+01
SCF Iter107:         4.75530892    3.62596E+00    1.14876E+01
SCF Iter108:         6.86064672    2.10534E+00    1.15564E+01
SCF Iter109:         5.16960036   -1.69105E+00    1.14095E+01
SCF Iter110:         3.52255286   -1.64705E+00    1.12653E+01
SCF Iter111:         1.86155611   -1.66100E+00    1.11223E+01
SCF Iter112:         2.67387714    8.12321E-01    1.11336E+01
SCF Iter113:         5.35900078    2.68512E+00    1.13008E+01
SCF Iter114:         8.26554395    2.90654E+00    1.14798E+01
SCF Iter115:         8.88252644    6.16982E-01    1.14995E+01
SCF Iter116:         8.43100889   -4.51518E-01    1.14406E+01
SCF Iter117:         7.57480565   -8.56203E-01    1.13663E+01
SCF Iter118:         7.19972952   -3.75076E-01    1.13308E+01
SCF Iter119:         6.28413425   -9.15595E-01    1.11753E+01
SCF Iter120:         6.28275987   -1.37438E-03    1.10208E+01
SCF Iter121:         5.95892425   -3.23836E-01    1.08691E+01
SCF Iter122:         5.15952827   -7.99396E-01    1.07220E+01
SCF Iter123:         4.58306338   -5.76465E-01    1.05769E+01
SCF Iter124:         4.84766344    2.64600E-01    1.05243E+01
SCF Iter125:         4.09605232   -7.51611E-01    1.04731E+01
SCF Iter126:         2.38664878   -1.70940E+00    1.03364E+01
SCF Iter127:         0.74102696   -1.64562E+00    1.02023E+01
SCF Iter128:        -0.85149476   -1.59252E+00    1.00707E+01
SCF Iter129:        -2.39669234   -1.54520E+00    9.94157E+00
SCF Iter130:        -3.91352008   -1.51683E+00    9.81482E+00
SCF Iter131:         0.62378801    4.53731E+00    1.01178E+01
SCF Iter132:         5.08267687    4.45889E+00    1.04098E+01
SCF Iter133:         8.64138987    3.55871E+00    1.06235E+01
SCF Iter134:         7.83493537   -8.06454E-01    1.05593E+01
SCF Iter135:         6.86548415   -9.69451E-01    1.04822E+01
SCF Iter136:         5.71946412   -1.14602E+00    1.03432E+01
SCF Iter137:         4.91144417   -8.08020E-01    1.02031E+01
SCF Iter138:         4.02740260   -8.84042E-01    1.00910E+01
SCF Iter139:         5.18574386    1.15834E+00    1.00934E+01
SCF Iter140:         4.22659230   -9.59152E-01    9.95683E+00
SCF Iter141:         3.27039761   -9.56195E-01    9.82427E+00
SCF Iter142:         1.58209339   -1.68830E+00    9.69224E+00
SCF Iter143:         0.22140666   -1.36069E+00    9.57702E+00
SCF Iter144:        -0.92346609   -1.14487E+00    9.46780E+00
SCF Iter145:        -1.87000614   -9.46540E-01    9.36734E+00
SCF Iter146:        -3.04890677   -1.17890E+00    9.25973E+00
SCF Iter147:        -4.23336068   -1.18445E+00    9.15019E+00
SCF Iter148:        -5.44418976   -1.21083E+00    9.03666E+00
SCF Iter149:        -5.44304619    1.14357E-03    9.01754E+00
SCF Iter150:        -5.45417544   -1.11292E-02    8.99548E+00
SCF Iter151:        -5.65487015   -2.00695E-01    8.94553E+00
SCF Iter152:        -6.47172333   -8.16853E-01    8.89074E+00
SCF Iter153:        -7.93505764   -1.46333E+00    8.77308E+00
SCF Iter154:        -8.81455947   -8.79502E-01    8.70968E+00
SCF Iter155:        -9.74879108   -9.34232E-01    8.63848E+00
SCF Iter156:       -10.67342846   -9.24637E-01    8.56201E+00
SCF Iter157:       -11.16329654   -4.89868E-01    8.52298E+00
SCF Iter158:       -11.70607985   -5.42783E-01    8.48374E+00
SCF Iter159:        -9.16797740    2.53810E+00    8.63261E+00
SCF Iter160:        -7.29915613    1.86882E+00    8.72241E+00
SCF Iter161:        -7.68440129   -3.85245E-01    8.61321E+00
SCF Iter162:        -8.27403465   -5.89633E-01    8.50594E+00
SCF Iter163:        -9.24832808   -9.74293E-01    8.39687E+00
SCF Iter164:       -10.18706925   -9.38741E-01    8.28304E+00
SCF Iter165:       -10.58588963   -3.98820E-01    8.20365E+00
SCF Iter166:       -11.42953170   -8.43642E-01    8.13012E+00
SCF Iter167:       -12.13665204   -7.07120E-01    8.06732E+00
SCF Iter168:       -12.69678014   -5.60128E-01    7.99776E+00
SCF Iter169:       -13.21678624   -5.20006E-01    7.93638E+00
SCF Iter170:       -12.93759714    2.79189E-01    7.97109E+00
SCF Iter171:       -12.46215272    4.75444E-01    8.00185E+00
SCF Iter172:       -11.88992549    5.72227E-01    8.02698E+00
SCF Iter173:       -11.91598726   -2.60618E-02    8.02817E+00
SCF Iter174:       -12.00699953   -9.10123E-02    8.02720E+00
SCF Iter175:       -13.19599080   -1.18899E+00    7.92915E+00
SCF Iter176:       -14.17720861   -9.81218E-01    7.85683E+00
SCF Iter177:       -14.94659946   -7.69391E-01    7.80347E+00
SCF Iter178:       -16.24166173   -1.29506E+00    7.69564E+00
SCF Iter179:       -17.39472149   -1.15306E+00    7.59869E+00
SCF Iter180:       -18.49744838   -1.10273E+00    7.49963E+00
SCF Iter181:       -19.68733289   -1.18988E+00    7.39803E+00
SCF Iter182:       -18.91744622    7.69887E-01    7.47217E+00
SCF Iter183:       -18.10427743    8.13169E-01    7.54660E+00
SCF Iter184:       -15.49543530    2.60884E+00    7.77010E+00
SCF Iter185:       -14.23620229    1.25923E+00    7.90182E+00
SCF Iter186:       -13.27480128    9.61401E-01    8.00968E+00
SCF Iter187:       -12.05775730    1.21704E+00    8.11661E+00
SCF Iter188:       -13.12504181   -1.06728E+00    8.03576E+00
SCF Iter189:       -12.47030135    6.54740E-01    8.10916E+00
SCF Iter190:       -13.34748154   -8.77180E-01    8.05421E+00
SCF Iter191:       -14.40111461   -1.05363E+00    7.96820E+00
SCF Iter192:       -15.73534595   -1.33423E+00    7.84943E+00
SCF Iter193:       -16.53370894   -7.98363E-01    7.78679E+00
SCF Iter194:       -17.03889911   -5.05190E-01    7.73512E+00
SCF Iter195:       -17.64361235   -6.04713E-01    7.67378E+00
SCF Iter196:       -16.96506829    6.78544E-01    7.73871E+00
SCF Iter197:       -17.93779239   -9.72724E-01    7.64866E+00
SCF Iter198:       -17.60147463    3.36318E-01    7.68591E+00
SCF Iter199:       -17.51490016    8.65745E-02    7.69393E+00
SCF Iter200:       -17.59619438   -8.12942E-02    7.68183E+00
SCF Iter201:       -17.63743596   -4.12416E-02    7.68280E+00
SCF Iter202:       -18.84679868   -1.20936E+00    7.56375E+00
SCF Iter203:       -17.92596733    9.20831E-01    7.64601E+00
SCF Iter204:       -18.74419173   -8.18224E-01    7.56407E+00
SCF Iter205:       -19.54031065   -7.96119E-01    7.48544E+00
SCF Iter206:       -20.30401378   -7.63703E-01    7.40856E+00
SCF Iter207:       -21.50428040   -1.20027E+00    7.29374E+00
SCF Iter208:       -21.92409658   -4.19816E-01    7.26098E+00
SCF Iter209:       -22.31325965   -3.89163E-01    7.22729E+00
SCF Iter210:       -22.83120944   -5.17950E-01    7.17905E+00
SCF Iter211:       -23.23033038   -3.99121E-01    7.13383E+00
SCF Iter212:       -23.57311881   -3.42788E-01    7.09214E+00
SCF Iter213:       -21.89039674    1.68272E+00    7.27952E+00
SCF Iter214:       -20.28340838    1.60699E+00    7.46137E+00
SCF Iter215:       -21.27141275   -9.88004E-01    7.34097E+00
SCF Iter216:       -21.08709952    1.84313E-01    7.37947E+00
SCF Iter217:       -21.27995536   -1.92856E-01    7.35832E+00
SCF Iter218:       -22.17635045   -8.96395E-01    7.23870E+00
SCF Iter219:       -23.27359576   -1.09725E+00    7.12211E+00
SCF Iter220:       -23.69257063   -4.18975E-01    7.07693E+00
SCF Iter221:       -24.14157278   -4.49002E-01    7.02433E+00
SCF Iter222:       -24.53066322   -3.89090E-01    6.98079E+00
SCF Iter223:       -24.93314583   -4.02483E-01    6.92566E+00
SCF Iter224:       -25.42322458   -4.90079E-01    6.86063E+00
SCF Iter225:       -25.43612322   -1.28986E-02    6.86493E+00
SCF Iter226:       -26.40239917   -9.66276E-01    6.75304E+00
SCF Iter227:       -27.05197964   -6.49580E-01    6.67716E+00
SCF Iter228:       -27.49476004   -4.42780E-01    6.62010E+00
SCF Iter229:       -27.77368584   -2.78926E-01    6.58512E+00
SCF Iter230:       -28.28134208   -5.07656E-01    6.54167E+00
SCF Iter231:       -29.21839092   -9.37049E-01    6.43510E+00
SCF Iter232:       -29.73853827   -5.20147E-01    6.37573E+00
SCF Iter233:       -30.36112432   -6.22586E-01    6.31684E+00
SCF Iter234:       -29.15033009    1.21079E+00    6.44531E+00
SCF Iter235:       -28.27165832    8.78672E-01    6.52309E+00
SCF Iter236:       -29.16011939   -8.88461E-01    6.42994E+00
SCF Iter237:       -28.89139478    2.68725E-01    6.43475E+00
SCF Iter238:       -28.68050509    2.10890E-01    6.44786E+00
SCF Iter239:       -28.90687083   -2.26366E-01    6.43999E+00
SCF Iter240:       -29.71120661   -8.04336E-01    6.35619E+00
SCF Iter241:       -30.44551818   -7.34312E-01    6.28333E+00
SCF Iter242:       -31.28075502   -8.35237E-01    6.19128E+00
SCF Iter243:       -32.20524681   -9.24492E-01    6.09541E+00
SCF Iter244:       -32.87320801   -6.67961E-01    6.02131E+00
SCF Iter245:       -33.62210477   -7.48897E-01    5.93643E+00
SCF Iter246:       -34.34400598   -7.21901E-01    5.85466E+00
SCF Iter247:       -35.04396266   -6.99957E-01    5.75970E+00
SCF Iter248:       -35.85870415   -8.14741E-01    5.67477E+00
SCF Iter249:       -35.94558910   -8.68849E-02    5.66974E+00
SCF Iter250:       -35.99185907   -4.62700E-02    5.66652E+00
SCF Iter251:       -36.12290191   -1.31043E-01    5.65461E+00
SCF Iter252:       -36.21210874   -8.92068E-02    5.65074E+00
SCF Iter253:       -36.34074004   -1.28631E-01    5.64334E+00
SCF Iter254:       -36.65377881   -3.13039E-01    5.61109E+00
SCF Iter255:       -37.17059040   -5.16812E-01    5.55508E+00
SCF Iter256:       -37.48497668   -3.14386E-01    5.50435E+00
SCF Iter257:       -37.79374771   -3.08771E-01    5.42877E+00
SCF Iter258:       -38.07852560   -2.84778E-01    5.35169E+00
SCF Iter259:       -38.47023673   -3.91711E-01    5.27773E+00
SCF Iter260:       -38.89624331   -4.26007E-01    5.20358E+00
SCF Iter261:       -39.25245787   -3.56215E-01    5.13174E+00
SCF Iter262:       -39.53414845   -2.81691E-01    5.06058E+00
SCF Iter263:       -39.00116869    5.32980E-01    5.11932E+00
SCF Iter264:       -38.89687541    1.04293E-01    5.10344E+00
SCF Iter265:       -38.56106802    3.35807E-01    5.11918E+00
SCF Iter266:       -38.71964449   -1.58576E-01    5.03528E+00
SCF Iter267:       -39.10506454   -3.85420E-01    4.96735E+00
SCF Iter268:       -38.97736214    1.27702E-01    5.00454E+00
SCF Iter269:       -39.48016219   -5.02800E-01    4.93936E+00
SCF Iter270:       -39.60024610   -1.20084E-01    4.96737E+00
SCF Iter271:       -39.41483699    1.85409E-01    5.04359E+00
SCF Iter272:       -39.32266818    9.21688E-02    5.09811E+00
SCF Iter273:       -39.51237781   -1.89710E-01    5.11297E+00
SCF Iter274:       -40.11741868   -6.05041E-01    5.05458E+00
SCF Iter275:       -40.86994326   -7.52525E-01    4.97474E+00
SCF Iter276:       -39.54942257    1.32052E+00    5.22292E+00
SCF Iter277:       -38.24677017    1.30265E+00    5.42445E+00
SCF Iter278:       -38.36952489   -1.22755E-01    5.43270E+00
SCF Iter279:       -38.26993434    9.95905E-02    5.46357E+00
SCF Iter280:       -37.96816975    3.01765E-01    5.54107E+00
SCF Iter281:       -37.51481088    4.53359E-01    5.62481E+00
SCF Iter282:       -38.40343681   -8.88626E-01    5.52562E+00
SCF Iter283:       -38.67056892   -2.67132E-01    5.51148E+00
SCF Iter284:       -39.25523515   -5.84666E-01    5.43666E+00
SCF Iter285:       -39.81902251   -5.63787E-01    5.36817E+00
SCF Iter286:       -40.30483289   -4.85810E-01    5.30645E+00
SCF Iter287:       -40.85865581   -5.53823E-01    5.24226E+00
SCF Iter288:       -41.23726167   -3.78606E-01    5.20513E+00
SCF Iter289:       -41.88003867   -6.42777E-01    5.12053E+00
SCF Iter290:       -42.34405265   -4.64014E-01    5.05387E+00
SCF Iter291:       -42.78206824   -4.38016E-01    4.99123E+00
SCF Iter292:       -42.42111207    3.60956E-01    5.09447E+00
SCF Iter293:       -41.45539958    9.65712E-01    5.27022E+00
SCF Iter294:       -40.39983205    1.05557E+00    5.44805E+00
SCF Iter295:       -40.17442539    2.25407E-01    5.51406E+00
SCF Iter296:       -40.00493118    1.69494E-01    5.57255E+00
SCF Iter297:       -40.89246290   -8.87532E-01    5.46389E+00
SCF Iter298:       -40.71531100    1.77152E-01    5.51383E+00
SCF Iter299:       -40.50920057    2.06110E-01    5.56195E+00
SCF Iter300:       -40.59134210   -8.21415E-02    5.56688E+00
SCF Iter301:       -40.64381839   -5.24763E-02    5.58233E+00
SCF Iter302:       -40.84226161   -1.98443E-01    5.57725E+00
SCF Iter303:       -41.75187160   -9.09610E-01    5.46312E+00
SCF Iter304:       -42.19147834   -4.39607E-01    5.42176E+00
SCF Iter305:       -42.14105338    5.04250E-02    5.45862E+00
SCF Iter306:       -42.42042969   -2.79376E-01    5.44527E+00
SCF Iter307:       -42.76736143   -3.46932E-01    5.42314E+00
SCF Iter308:       -43.45088153   -6.83520E-01    5.34223E+00
SCF Iter309:       -44.29646563   -8.45584E-01    5.23081E+00
SCF Iter310:       -44.67617238   -3.79707E-01    5.19401E+00
SCF Iter311:       -44.82000167   -1.43829E-01    5.20153E+00
SCF Iter312:       -44.86316462   -4.31629E-02    5.22888E+00
SCF Iter313:       -45.62160694   -7.58442E-01    5.13070E+00

KeyboardInterrupt:

In [46]:
df.to_csv(csv_file, index=False)
df

,Method,Atom,Basis,Grid_Sph,Grid_Rad,"Energy,Ha",Iterations,DIIS,Damp_Start,Damp_End,Damp_Cutoff
0,TFW LDA,H,UGBS_S,6,1000,-0.243294,30,True,0.90,0.00,0.0010
1,TFW LDA,He,UGBS_S,6,1000,-1.477450,52,True,0.90,0.00,0.0010
2,TFW LDA,Li,UGBS_S,6,1000,-4.070028,74,True,0.90,0.00,0.0010
3,TFW LDA,Be,UGBS_S,6,1000,-8.492186,77,True,0.90,0.00,0.0010
4,TFW LDA,B,UGBS_S,6,1000,-14.888970,96,True,0.90,0.00,0.0010
...,...,...,...,...,...,...,...,...,...,...,...
132,TF0.111111W PBE,Li,UGBS_S,6,1000,-8.485256,1202,True,0.90,0.90,0.0001
133,TF0.111111W PBE,Be,UGBS_S,6,1000,-16.541291,430,True,0.90,0.90,0.0001
134,TF0.111111W PBE,B,UGBS_S,6,1000,-27.760995,8228,True,0.90,0.90,0.0001
135,TF0.111111W PBE,C,UGBS_S,6,1000,-42.403790,6540,True,0.99,0.90,0.0001
136,TF0.111111W PBE,N,UGBS_S,6,1000,-60.662545,3992,True,0.99,0.99,0.0001

In [22]:
ATOMS = {
    'He':  {'mult': 1}, 
    'Be': {'mult': 1},
    'Ne': {'mult': 1}, 
    'Mg': {'mult': 1},
    'Ar':  {'mult': 1}, 
    'Ca':  {'mult': 1},
    'Zn':  {'mult': 1}, 
    'Kr':  {'mult': 1}
}
psi4.core.set_output_file('output.dat', False)
psi4.set_options({'basis': 'UGBS',
                  'scf_type': 'PK'})
rhf_energies = {}
rhf_homos = {}
for atom in ATOMS:
    MOL = psi4.geometry(f"0 {ATOMS[atom]['mult']}\n {atom}\nsymmetry c1")
    E, wfn = psi4.energy('SCF', return_wfn=True)
    homo = wfn.epsilon_a().np[wfn.nalpha()-1]
    rhf_energies[atom] = round(E, 6)
    rhf_homos[atom] = round(homo, 6)
    print(f"RHF/UGBS {atom} Energy: {E:.4f} Hartree, IP: {homo:.4f}")

RHF/UGBS He Energy: -2.8617 Hartree, IP: -0.9180
RHF/UGBS Be Energy: -14.5730 Hartree, IP: -0.3093
RHF/UGBS Ne Energy: -128.5471 Hartree, IP: -0.8504
RHF/UGBS Mg Energy: -199.6146 Hartree, IP: -0.2530
RHF/UGBS Ar Energy: -526.8175 Hartree, IP: -0.5910
RHF/UGBS Ca Energy: -676.7582 Hartree, IP: -0.1955
RHF/UGBS Zn Energy: -1777.8481 Hartree, IP: -0.2925
RHF/UGBS Kr Energy: -2752.0549 Hartree, IP: -0.5242

In [26]:
atom_order = ['He', 'Be', 'Ne', 'Mg', 'Ar', 'Ca', 'Zn', 'Kr']
energy_table = df.pivot(index='Atom', columns='Method', values='Energy,Ha')
energy_table = energy_table.reindex(atom_order)
energy_table['RHF/UGBS'] = pd.Series(rhf_energies)
new_order = ['TFD0.166666W', 'TF0.166666W PBEx', 'TF0.166666W FA', 'RHF/UGBS']
energy_table = energy_table[new_order]

In [28]:
reference = energy_table['RHF/UGBS']

res = {}
for method, energies in energy_table.items():
    if method == 'RHF/UGBS': 
        continue 
    
    mae  = (energies - reference).abs().mean()
    rmae = (((energies - reference).abs()) / reference * -100).mean()
    res[method] = round(mae, 2), round(rmae, 2)

mae_row  = {method: values[0] for method, values in res.items()}
rmae_row = {method: values[1] for method, values in res.items()}
stats_df = pd.DataFrame([mae_row, rmae_row], index=['MAE(Ha)', 'rMAE(%)'])
energy_table = pd.concat([energy_table, stats_df], sort=False)

In [29]:
display(energy_table)

         TFD0.166666W  TF0.166666W PBEx  TF0.166666W FA     RHF/UGBS
He          -2.951247         -3.097069       -3.019526    -2.861680
Be         -15.040391        -15.388877      -14.660508   -14.573023
Ne        -132.508856       -133.573716     -128.291707  -128.547083
Mg        -204.540690       -205.864549     -198.305386  -199.614621
Ar        -537.208760       -539.346529     -522.928926  -526.817486
Ca        -690.396266       -692.814969     -672.808485  -676.758154
Zn       -1812.192490      -1816.067937    -1773.727670 -1777.848060
Kr       -2795.914635      -2800.696590    -2741.665221 -2752.054860
MAE(Ha)     13.960000         15.970000        3.020000          NaN
rMAE(%)      2.420000          3.690000        1.110000          NaN

In [33]:
atom_order = ['He', 'Be', 'Ne', 'Mg', 'Ar', 'Ca', 'Zn', 'Kr']
mu_table = df.pivot(index='Atom', columns='Method', values='ChemPot,Ha')
mu_table = mu_table.reindex(atom_order)
mu_table['RHF/UGBS'] = pd.Series(rhf_homos)
new_order = ['TFD0.166666W', 'TF0.166666W PBEx', 'TF0.166666W FA', 'RHF/UGBS']
mu_table = mu_table[new_order]

In [35]:
reference = mu_table['RHF/UGBS']

res = {}
for method, energies in mu_table.items():
    if method == 'RHF/UGBS': 
        continue 
    
    mae  = (energies - reference).abs().mean()
    rmae = (((energies - reference).abs()) / reference * -100).mean()
    res[method] = round(mae, 2), round(rmae, 2)

mae_row  = {method: values[0] for method, values in res.items()}
rmae_row = {method: values[1] for method, values in res.items()}
stats_df = pd.DataFrame([mae_row, rmae_row], index=['MAE(Ha)', 'rMAE(%)'])
mu_table = pd.concat([mu_table, stats_df], sort=False)

In [36]:
display(mu_table)

         TFD0.166666W  TF0.166666W PBEx  TF0.166666W FA  RHF/UGBS
He          -0.067106         -0.081193       -0.313483 -0.917956
Be          -0.069849         -0.081756       -0.272375 -0.309271
Ne          -0.072529         -0.082214       -0.231390 -0.850411
Mg          -0.072963         -0.082281       -0.224844 -0.253048
Ar          -0.073833         -0.082424       -0.211897 -0.590989
Ca          -0.074040         -0.082458       -0.208863 -0.195527
Zn          -0.074767         -0.082581       -0.198303 -0.292463
Kr          -0.075063         -0.082633       -0.194080 -0.524161
MAE(Ha)      0.420000          0.410000        0.260000       NaN
rMAE(%)     80.310000         77.800000       40.980000       NaN