In [1]:
import psi4
import pandas as pd
import os
import numpy as np
from lps_uscf import lps_solver

In [2]:
csv_file = 'open_shell_15atoms_vs_uhf.csv'

if os.path.exists(csv_file):
    df = pd.read_csv(csv_file)
    print(f"-> Loaded existing results: {len(df)} rows found.")
else:
    df = pd.DataFrame()
    print("-> No existing file found. Starting fresh.")

-> Loaded existing results: 131 rows found.

In [36]:
TP = ['LDA_K_TF', 1.0]
LAMBDA = 0.166666
EXC = ['GGA_X_PBE', 0.0, 'LDA_C_VWN', 0.0]
FA = [True, 1.0]
DIIS = True
MAX_ITER = 10000
DAMPING = [0.99, 0.9, 0.00009]
# D_guess = [GUESS_A, GUESS_B]
D_guess = None
verbose=True

psi4.set_options({'basis': 'UGBS_S', 
                  'DFT_SPHERICAL_POINTS': 6, 
                  'DFT_RADIAL_POINTS': 1000})

mol = psi4.geometry("""
units bohr
0 3
Si
symmetry c1
""")

E, Da, Db, iterations = lps_solver(MAX_ITER,TP,EXC,LAMBDA,mol,DAMPING,FA,D_guess,DIIS,verbose)
print('\nFinal SCF energy: %.6f Hartree' % E)

Number of basis functions:   31

Starting SCF iterations:

    Iter            Energy            Delta E         dRMS

SCF Iter  1:      2941.69488562    2.94169E+03    2.39654E+02
SCF Iter  2:      2873.56927670   -6.81256E+01    2.35185E+02
SCF Iter  3:      2806.79201719   -6.67773E+01    2.30797E+02
SCF Iter  4:      3708.84084848    9.02049E+02    3.39813E+02
SCF Iter  5:      4576.22860948    8.67388E+02    3.86179E+02
SCF Iter  6:      5511.80797960    9.35579E+02    4.22849E+02
SCF Iter  7:      6534.72706047    1.02292E+03    4.59503E+02
SCF Iter  8:      6416.24658169   -1.18480E+02    4.53088E+02
SCF Iter  9:      6299.37071818   -1.16876E+02    4.46784E+02
SCF Iter 10:      6188.98141998   -1.10389E+02    4.40627E+02
SCF Iter 11:      6080.59588597   -1.08386E+02    4.34732E+02
SCF Iter 12:      5973.94414341   -1.06652E+02    4.29206E+02
SCF Iter 13:      5877.81724999   -9.61269E+01    4.24064E+02
SCF Iter 14:      5782.63070633   -9.51865E+01    4.18272E+02
SCF Iter 15:      5682.66606887   -9.99646E+01    4.12808E+02
SCF Iter 16:      5591.93159164   -9.07345E+01    4.07214E+02
SCF Iter 17:      5498.25866002   -9.36729E+01    4.01701E+02
SCF Iter 18:      5410.83049681   -8.74282E+01    3.96254E+02
SCF Iter 19:      5324.27668348   -8.65538E+01    3.90912E+02
SCF Iter 20:      5234.47540664   -8.98013E+01    3.85670E+02
SCF Iter 21:      5145.55439079   -8.89210E+01    3.80516E+02
SCF Iter 22:      5055.90041281   -8.96540E+01    3.75441E+02
SCF Iter 23:      4967.69671754   -8.82037E+01    3.70441E+02
SCF Iter 24:      4881.04832591   -8.66484E+01    3.65527E+02
SCF Iter 25:      4795.95146956   -8.50969E+01    3.60691E+02
SCF Iter 26:      4713.98328728   -8.19682E+01    3.55937E+02
SCF Iter 27:      4633.27587090   -8.07074E+01    3.51264E+02
SCF Iter 28:      4553.22356917   -8.00523E+01    3.46672E+02
SCF Iter 29:      4474.78128216   -7.84423E+01    3.42159E+02
SCF Iter 30:      4397.71940301   -7.70619E+01    3.37719E+02
SCF Iter 31:      4325.99525649   -7.17241E+01    3.33347E+02
SCF Iter 32:      4255.48620108   -7.05091E+01    3.29039E+02
SCF Iter 33:      4185.13846481   -7.03477E+01    3.24802E+02
SCF Iter 34:      4117.76691404   -6.73716E+01    3.20628E+02
SCF Iter 35:      4050.98288910   -6.67840E+01    3.16514E+02
SCF Iter 36:      3979.27368549   -7.17092E+01    3.12487E+02
SCF Iter 37:      3909.32467127   -6.99490E+01    3.08526E+02
SCF Iter 38:      3843.65204077   -6.56726E+01    3.04628E+02
SCF Iter 39:      3787.01815528   -5.66339E+01    3.00772E+02
SCF Iter 40:      3724.81483604   -6.22033E+01    2.96982E+02
SCF Iter 41:      3663.90552019   -6.09093E+01    2.93255E+02
SCF Iter 42:      3609.97714540   -5.39284E+01    2.89582E+02
SCF Iter 43:      3550.96682109   -5.90103E+01    2.85967E+02
SCF Iter 44:      3492.44275122   -5.85241E+01    2.82399E+02
SCF Iter 45:      3435.70566550   -5.67371E+01    2.78903E+02
SCF Iter 46:      3373.94632022   -6.17593E+01    2.75471E+02
SCF Iter 47:      3327.98247163   -4.59638E+01    2.72073E+02
SCF Iter 48:      3272.74320368   -5.52393E+01    2.68744E+02
SCF Iter 49:      3220.27943206   -5.24638E+01    2.65465E+02
SCF Iter 50:      3167.81994195   -5.24595E+01    2.62235E+02
SCF Iter 51:      3119.43441479   -4.83855E+01    2.59060E+02
SCF Iter 52:      3073.10287750   -4.63315E+01    2.55931E+02
SCF Iter 53:      3029.25252820   -4.38503E+01    2.52840E+02
SCF Iter 54:      2983.69179225   -4.55607E+01    2.49794E+02
SCF Iter 55:      2938.33876542   -4.53530E+01    2.46781E+02
SCF Iter 56:      2894.08154863   -4.42572E+01    2.43809E+02
SCF Iter 57:      2850.61347312   -4.34681E+01    2.40905E+02
SCF Iter 58:      2803.84622708   -4.67672E+01    2.38048E+02
SCF Iter 59:      2756.42348811   -4.74227E+01    2.35235E+02
SCF Iter 60:      2714.62341059   -4.18001E+01    2.32455E+02
SCF Iter 61:      2672.79982289   -4.18236E+01    2.29718E+02
SCF Iter 62:      2628.40477686   -4.43950E+01    2.27034E+02
SCF Iter 63:      2583.67074982   -4.47340E+01    2.24388E+02
SCF Iter 64:      2538.23097703   -4.54398E+01    2.21781E+02
SCF Iter 65:      2493.62472148   -4.46063E+01    2.19212E+02
SCF Iter 66:      2449.87463312   -4.37501E+01    2.16680E+02
SCF Iter 67:      2408.28504543   -4.15896E+01    2.14185E+02
SCF Iter 68:      2367.17356994   -4.11115E+01    2.11726E+02
SCF Iter 69:      2326.69593391   -4.04776E+01    2.09302E+02
SCF Iter 70:      2286.70933949   -3.99866E+01    2.06916E+02
SCF Iter 71:      2248.01228874   -3.86971E+01    2.04565E+02
SCF Iter 72:      2239.27831212   -8.73398E+00    2.01916E+02
SCF Iter 73:      2198.33143584   -4.09469E+01    1.99616E+02
SCF Iter 74:      2162.50200181   -3.58294E+01    1.97350E+02
SCF Iter 75:      2125.03487604   -3.74671E+01    1.95117E+02
SCF Iter 76:      2088.69279807   -3.63421E+01    1.92914E+02
SCF Iter 77:      2052.55229069   -3.61405E+01    1.90743E+02
SCF Iter 78:      2017.16044663   -3.53918E+01    1.88601E+02
SCF Iter 79:      1985.19053174   -3.19699E+01    1.86492E+02
SCF Iter 80:      1954.55265273   -3.06379E+01    1.84413E+02
SCF Iter 81:      1924.60354118   -2.99491E+01    1.82362E+02
SCF Iter 82:      1925.32721840    7.23677E-01    1.79907E+02
SCF Iter 83:      1913.60295655   -1.17243E+01    1.77866E+02
SCF Iter 84:      1885.57007049   -2.80329E+01    1.75860E+02
SCF Iter 85:      1858.55128183   -2.70188E+01    1.73872E+02
SCF Iter 86:      1831.84102580   -2.67103E+01    1.71915E+02
SCF Iter 87:      1806.56892108   -2.52721E+01    1.69984E+02
SCF Iter 88:      1781.43674496   -2.51322E+01    1.68086E+02
SCF Iter 89:      1749.33187721   -3.21049E+01    1.66230E+02
SCF Iter 90:      1720.56411599   -2.87678E+01    1.64412E+02
SCF Iter 91:      1691.18040854   -2.93837E+01    1.62607E+02
SCF Iter 92:      1661.78040159   -2.94000E+01    1.60831E+02
SCF Iter 93:      1633.33169718   -2.84487E+01    1.59078E+02
SCF Iter 94:      1604.55451656   -2.87772E+01    1.57345E+02
SCF Iter 95:      1575.31923813   -2.92353E+01    1.55636E+02
SCF Iter 96:      1546.84756964   -2.84717E+01    1.53950E+02
SCF Iter 97:      1519.19876903   -2.76488E+01    1.52287E+02
SCF Iter 98:      1492.25991265   -2.69389E+01    1.50645E+02
SCF Iter 99:      1465.79934599   -2.64606E+01    1.49026E+02
SCF Iter100:      1440.97102267   -2.48283E+01    1.47427E+02
SCF Iter101:      1417.10963554   -2.38614E+01    1.45850E+02
SCF Iter102:      1393.89458052   -2.32151E+01    1.44294E+02
SCF Iter103:      1371.11865806   -2.27759E+01    1.42759E+02
SCF Iter104:      1348.89543249   -2.22232E+01    1.41239E+02
SCF Iter105:      1327.87473318   -2.10207E+01    1.39737E+02
SCF Iter106:      1307.37719725   -2.04975E+01    1.38255E+02
SCF Iter107:      1285.77921760   -2.15980E+01    1.36796E+02
SCF Iter108:      1269.80584817   -1.59734E+01    1.35312E+02
SCF Iter109:      1248.41323643   -2.13926E+01    1.33890E+02
SCF Iter110:      1227.22427064   -2.11890E+01    1.32485E+02
SCF Iter111:      1206.93383661   -2.02904E+01    1.31095E+02
SCF Iter112:      1185.24276200   -2.16911E+01    1.29726E+02
SCF Iter113:      1164.60689247   -2.06359E+01    1.28376E+02
SCF Iter114:      1156.48851392   -8.11838E+00    1.26758E+02
SCF Iter115:      1135.50902111   -2.09795E+01    1.25438E+02
SCF Iter116:      1114.88061491   -2.06284E+01    1.24133E+02
SCF Iter117:      1095.01816847   -1.98624E+01    1.22846E+02
SCF Iter118:      1075.44159020   -1.95766E+01    1.21573E+02
SCF Iter119:      1083.63224281    8.19065E+00    1.19539E+02
SCF Iter120:      1063.55001554   -2.00822E+01    1.18294E+02
SCF Iter121:      1043.77207120   -1.97779E+01    1.17065E+02
SCF Iter122:      1047.17022261    3.39815E+00    1.15115E+02
SCF Iter123:      1031.59998426   -1.55702E+01    1.13875E+02
SCF Iter124:      1022.30920087   -9.29078E+00    1.12598E+02
SCF Iter125:      1004.84839392   -1.74608E+01    1.11426E+02
SCF Iter126:       986.49192412   -1.83565E+01    1.10261E+02
SCF Iter127:       968.50546457   -1.79865E+01    1.09110E+02
SCF Iter128:       950.06605524   -1.84394E+01    1.07972E+02
SCF Iter129:       954.13189555    4.06584E+00    1.06318E+02
SCF Iter130:       935.48526770   -1.86466E+01    1.05204E+02
SCF Iter131:       918.81956704   -1.66657E+01    1.04111E+02
SCF Iter132:       901.94339415   -1.68762E+01    1.03029E+02
SCF Iter133:       885.26298825   -1.66804E+01    1.01962E+02
SCF Iter134:       868.56530670   -1.66977E+01    1.00906E+02
SCF Iter135:       851.54418164   -1.70211E+01    9.98620E+01
SCF Iter136:       866.55419677    1.50100E+01    9.80711E+01
SCF Iter137:       871.33754969    4.78335E+00    9.68107E+01
SCF Iter138:       860.48825207   -1.08493E+01    9.58274E+01
SCF Iter139:       846.22030197   -1.42680E+01    9.48454E+01
SCF Iter140:       829.72179468   -1.64985E+01    9.38415E+01
SCF Iter141:       823.99358049   -5.72821E+00    9.27595E+01
SCF Iter142:       816.80636377   -7.18722E+00    9.17398E+01
SCF Iter143:       805.82791548   -1.09784E+01    9.07656E+01
SCF Iter144:       789.35602891   -1.64719E+01    8.97969E+01
SCF Iter145:       788.02061281   -1.33542E+00    8.89167E+01
SCF Iter146:       771.85651333   -1.61641E+01    8.79622E+01
SCF Iter147:       756.22062431   -1.56359E+01    8.70248E+01
SCF Iter148:       741.13320307   -1.50874E+01    8.60991E+01
SCF Iter149:       726.29841452   -1.48348E+01    8.51863E+01
SCF Iter150:       743.97279032    1.76744E+01    8.31765E+01
SCF Iter151:       751.73979546    7.76701E+00    8.18599E+01
SCF Iter152:       766.01018737    1.42704E+01    8.08105E+01
SCF Iter153:       751.28244993   -1.47277E+01    7.99136E+01
SCF Iter154:       735.36855868   -1.59139E+01    7.90105E+01
SCF Iter155:       720.36825808   -1.50003E+01    7.81287E+01
SCF Iter156:       705.50912320   -1.48591E+01    7.72600E+01
SCF Iter157:       690.49098122   -1.50181E+01    7.63991E+01
SCF Iter158:       690.31937714   -1.71604E-01    7.54963E+01
SCF Iter159:       675.88415336   -1.44352E+01    7.46541E+01
SCF Iter160:       661.84870797   -1.40354E+01    7.38215E+01
SCF Iter161:       648.33858774   -1.35101E+01    7.30059E+01
SCF Iter162:       635.05721468   -1.32814E+01    7.22024E+01
SCF Iter163:       621.39009030   -1.36671E+01    7.14047E+01
SCF Iter164:       626.86703173    5.47694E+00    7.04608E+01
SCF Iter165:       614.24176423   -1.26253E+01    6.96900E+01
SCF Iter166:       601.83715025   -1.24046E+01    6.89309E+01
SCF Iter167:       589.65890378   -1.21782E+01    6.81834E+01
SCF Iter168:       577.36328248   -1.22956E+01    6.74421E+01
SCF Iter169:       583.45905747    6.09577E+00    6.63970E+01
SCF Iter170:       579.71844812   -3.74061E+00    6.57362E+01
SCF Iter171:       568.47428151   -1.12442E+01    6.50331E+01
SCF Iter172:       555.83634125   -1.26379E+01    6.42980E+01
SCF Iter173:       549.68027529   -6.15607E+00    6.36185E+01
SCF Iter174:       548.18354174   -1.49673E+00    6.30213E+01
SCF Iter175:       542.54691196   -5.63663E+00    6.24511E+01
SCF Iter176:       535.87962903   -6.66728E+00    6.18502E+01
SCF Iter177:       523.54231413   -1.23373E+01    6.11306E+01
SCF Iter178:       517.80040620   -5.74191E+00    6.05767E+01
SCF Iter179:       512.18094176   -5.61946E+00    6.00527E+01
SCF Iter180:       501.99279504   -1.01881E+01    5.93938E+01
SCF Iter181:       495.80517215   -6.18762E+00    5.87396E+01
SCF Iter182:       490.26225268   -5.54292E+00    5.80764E+01
SCF Iter183:       488.71028618   -1.55197E+00    5.75919E+01
SCF Iter184:       485.52737518   -3.18291E+00    5.71424E+01
SCF Iter185:       477.91144493   -7.61593E+00    5.66281E+01
SCF Iter186:       471.45272712   -6.45872E+00    5.61481E+01
SCF Iter187:       460.56675368   -1.08860E+01    5.54735E+01
SCF Iter188:       450.15526587   -1.04115E+01    5.48045E+01
SCF Iter189:       441.15592145   -8.99934E+00    5.41499E+01
SCF Iter190:       432.10819033   -9.04773E+00    5.35050E+01
SCF Iter191:       444.70035364    1.25922E+01    5.34227E+01
SCF Iter192:       457.10424857    1.24039E+01    5.39772E+01
SCF Iter193:       469.34880571    1.22446E+01    5.49871E+01
SCF Iter194:       458.34982140   -1.09990E+01    5.42301E+01
SCF Iter195:       446.80113501   -1.15487E+01    5.34914E+01
SCF Iter196:       435.63562423   -1.11655E+01    5.27760E+01
SCF Iter197:       424.81233077   -1.08233E+01    5.20602E+01
SCF Iter198:       418.66909456   -6.14324E+00    5.17456E+01
SCF Iter199:       413.25757075   -5.41152E+00    5.15205E+01
SCF Iter200:       403.03731412   -1.02203E+01    5.08653E+01
SCF Iter201:       393.03687633   -1.00004E+01    5.02112E+01
SCF Iter202:       383.10481809   -9.93206E+00    4.95674E+01
SCF Iter203:       373.18716803   -9.91765E+00    4.88988E+01
SCF Iter204:       363.73372956   -9.45344E+00    4.82747E+01
SCF Iter205:       355.22519981   -8.50853E+00    4.77087E+01
SCF Iter206:       347.11116149   -8.11404E+00    4.70941E+01
SCF Iter207:       338.72716636   -8.38400E+00    4.65378E+01
SCF Iter208:       331.30346258   -7.42370E+00    4.59592E+01
SCF Iter209:       323.41978153   -7.88368E+00    4.53702E+01
SCF Iter210:       315.16608614   -8.25370E+00    4.47825E+01
SCF Iter211:       307.30837427   -7.85771E+00    4.42250E+01
SCF Iter212:       298.97419404   -8.33418E+00    4.36700E+01
SCF Iter213:       290.62861070   -8.34558E+00    4.31098E+01
SCF Iter214:       283.44015905   -7.18845E+00    4.25765E+01
SCF Iter215:       275.88966627   -7.55049E+00    4.20325E+01
SCF Iter216:       275.90458629    1.49200E-02    4.11606E+01
SCF Iter217:       268.48028365   -7.42430E+00    4.06383E+01
SCF Iter218:       261.06032927   -7.41995E+00    4.01239E+01
SCF Iter219:       254.90569090   -6.15464E+00    3.96151E+01
SCF Iter220:       248.17783185   -6.72786E+00    3.91201E+01
SCF Iter221:       251.21315885    3.03533E+00    3.94580E+01
SCF Iter222:       243.47472422   -7.73843E+00    3.89372E+01
SCF Iter223:       236.05271483   -7.42201E+00    3.84268E+01
SCF Iter224:       228.74540532   -7.30731E+00    3.79261E+01
SCF Iter225:       221.33292785   -7.41248E+00    3.74339E+01
SCF Iter226:       225.25786210    3.92493E+00    3.69643E+01
SCF Iter227:       224.47463082   -7.83231E-01    3.69934E+01
SCF Iter228:       219.39133594   -5.08329E+00    3.66458E+01
SCF Iter229:       213.69038237   -5.70095E+00    3.62424E+01
SCF Iter230:       207.48945478   -6.20093E+00    3.58004E+01
SCF Iter231:       200.14942630   -7.34003E+00    3.53103E+01
SCF Iter232:       193.85322463   -6.29620E+00    3.48872E+01
SCF Iter233:       190.56408938   -3.28914E+00    3.47070E+01
SCF Iter234:       186.62970293   -3.93439E+00    3.44281E+01
SCF Iter235:       180.09575668   -6.53395E+00    3.39940E+01
SCF Iter236:       173.37587836   -6.71988E+00    3.35276E+01
SCF Iter237:       167.08309583   -6.29278E+00    3.30724E+01
SCF Iter238:       163.01725975   -4.06584E+00    3.26139E+01
SCF Iter239:       159.32629098   -3.69097E+00    3.21772E+01
SCF Iter240:       156.10106506   -3.22523E+00    3.18302E+01
SCF Iter241:       152.52029005   -3.58078E+00    3.14558E+01
SCF Iter242:       147.01330791   -5.50698E+00    3.10601E+01
SCF Iter243:       143.92129329   -3.09201E+00    3.08853E+01
SCF Iter244:       140.81012092   -3.11117E+00    3.07176E+01
SCF Iter245:       137.52063145   -3.28949E+00    3.05869E+01
SCF Iter246:       133.47025706   -4.05037E+00    3.03970E+01
SCF Iter247:       132.72497281   -7.45284E-01    2.98642E+01
SCF Iter248:       126.63089851   -6.09407E+00    2.94434E+01
SCF Iter249:       120.88424932   -5.74665E+00    2.90569E+01
SCF Iter250:       115.17830851   -5.70594E+00    2.86700E+01
SCF Iter251:       110.76758182   -4.41073E+00    2.83368E+01
SCF Iter252:       106.17862141   -4.58896E+00    2.79620E+01
SCF Iter253:       101.89113107   -4.28749E+00    2.75825E+01
SCF Iter254:        99.43945010   -2.45168E+00    2.72255E+01
SCF Iter255:        95.87651166   -3.56294E+00    2.68853E+01
SCF Iter256:        98.07716047    2.20065E+00    2.72223E+01
SCF Iter257:        92.68791607   -5.38924E+00    2.68615E+01
SCF Iter258:        87.79855258   -4.88936E+00    2.65816E+01
SCF Iter259:        86.11270278   -1.68585E+00    2.64049E+01
SCF Iter260:        83.03364842   -3.07905E+00    2.60581E+01
SCF Iter261:        80.15233016   -2.88132E+00    2.57199E+01
SCF Iter262:        75.07871456   -5.07362E+00    2.53523E+01
SCF Iter263:        70.56755855   -4.51116E+00    2.49887E+01
SCF Iter264:        69.48497270   -1.08259E+00    2.46769E+01
SCF Iter265:        64.68472499   -4.80025E+00    2.43032E+01
SCF Iter266:        60.94588811   -3.73884E+00    2.39982E+01
SCF Iter267:        56.71698368   -4.22890E+00    2.36786E+01
SCF Iter268:        52.54437007   -4.17261E+00    2.33659E+01
SCF Iter269:        48.25286439   -4.29151E+00    2.30542E+01
SCF Iter270:        43.53133302   -4.72153E+00    2.27144E+01
SCF Iter271:        39.04656368   -4.48477E+00    2.23833E+01
SCF Iter272:        51.75036335    1.27038E+01    2.17550E+01
SCF Iter273:        57.56571249    5.81535E+00    2.19476E+01
SCF Iter274:        61.25686280    3.69115E+00    2.23165E+01
SCF Iter275:        70.96556933    9.70871E+00    2.34579E+01
SCF Iter276:        68.90444529   -2.06112E+00    2.34568E+01
SCF Iter277:        63.36195859   -5.54249E+00    2.29820E+01
SCF Iter278:        60.64988675   -2.71207E+00    2.28020E+01
SCF Iter279:        56.84437196   -3.80551E+00    2.25095E+01
SCF Iter280:        53.27565913   -3.56871E+00    2.22534E+01
SCF Iter281:        49.11566762   -4.15999E+00    2.19411E+01
SCF Iter282:        45.13543449   -3.98023E+00    2.16501E+01
SCF Iter283:        40.35796835   -4.77747E+00    2.12338E+01
SCF Iter284:        39.84144708   -5.16521E-01    2.13019E+01
SCF Iter285:        38.39984579   -1.44160E+00    2.12963E+01
SCF Iter286:        37.79572178   -6.04124E-01    2.14433E+01
SCF Iter287:        33.32869064   -4.46703E+00    2.10864E+01
SCF Iter288:        30.55629015   -2.77240E+00    2.09025E+01
SCF Iter289:        26.42984546   -4.12644E+00    2.05913E+01
SCF Iter290:        22.92770950   -3.50214E+00    2.03143E+01
SCF Iter291:        19.88670349   -3.04101E+00    1.99687E+01
SCF Iter292:        27.56874491    7.68204E+00    2.10262E+01
SCF Iter293:        23.71292380   -3.85582E+00    2.06020E+01
SCF Iter294:        21.62691318   -2.08601E+00    2.04974E+01
SCF Iter295:        19.39954596   -2.22737E+00    2.03680E+01
SCF Iter296:        16.88452531   -2.51502E+00    2.00998E+01
SCF Iter297:        13.78924353   -3.09528E+00    1.98360E+01
SCF Iter298:        10.40099814   -3.38825E+00    1.94249E+01
SCF Iter299:         5.93859880   -4.46240E+00    1.89873E+01
SCF Iter300:         1.71595816   -4.22264E+00    1.85841E+01
SCF Iter301:         1.49542395   -2.20534E-01    1.87765E+01
SCF Iter302:         0.23655310   -1.25887E+00    1.88152E+01
SCF Iter303:        -2.82232201   -3.05888E+00    1.85642E+01
SCF Iter304:        -4.62578866   -1.80347E+00    1.85134E+01
SCF Iter305:        -6.09892450   -1.47314E+00    1.85060E+01
SCF Iter306:        -8.84464260   -2.74572E+00    1.83198E+01
SCF Iter307:       -10.59933152   -1.75469E+00    1.82721E+01
SCF Iter308:       -14.14663508   -3.54730E+00    1.79436E+01
SCF Iter309:       -18.51572092   -4.36909E+00    1.75210E+01
SCF Iter310:       -21.49132834   -2.97561E+00    1.73108E+01
SCF Iter311:       -24.84023556   -3.34891E+00    1.70391E+01
SCF Iter312:       -28.17348361   -3.33325E+00    1.67480E+01
SCF Iter313:       -32.25598258   -4.08250E+00    1.63528E+01
SCF Iter314:       -33.74799670   -1.49201E+00    1.63839E+01
SCF Iter315:       -36.62903863   -2.88104E+00    1.61851E+01
SCF Iter316:       -39.75117475   -3.12214E+00    1.59382E+01
SCF Iter317:       -41.80262080   -2.05145E+00    1.58432E+01
SCF Iter318:       -44.21678657   -2.41417E+00    1.56749E+01
SCF Iter319:       -47.94613945   -3.72935E+00    1.52721E+01
SCF Iter320:       -50.40940946   -2.46327E+00    1.50547E+01

In [37]:
GUESS_A = Da
GUESS_B = Db

In [39]:
psi4.core.set_output_file('output.dat', False)

ATOMS = {
    # Period 3 (Na-Ar)
    # 'Na': {'mult': 2},  # [Ne] 3s1
    # 'Mg': {'mult': 1},  # [Ne] 3s2
    # 'Al': {'mult': 2},  # [Ne] 3s2 3p1
    'Si': {'mult': 3},  # [Ne] 3s2 3p2 
    # 'P':  {'mult': 4},  # [Ne] 3s2 3p3 
    # 'S':  {'mult': 3},  # [Ne] 3s2 3p4
    # 'Cl': {'mult': 2},  # [Ne] 3s2 3p5
    # 'Ar': {'mult': 1},  # [Ne] 3s2 3p6
    # Period 4 (Selected)
    # 'K':  {'mult': 2},  # [Ar] 4s1
    # 'Ca': {'mult': 1},  # [Ar] 4s2
    # 'Cu': {'mult': 2},  # [Ar] 3d10 4s1 
    # 'Zn': {'mult': 1},  # [Ar] 3d10 4s2
    # 'Kr': {'mult': 1},  # [Ar] 3d10 4s2 4p6
}

METHOD = "TF0.111111W FA"
TP = ['LDA_K_TF', 1.0]
LAMBDA = 0.111111
# EXC = ['LDA_X', 1.0, 'LDA_C_VWN', 0.0]
EXC = ['GGA_X_PBE', 0.0, 'LDA_C_VWN', 0.0]
FA = [True, 1.0]
DIIS = True
MAX_ITER = 10000
DAMPING = [0.99, 0.9, 0.00002]
D_guess = [GUESS_A, GUESS_B]
# D_guess = None
verbose=True

psi4.set_options({'basis': 'UGBS_S', 
                  'DFT_SPHERICAL_POINTS': 6, 
                  'DFT_RADIAL_POINTS': 1000})

for atom in ATOMS:
    
    if not df.empty:
        exists = df[
            (df['Atom'] == atom) & 
            (df['Method'] == METHOD) & 
            (df['Basis'] == psi4.core.get_global_option("BASIS"))
        ]
        if not exists.empty:
            print(f"Skipping {atom} (Already exists for {METHOD}/{psi4.core.get_global_option("BASIS")})")
            continue

    print(f"Calculating {atom} with {METHOD}...")
    MOL = psi4.geometry(f"0 {ATOMS[atom]['mult']}\n {atom}\nsymmetry c1")
    try:
        E, Da, Db, iterations = lps_solver(MAX_ITER,TP,EXC,LAMBDA,MOL,DAMPING,FA,D_guess,DIIS,verbose)
        if iterations >= MAX_ITER:
            print("  !!! SCF failed to converge (Max cycles exceeded).")
        else:
            print(f"Calculated Energy: {E:.4f} Hartree")
            row = {
                "Method": METHOD,
                "Atom": atom,
                "Basis": psi4.core.get_global_option("BASIS"),
                "Grid_Sph": psi4.core.get_global_option("DFT_SPHERICAL_POINTS"),
                "Grid_Rad": psi4.core.get_global_option("DFT_RADIAL_POINTS"),
                "Energy,Ha": round(E, 6),
                "Iterations": iterations,
                "DIIS": DIIS,
                "Damp_Start": DAMPING[0],
                "Damp_End": DAMPING[1],
                "Damp_Cutoff": DAMPING[2]
            }
            
            df = pd.concat([df, pd.DataFrame([row])], ignore_index=True)
    
    except Exception as e:
        print(f"  !!! Failed {atom}. Error: {e}")
        continue

Calculating Si with TF0.111111W FA...
Number of basis functions:   31

Starting SCF iterations:

    Iter            Energy            Delta E         dRMS

SCF Iter  1:      -299.54021904   -2.99540E+02    1.33686E+01
SCF Iter  2:      -299.66516969   -1.24951E-01    1.32038E+01
SCF Iter  3:      -299.69539611   -3.02264E-02    1.31403E+01
SCF Iter  4:      -299.62985658    6.55395E-02    1.31388E+01
SCF Iter  5:      -299.44797395    1.81883E-01    1.31454E+01
SCF Iter  6:      -299.22782467    2.20149E-01    1.31595E+01
SCF Iter  7:      -298.95770296    2.70122E-01    1.31802E+01
SCF Iter  8:      -296.16450842    2.79319E+00    1.39714E+01
SCF Iter  9:      -295.79915507    3.65353E-01    1.39465E+01
SCF Iter 10:      -293.05142263    2.74773E+00    1.36682E+01
SCF Iter 11:      -285.20748762    7.84394E+00    1.46237E+01
SCF Iter 12:      -266.83549764    1.83720E+01    1.81630E+01
SCF Iter 13:      -267.58873589   -7.53238E-01    1.78578E+01
SCF Iter 14:      -259.20222496    8.38651E+00    1.89986E+01
SCF Iter 15:      -254.57174811    4.63048E+00    1.99901E+01
SCF Iter 16:      -255.22145567   -6.49708E-01    1.98286E+01
SCF Iter 17:      -255.69491986   -4.73464E-01    1.96930E+01
SCF Iter 18:      -256.08857705   -3.93657E-01    1.95009E+01
SCF Iter 19:      -257.08804700   -9.99470E-01    1.91217E+01
SCF Iter 20:      -257.83543989   -7.47393E-01    1.88020E+01
SCF Iter 21:      -254.42666573    3.40877E+00    1.92297E+01
SCF Iter 22:      -255.41040893   -9.83743E-01    1.88210E+01
SCF Iter 23:      -255.52298763   -1.12579E-01    1.86879E+01
SCF Iter 24:      -256.23990955   -7.16922E-01    1.83667E+01
SCF Iter 25:      -257.06468256   -8.24773E-01    1.79942E+01
SCF Iter 26:      -257.63102669   -5.66344E-01    1.76378E+01
SCF Iter 27:      -257.02637594    6.04651E-01    1.76695E+01
SCF Iter 28:      -257.67840647   -6.52031E-01    1.73090E+01
SCF Iter 29:      -242.75517240    1.49232E+01    2.02389E+01
SCF Iter 30:      -225.76710749    1.69881E+01    2.34685E+01
SCF Iter 31:      -227.34993101   -1.58282E+00    2.29464E+01
SCF Iter 32:      -228.91767844   -1.56775E+00    2.24427E+01
SCF Iter 33:      -197.40804899    3.15096E+01    2.68792E+01
SCF Iter 34:      -199.66064111   -2.25259E+00    2.62904E+01
SCF Iter 35:      -201.68787075   -2.02723E+00    2.57188E+01
SCF Iter 36:      -203.68942377   -2.00155E+00    2.51642E+01
SCF Iter 37:      -205.15126696   -1.46184E+00    2.47233E+01
SCF Iter 38:      -206.79595356   -1.64469E+00    2.43098E+01
SCF Iter 39:      -202.10945946    4.68649E+00    2.51418E+01
SCF Iter 40:      -197.48893732    4.62052E+00    2.62452E+01
SCF Iter 41:      -199.46206873   -1.97313E+00    2.57280E+01
SCF Iter 42:      -190.69580620    8.76626E+00    2.62892E+01
SCF Iter 43:      -192.60176203   -1.90596E+00    2.57905E+01
SCF Iter 44:      -190.48785143    2.11391E+00    2.62763E+01
SCF Iter 45:      -187.57290972    2.91494E+00    2.70534E+01
SCF Iter 46:      -185.66709338    1.90582E+00    2.75130E+01
SCF Iter 47:      -188.39170001   -2.72461E+00    2.67924E+01
SCF Iter 48:      -191.12801100   -2.73631E+00    2.61200E+01
SCF Iter 49:      -193.64242295   -2.51441E+00    2.54342E+01
SCF Iter 50:      -190.17009600    3.47233E+00    2.62061E+01
SCF Iter 51:      -186.93901029    3.23109E+00    2.69239E+01
SCF Iter 52:      -181.38224851    5.55676E+00    2.80593E+01
SCF Iter 53:      -183.82142474   -2.43918E+00    2.75633E+01
SCF Iter 54:      -185.88938138   -2.06796E+00    2.71789E+01
SCF Iter 55:      -188.54957810   -2.66020E+00    2.65230E+01
SCF Iter 56:      -190.87822254   -2.32864E+00    2.59922E+01
SCF Iter 57:      -193.02053300   -2.14231E+00    2.55030E+01
SCF Iter 58:      -195.07512619   -2.05459E+00    2.50263E+01
SCF Iter 59:      -197.08916309   -2.01404E+00    2.45551E+01
SCF Iter 60:      -199.15751085   -2.06835E+00    2.40639E+01
SCF Iter 61:      -201.06264027   -1.90513E+00    2.36325E+01
SCF Iter 62:      -190.34394667    1.07187E+01    2.59529E+01
SCF Iter 63:      -178.32566246    1.20183E+01    2.84822E+01
SCF Iter 64:      -180.07365753   -1.74800E+00    2.82556E+01
SCF Iter 65:      -181.91714424   -1.84349E+00    2.79854E+01
SCF Iter 66:      -183.58052442   -1.66338E+00    2.77254E+01
SCF Iter 67:      -186.37487769   -2.79435E+00    2.69957E+01
SCF Iter 68:      -189.07861734   -2.70374E+00    2.63367E+01
SCF Iter 69:      -191.30929020   -2.23067E+00    2.58259E+01
SCF Iter 70:      -193.26411188   -1.95482E+00    2.54122E+01
SCF Iter 71:      -179.15575155    1.41084E+01    2.82091E+01
SCF Iter 72:      -181.12058706   -1.96484E+00    2.78837E+01
SCF Iter 73:      -183.19382918   -2.07324E+00    2.75470E+01
SCF Iter 74:      -184.60846856   -1.41464E+00    2.73646E+01
SCF Iter 75:      -187.07351913   -2.46505E+00    2.68078E+01
SCF Iter 76:      -189.24695548   -2.17344E+00    2.63471E+01
SCF Iter 77:      -191.80772262   -2.56077E+00    2.56413E+01
SCF Iter 78:      -193.33856901   -1.53085E+00    2.53546E+01
SCF Iter 79:      -194.84464809   -1.50608E+00    2.50551E+01
SCF Iter 80:      -196.30762363   -1.46298E+00    2.47584E+01
SCF Iter 81:      -197.57886056   -1.27124E+00    2.44891E+01
SCF Iter 82:      -196.53060323    1.04826E+00    2.48881E+01
SCF Iter 83:      -197.04631059   -5.15707E-01    2.49682E+01
SCF Iter 84:      -198.25626357   -1.20995E+00    2.47657E+01
SCF Iter 85:      -200.48544235   -2.22918E+00    2.42855E+01
SCF Iter 86:      -202.21940766   -1.73397E+00    2.39212E+01
SCF Iter 87:      -203.77572662   -1.55632E+00    2.35881E+01
SCF Iter 88:      -205.63916278   -1.86344E+00    2.31096E+01
SCF Iter 89:      -207.75628378   -2.11712E+00    2.24612E+01
SCF Iter 90:      -209.38538860   -1.62910E+00    2.21023E+01
SCF Iter 91:      -211.20520491   -1.81982E+00    2.16223E+01
SCF Iter 92:      -208.87773187    2.32747E+00    2.22695E+01
SCF Iter 93:      -208.38021713    4.97515E-01    2.26264E+01
SCF Iter 94:      -210.08366868   -1.70345E+00    2.22481E+01
SCF Iter 95:      -211.37405821   -1.29039E+00    2.20517E+01
SCF Iter 96:      -213.53989204   -2.16583E+00    2.14198E+01
SCF Iter 97:      -215.02283191   -1.48294E+00    2.11334E+01
SCF Iter 98:      -215.67152098   -6.48689E-01    2.10929E+01
SCF Iter 99:      -215.89610046   -2.24579E-01    2.11573E+01
SCF Iter100:      -217.15053283   -1.25443E+00    2.09540E+01
SCF Iter101:      -218.59887292   -1.44834E+00    2.06450E+01
SCF Iter102:      -219.92030174   -1.32143E+00    2.03142E+01
SCF Iter103:      -221.27322567   -1.35292E+00    2.00021E+01
SCF Iter104:      -222.75738256   -1.48416E+00    1.96435E+01
SCF Iter105:      -221.78668850    9.70694E-01    2.00670E+01
SCF Iter106:      -221.38327588    4.03413E-01    2.03456E+01
SCF Iter107:      -220.90359772    4.79678E-01    2.06236E+01
SCF Iter108:      -221.51434166   -6.10744E-01    2.05666E+01
SCF Iter109:      -223.01334518   -1.49900E+00    2.02030E+01
SCF Iter110:      -223.86151346   -8.48168E-01    2.00416E+01
SCF Iter111:      -224.43838072   -5.76867E-01    1.98556E+01
SCF Iter112:      -225.16601170   -7.27631E-01    1.96963E+01
SCF Iter113:      -226.33604905   -1.17004E+00    1.94511E+01
SCF Iter114:      -221.46570671    4.87034E+00    2.07553E+01
SCF Iter115:      -223.56078929   -2.09508E+00    2.01284E+01
SCF Iter116:      -225.55979413   -1.99900E+00    1.95175E+01
SCF Iter117:      -203.23817919    2.23216E+01    2.42497E+01
SCF Iter118:      -178.11180813    2.51264E+01    2.91429E+01
SCF Iter119:      -144.30066605    3.38111E+01    3.51912E+01
SCF Iter120:      -108.81717969    3.54835E+01    4.12207E+01
SCF Iter121:      -112.40127701   -3.58410E+00    4.05347E+01
SCF Iter122:      -117.18871283   -4.78744E+00    3.96014E+01
SCF Iter123:      -121.87302123   -4.68431E+00    3.86388E+01
SCF Iter124:      -126.08728579   -4.21426E+00    3.78192E+01
SCF Iter125:      -130.15650069   -4.06921E+00    3.69879E+01
SCF Iter126:      -134.43247765   -4.27598E+00    3.60926E+01
SCF Iter127:      -126.33293127    8.09955E+00    3.77255E+01
SCF Iter128:      -111.02999848    1.53029E+01    4.04566E+01
SCF Iter129:      -114.99334025   -3.96334E+00    3.96798E+01
SCF Iter130:      -107.37997664    7.61336E+00    4.12112E+01
SCF Iter131:      -110.32773815   -2.94776E+00    4.06476E+01
SCF Iter132:      -115.23368465   -4.90595E+00    3.96393E+01
SCF Iter133:      -119.51068196   -4.27700E+00    3.87492E+01
SCF Iter134:      -123.67711186   -4.16643E+00    3.78775E+01
SCF Iter135:      -104.43965115    1.92375E+01    4.08395E+01
SCF Iter136:       -81.91117796    2.25285E+01    4.40694E+01
SCF Iter137:       -58.91333232    2.29978E+01    4.72236E+01
SCF Iter138:       -34.74171179    2.41716E+01    5.04157E+01
SCF Iter139:       -41.04254650   -6.30083E+00    4.93329E+01
SCF Iter140:       -47.09512611   -6.05258E+00    4.83195E+01
SCF Iter141:       -53.19499847   -6.09987E+00    4.72475E+01
SCF Iter142:       -58.61540226   -5.42040E+00    4.63394E+01
SCF Iter143:       -63.55696498   -4.94156E+00    4.55052E+01
SCF Iter144:       -69.01600011   -5.45904E+00    4.45171E+01
SCF Iter145:       -74.35356154   -5.33756E+00    4.35471E+01
SCF Iter146:       -79.61318216   -5.25962E+00    4.25881E+01
SCF Iter147:       -73.49031375    6.12287E+00    4.37178E+01
SCF Iter148:       -67.42381598    6.06650E+00    4.48323E+01
SCF Iter149:       -64.95417782    2.46964E+00    4.53460E+01
SCF Iter150:       -62.43851837    2.51566E+00    4.58378E+01
SCF Iter151:       -68.34287391   -5.90436E+00    4.47703E+01
SCF Iter152:       -73.89677540   -5.55390E+00    4.37682E+01
SCF Iter153:       -78.16400701   -4.26723E+00    4.30399E+01
SCF Iter154:       -82.92796663   -4.76396E+00    4.21960E+01
SCF Iter155:       -86.12723369   -3.19927E+00    4.16628E+01
SCF Iter156:       -91.23485041   -5.10762E+00    4.07180E+01
SCF Iter157:       -95.65983999   -4.42499E+00    3.99125E+01
SCF Iter158:       -99.61474712   -3.95491E+00    3.92048E+01
SCF Iter159:      -104.10565499   -4.49091E+00    3.83485E+01
SCF Iter160:      -108.35074153   -4.24509E+00    3.75560E+01
SCF Iter161:      -112.00035580   -3.64961E+00    3.69275E+01
SCF Iter162:      -116.27875677   -4.27840E+00    3.61276E+01
SCF Iter163:      -120.80169192   -4.52294E+00    3.52617E+01
SCF Iter164:      -124.16304417   -3.36135E+00    3.46750E+01
SCF Iter165:      -127.74525019   -3.58221E+00    3.40349E+01
SCF Iter166:      -131.34885869   -3.60361E+00    3.33825E+01
SCF Iter167:      -134.77780277   -3.42894E+00    3.27611E+01
SCF Iter168:      -137.43484359   -2.65704E+00    3.23178E+01
SCF Iter169:      -140.90073433   -3.46589E+00    3.17013E+01
SCF Iter170:      -144.91508767   -4.01435E+00    3.08846E+01
SCF Iter171:      -148.07768511   -3.16260E+00    3.02835E+01
SCF Iter172:      -151.18151544   -3.10383E+00    2.96999E+01
SCF Iter173:      -154.43922988   -3.25771E+00    2.90867E+01
SCF Iter174:      -156.20596763   -1.76674E+00    2.88685E+01
SCF Iter175:      -158.54374239   -2.33777E+00    2.84871E+01
SCF Iter176:      -160.90387799   -2.36014E+00    2.80758E+01
SCF Iter177:      -162.60758473   -1.70371E+00    2.78427E+01
SCF Iter178:      -166.09215959   -3.48457E+00    2.70908E+01
SCF Iter179:      -168.65599202   -2.56383E+00    2.65528E+01
SCF Iter180:      -170.59273001   -1.93674E+00    2.61933E+01
SCF Iter181:      -172.65204023   -2.05931E+00    2.58087E+01
SCF Iter182:      -173.54929518   -8.97255E-01    2.56912E+01
SCF Iter183:      -175.46645440   -1.91716E+00    2.53484E+01
SCF Iter184:      -178.28464923   -2.81819E+00    2.47508E+01
SCF Iter185:      -181.07691622   -2.79227E+00    2.41665E+01
SCF Iter186:      -183.77307567   -2.69616E+00    2.36037E+01
SCF Iter187:      -186.28191714   -2.50884E+00    2.30760E+01
SCF Iter188:      -188.92970464   -2.64779E+00    2.24949E+01
SCF Iter189:      -180.91986387    8.00984E+00    2.46163E+01
SCF Iter190:      -181.86082347   -9.40960E-01    2.44271E+01
SCF Iter191:      -181.08291160    7.77912E-01    2.48118E+01
SCF Iter192:      -179.63178082    1.45113E+00    2.53670E+01
SCF Iter193:      -179.48305460    1.48726E-01    2.55882E+01
SCF Iter194:      -177.43044817    2.05261E+00    2.61562E+01
SCF Iter195:      -177.48637688   -5.59287E-02    2.61388E+01
SCF Iter196:      -177.30033245    1.86044E-01    2.61621E+01
SCF Iter197:      -177.35849241   -5.81600E-02    2.61520E+01
SCF Iter198:      -180.43589825   -3.07741E+00    2.54834E+01
SCF Iter199:      -183.22030830   -2.78441E+00    2.48770E+01
SCF Iter200:      -174.13482017    9.08549E+00    2.70439E+01
SCF Iter201:      -158.90310931    1.52317E+01    3.01470E+01
SCF Iter202:      -160.22746126   -1.32435E+00    2.98842E+01
SCF Iter203:      -161.17233171   -9.44870E-01    2.97373E+01
SCF Iter204:      -160.92703090    2.45301E-01    2.99227E+01
SCF Iter205:      -163.35358854   -2.42656E+00    2.94294E+01
SCF Iter206:      -164.95933307   -1.60574E+00    2.90907E+01
SCF Iter207:      -167.21710890   -2.25778E+00    2.85882E+01
SCF Iter208:      -168.51685680   -1.29975E+00    2.83590E+01
SCF Iter209:      -164.63837379    3.87848E+00    2.92633E+01
SCF Iter210:      -163.59483966    1.04353E+00    2.95632E+01
SCF Iter211:      -162.95232816    6.42511E-01    2.97868E+01
SCF Iter212:      -166.14512747   -3.19280E+00    2.91445E+01
SCF Iter213:      -169.78539949   -3.64027E+00    2.83702E+01
SCF Iter214:      -173.14293339   -3.35753E+00    2.76622E+01
SCF Iter215:      -175.27614340   -2.13321E+00    2.72328E+01
SCF Iter216:      -178.74920554   -3.47306E+00    2.64784E+01
SCF Iter217:      -175.16212329    3.58708E+00    2.74073E+01
SCF Iter218:      -172.75776580    2.40436E+00    2.80442E+01
SCF Iter219:      -176.12468625   -3.36692E+00    2.73175E+01
SCF Iter220:      -177.38438398   -1.25970E+00    2.71206E+01
SCF Iter221:      -178.94212635   -1.55774E+00    2.68291E+01
SCF Iter222:      -180.01703538   -1.07491E+00    2.66444E+01
SCF Iter223:      -181.04152379   -1.02449E+00    2.64446E+01
SCF Iter224:      -184.02495089   -2.98343E+00    2.57871E+01
SCF Iter225:      -176.53782180    7.48713E+00    2.75020E+01
SCF Iter226:      -167.68338657    8.85444E+00    2.94428E+01
SCF Iter227:      -170.72811758   -3.04473E+00    2.88041E+01
SCF Iter228:      -151.78984099    1.89383E+01    3.22567E+01
SCF Iter229:      -132.86713041    1.89227E+01    3.56561E+01
SCF Iter230:      -134.81141436   -1.94428E+00    3.53546E+01
SCF Iter231:      -136.97686746   -2.16545E+00    3.49984E+01
SCF Iter232:      -139.50433128   -2.52746E+00    3.45786E+01
SCF Iter233:      -143.98151998   -4.47719E+00    3.36771E+01
SCF Iter234:      -146.54078044   -2.55926E+00    3.32198E+01
SCF Iter235:      -150.44016717   -3.89939E+00    3.24363E+01
SCF Iter236:      -154.36959038   -3.92942E+00    3.16268E+01
SCF Iter237:      -158.18879778   -3.81921E+00    3.08238E+01
SCF Iter238:      -161.85603951   -3.66724E+00    3.00512E+01
SCF Iter239:      -165.28930952   -3.43327E+00    2.93133E+01
SCF Iter240:      -168.71956116   -3.43025E+00    2.85583E+01
SCF Iter241:      -168.85338632   -1.33825E-01    2.86034E+01
SCF Iter242:      -170.49131457   -1.63793E+00    2.83187E+01
SCF Iter243:      -172.64971694   -2.15840E+00    2.78883E+01
SCF Iter244:      -174.86129500   -2.21158E+00    2.74448E+01
SCF Iter245:      -177.07898568   -2.21769E+00    2.70170E+01
SCF Iter246:      -180.41753697   -3.33855E+00    2.62926E+01
SCF Iter247:      -183.37396192   -2.95642E+00    2.56681E+01
SCF Iter248:      -186.05261299   -2.67865E+00    2.51089E+01
SCF Iter249:      -188.71250442   -2.65989E+00    2.45513E+01
SCF Iter250:      -191.06945389   -2.35695E+00    2.40312E+01
SCF Iter251:      -193.60895483   -2.53950E+00    2.34829E+01
SCF Iter252:      -196.53516788   -2.92621E+00    2.28122E+01
SCF Iter253:      -199.01015183   -2.47498E+00    2.22571E+01
SCF Iter254:      -200.20888468   -1.19873E+00    2.20053E+01
SCF Iter255:      -201.99038667   -1.78150E+00    2.16419E+01
SCF Iter256:      -202.82472833   -8.34342E-01    2.15829E+01
SCF Iter257:      -205.02457536   -2.19985E+00    2.11034E+01
SCF Iter258:      -206.94664530   -1.92207E+00    2.06890E+01
SCF Iter259:      -196.98823939    9.95841E+00    2.28654E+01
SCF Iter260:      -192.62488798    4.36335E+00    2.39673E+01
SCF Iter261:      -194.28807696   -1.66319E+00    2.36946E+01
SCF Iter262:      -179.55069359    1.47374E+01    2.66112E+01
SCF Iter263:      -167.71994287    1.18308E+01    2.90096E+01
SCF Iter264:      -169.85177185   -2.13183E+00    2.86704E+01
SCF Iter265:      -173.53226572   -3.68049E+00    2.78792E+01
SCF Iter266:      -176.09655172   -2.56429E+00    2.74027E+01
SCF Iter267:      -178.23866436   -2.14211E+00    2.70492E+01
SCF Iter268:      -180.24646582   -2.00780E+00    2.67133E+01
SCF Iter269:      -183.18350076   -2.93703E+00    2.60873E+01
SCF Iter270:      -186.11461439   -2.93111E+00    2.54693E+01
SCF Iter271:      -188.24221906   -2.12760E+00    2.50486E+01
SCF Iter272:      -191.08366293   -2.84144E+00    2.44107E+01
SCF Iter273:      -191.51405999   -4.30397E-01    2.44369E+01
SCF Iter274:      -193.00207652   -1.48802E+00    2.42228E+01
SCF Iter275:      -194.75682159   -1.75475E+00    2.39252E+01
SCF Iter276:      -196.88675223   -2.12993E+00    2.34988E+01
SCF Iter277:      -199.59087192   -2.70412E+00    2.28843E+01
SCF Iter278:      -200.66535039   -1.07448E+00    2.26412E+01
SCF Iter279:      -201.83549948   -1.17015E+00    2.23703E+01
SCF Iter280:      -202.35095198   -5.15453E-01    2.22941E+01
SCF Iter281:      -204.26635497   -1.91540E+00    2.18693E+01
SCF Iter282:      -206.38072284   -2.11437E+00    2.13515E+01
SCF Iter283:      -207.94552710   -1.56480E+00    2.09244E+01
SCF Iter284:      -209.73596966   -1.79044E+00    2.04551E+01
SCF Iter285:      -212.29210900   -2.55614E+00    1.98245E+01
SCF Iter286:      -214.23126282   -1.93915E+00    1.93174E+01
SCF Iter287:      -216.17985274   -1.94859E+00    1.88172E+01
SCF Iter288:      -217.85428475   -1.67443E+00    1.83714E+01
SCF Iter289:      -219.83141636   -1.97713E+00    1.78069E+01
SCF Iter290:      -221.73218581   -1.90077E+00    1.72353E+01
SCF Iter291:      -223.65037411   -1.91819E+00    1.66803E+01
SCF Iter292:      -225.21124121   -1.56087E+00    1.63169E+01
SCF Iter293:      -226.66389887   -1.45266E+00    1.59660E+01
SCF Iter294:      -227.96222737   -1.29833E+00    1.56393E+01
SCF Iter295:      -229.24462635   -1.28240E+00    1.53100E+01
SCF Iter296:      -230.52175636   -1.27713E+00    1.49671E+01
SCF Iter297:      -231.43465250   -9.12896E-01    1.47259E+01
SCF Iter298:      -233.06797954   -1.63333E+00    1.43321E+01
SCF Iter299:      -234.57287951   -1.50490E+00    1.39342E+01
SCF Iter300:      -233.09913336    1.47375E+00    1.46796E+01
SCF Iter301:      -231.06702880    2.03210E+00    1.55645E+01
SCF Iter302:      -231.06383579    3.19301E-03    1.57625E+01
SCF Iter303:      -231.03765119    2.61846E-02    1.60020E+01
SCF Iter304:      -228.44013917    2.59751E+00    1.69804E+01
SCF Iter305:      -224.53861746    3.90152E+00    1.81922E+01
SCF Iter306:      -225.03642325   -4.97806E-01    1.82173E+01
SCF Iter307:      -226.44345050   -1.40703E+00    1.79097E+01
SCF Iter308:      -228.54714989   -2.10370E+00    1.73277E+01
SCF Iter309:      -229.25984075   -7.12691E-01    1.71968E+01
SCF Iter310:      -230.06063681   -8.00796E-01    1.70251E+01
SCF Iter311:      -231.33912319   -1.27849E+00    1.66544E+01
SCF Iter312:      -232.57117331   -1.23205E+00    1.63180E+01
SCF Iter313:      -233.91920636   -1.34803E+00    1.59646E+01
SCF Iter314:      -235.38123408   -1.46203E+00    1.55906E+01
SCF Iter315:      -237.03629504   -1.65506E+00    1.50612E+01
SCF Iter316:      -237.70324064   -6.66946E-01    1.49758E+01
SCF Iter317:      -238.92910959   -1.22587E+00    1.46551E+01
SCF Iter318:      -239.65239669   -7.23287E-01    1.44351E+01
SCF Iter319:      -240.38067369   -7.28277E-01    1.42147E+01
SCF Iter320:      -240.97979619   -5.99122E-01    1.40166E+01

In [40]:
df.to_csv(csv_file, index=False)
df

,Method,Atom,Basis,Grid_Sph,Grid_Rad,"Energy,Ha",Iterations,DIIS,Damp_Start,Damp_End,Damp_Cutoff
0,TFW LDA,Na,UGBS_S,6,1000,-108.912083,284,True,0.90,0.9,0.00009
1,TFW LDA,Mg,UGBS_S,6,1000,-135.553609,237,True,0.90,0.9,0.00009
2,TFW LDA,Al,UGBS_S,6,1000,-165.669941,387,True,0.90,0.9,0.00009
3,TFW LDA,Si,UGBS_S,6,1000,-199.392286,517,True,0.90,0.9,0.00009
4,TFW LDA,P,UGBS_S,6,1000,-236.833553,342,True,0.90,0.9,0.00009
...,...,...,...,...,...,...,...,...,...,...,...
131,TF0.111111W FA,S,UGBS_S,6,1000,-413.577377,8321,True,0.99,0.9,0.00009
132,TF0.111111W FA,Ca,UGBS_S,6,1000,-702.938291,5212,True,0.99,0.9,0.00009
133,TF0.111111W FA,Zn,UGBS_S,6,1000,-1842.940240,6431,True,0.99,0.9,0.00009
134,TF0.111111W FA,Kr,UGBS_S,6,1000,-2842.167575,7460,True,0.99,0.9,0.00009
135,TF0.111111W FA,Si,UGBS_S,6,1000,-301.135691,5498,True,0.99,0.9,0.00002

In [ ]:
## TF0.111111W PBE for O and F used TF0.111111W FA densities of O and F as initial guesses
## TF0.111111W FA for Si, Kr used TF0.166666W FA initial guess

In [22]:
ATOMS = {
    'He':  {'mult': 1}, 
    'Be': {'mult': 1},
    'Ne': {'mult': 1}, 
    'Mg': {'mult': 1},
    'Ar':  {'mult': 1}, 
    'Ca':  {'mult': 1},
    'Zn':  {'mult': 1}, 
    'Kr':  {'mult': 1}
}
psi4.core.set_output_file('output.dat', False)
psi4.set_options({'basis': 'UGBS',
                  'scf_type': 'PK'})
rhf_energies = {}
rhf_homos = {}
for atom in ATOMS:
    MOL = psi4.geometry(f"0 {ATOMS[atom]['mult']}\n {atom}\nsymmetry c1")
    E, wfn = psi4.energy('SCF', return_wfn=True)
    homo = wfn.epsilon_a().np[wfn.nalpha()-1]
    rhf_energies[atom] = round(E, 6)
    rhf_homos[atom] = round(homo, 6)
    print(f"RHF/UGBS {atom} Energy: {E:.4f} Hartree, IP: {homo:.4f}")

RHF/UGBS He Energy: -2.8617 Hartree, IP: -0.9180
RHF/UGBS Be Energy: -14.5730 Hartree, IP: -0.3093
RHF/UGBS Ne Energy: -128.5471 Hartree, IP: -0.8504
RHF/UGBS Mg Energy: -199.6146 Hartree, IP: -0.2530
RHF/UGBS Ar Energy: -526.8175 Hartree, IP: -0.5910
RHF/UGBS Ca Energy: -676.7582 Hartree, IP: -0.1955
RHF/UGBS Zn Energy: -1777.8481 Hartree, IP: -0.2925
RHF/UGBS Kr Energy: -2752.0549 Hartree, IP: -0.5242

In [26]:
atom_order = ['He', 'Be', 'Ne', 'Mg', 'Ar', 'Ca', 'Zn', 'Kr']
energy_table = df.pivot(index='Atom', columns='Method', values='Energy,Ha')
energy_table = energy_table.reindex(atom_order)
energy_table['RHF/UGBS'] = pd.Series(rhf_energies)
new_order = ['TFD0.166666W', 'TF0.166666W PBEx', 'TF0.166666W FA', 'RHF/UGBS']
energy_table = energy_table[new_order]

In [28]:
reference = energy_table['RHF/UGBS']

res = {}
for method, energies in energy_table.items():
    if method == 'RHF/UGBS': 
        continue 
    
    mae  = (energies - reference).abs().mean()
    rmae = (((energies - reference).abs()) / reference * -100).mean()
    res[method] = round(mae, 2), round(rmae, 2)

mae_row  = {method: values[0] for method, values in res.items()}
rmae_row = {method: values[1] for method, values in res.items()}
stats_df = pd.DataFrame([mae_row, rmae_row], index=['MAE(Ha)', 'rMAE(%)'])
energy_table = pd.concat([energy_table, stats_df], sort=False)

In [29]:
display(energy_table)

         TFD0.166666W  TF0.166666W PBEx  TF0.166666W FA     RHF/UGBS
He          -2.951247         -3.097069       -3.019526    -2.861680
Be         -15.040391        -15.388877      -14.660508   -14.573023
Ne        -132.508856       -133.573716     -128.291707  -128.547083
Mg        -204.540690       -205.864549     -198.305386  -199.614621
Ar        -537.208760       -539.346529     -522.928926  -526.817486
Ca        -690.396266       -692.814969     -672.808485  -676.758154
Zn       -1812.192490      -1816.067937    -1773.727670 -1777.848060
Kr       -2795.914635      -2800.696590    -2741.665221 -2752.054860
MAE(Ha)     13.960000         15.970000        3.020000          NaN
rMAE(%)      2.420000          3.690000        1.110000          NaN

In [33]:
atom_order = ['He', 'Be', 'Ne', 'Mg', 'Ar', 'Ca', 'Zn', 'Kr']
mu_table = df.pivot(index='Atom', columns='Method', values='ChemPot,Ha')
mu_table = mu_table.reindex(atom_order)
mu_table['RHF/UGBS'] = pd.Series(rhf_homos)
new_order = ['TFD0.166666W', 'TF0.166666W PBEx', 'TF0.166666W FA', 'RHF/UGBS']
mu_table = mu_table[new_order]

In [35]:
reference = mu_table['RHF/UGBS']

res = {}
for method, energies in mu_table.items():
    if method == 'RHF/UGBS': 
        continue 
    
    mae  = (energies - reference).abs().mean()
    rmae = (((energies - reference).abs()) / reference * -100).mean()
    res[method] = round(mae, 2), round(rmae, 2)

mae_row  = {method: values[0] for method, values in res.items()}
rmae_row = {method: values[1] for method, values in res.items()}
stats_df = pd.DataFrame([mae_row, rmae_row], index=['MAE(Ha)', 'rMAE(%)'])
mu_table = pd.concat([mu_table, stats_df], sort=False)

In [36]:
display(mu_table)

         TFD0.166666W  TF0.166666W PBEx  TF0.166666W FA  RHF/UGBS
He          -0.067106         -0.081193       -0.313483 -0.917956
Be          -0.069849         -0.081756       -0.272375 -0.309271
Ne          -0.072529         -0.082214       -0.231390 -0.850411
Mg          -0.072963         -0.082281       -0.224844 -0.253048
Ar          -0.073833         -0.082424       -0.211897 -0.590989
Ca          -0.074040         -0.082458       -0.208863 -0.195527
Zn          -0.074767         -0.082581       -0.198303 -0.292463
Kr          -0.075063         -0.082633       -0.194080 -0.524161
MAE(Ha)      0.420000          0.410000        0.260000       NaN
rMAE(%)     80.310000         77.800000       40.980000       NaN