In [1]:
import psi4
import pandas as pd
import os
import numpy as np
from lps_uscf import lps_solver

In [2]:
csv_file = 'open_shell_15atoms_vs_uhf.csv'

if os.path.exists(csv_file):
    df = pd.read_csv(csv_file)
    print(f"-> Loaded existing results: {len(df)} rows found.")
else:
    df = pd.DataFrame()
    print("-> No existing file found. Starting fresh.")

-> Loaded existing results: 139 rows found.

In [69]:
TP = ['LDA_K_TF', 1.0]
LAMBDA = 0.166666
EXC = ['GGA_X_PBE', 0.0, 'LDA_C_VWN', 0.0]
FA = [True, 1.0]
DIIS = True
MAX_ITER = 10000
DAMPING = [0.99, 0.9, 0.00009]
# D_guess = [GUESS_A, GUESS_B]
D_guess = None
verbose=True

psi4.set_options({'basis': 'UGBS_S', 
                  'DFT_SPHERICAL_POINTS': 6, 
                  'DFT_RADIAL_POINTS': 1000})

mol = psi4.geometry("""
units bohr
0 2
K
symmetry c1
""")

E, Da, Db, iterations = lps_solver(MAX_ITER,TP,EXC,LAMBDA,mol,DAMPING,FA,D_guess,DIIS,verbose)
print('\nFinal SCF energy: %.4f Hartree' % E)

Number of basis functions:   31

Starting SCF iterations:

    Iter            Energy            Delta E         dRMS

SCF Iter  1:      9885.51092381    9.88551E+03    7.52108E+02
SCF Iter  2:      9673.03853755   -2.12472E+02    7.38308E+02
SCF Iter  3:      9464.64085499   -2.08398E+02    7.24755E+02
SCF Iter  4:     10582.08796164    1.11745E+03    8.49682E+02
SCF Iter  5:     11697.55195311    1.11546E+03    9.03339E+02
SCF Iter  6:     12943.89266588    1.24634E+03    9.49197E+02
SCF Iter  7:     14340.13937367    1.39625E+03    9.97784E+02
SCF Iter  8:     14078.29658164   -2.61843E+02    9.82051E+02
SCF Iter  9:     13820.33541420   -2.57961E+02    9.66862E+02
SCF Iter 10:     13565.32940828   -2.55006E+02    9.51817E+02
SCF Iter 11:     13314.79762513   -2.50532E+02    9.37348E+02
SCF Iter 12:     13061.79249431   -2.53005E+02    9.23137E+02
SCF Iter 13:     12813.37338043   -2.48419E+02    9.09525E+02
SCF Iter 14:     12572.43989643   -2.40933E+02    8.95461E+02
SCF Iter 15:     12348.84454846   -2.23595E+02    8.81404E+02
SCF Iter 16:     12125.27307129   -2.23571E+02    8.67601E+02
SCF Iter 17:     11897.25581249   -2.28017E+02    8.54019E+02
SCF Iter 18:     11674.47989031   -2.22776E+02    8.40676E+02
SCF Iter 19:     11459.87720968   -2.14603E+02    8.27546E+02
SCF Iter 20:     11252.76430403   -2.07113E+02    8.14624E+02
SCF Iter 21:     11046.27300163   -2.06491E+02    8.01937E+02
SCF Iter 22:     10849.84476186   -1.96428E+02    7.89458E+02
SCF Iter 23:     10652.69878895   -1.97146E+02    7.77206E+02
SCF Iter 24:     10467.80775527   -1.84891E+02    7.65182E+02
SCF Iter 25:     10279.20467391   -1.88603E+02    7.53353E+02
SCF Iter 26:     10094.50066174   -1.84704E+02    7.41721E+02
SCF Iter 27:      9901.94265200   -1.92558E+02    7.30317E+02
SCF Iter 28:      9712.81991388   -1.89123E+02    7.19107E+02
SCF Iter 29:      9530.93103932   -1.81889E+02    7.08094E+02
SCF Iter 30:      9350.51018832   -1.80421E+02    6.97268E+02
SCF Iter 31:      9172.44426124   -1.78066E+02    6.86629E+02
SCF Iter 32:      8997.75947063   -1.74685E+02    6.76175E+02
SCF Iter 33:      8826.95690725   -1.70803E+02    6.65904E+02
SCF Iter 34:      8659.53450655   -1.67422E+02    6.55809E+02
SCF Iter 35:      8497.96308293   -1.61571E+02    6.45901E+02
SCF Iter 36:      8341.09144309   -1.56872E+02    6.36144E+02
SCF Iter 37:      8191.17660379   -1.49915E+02    6.26550E+02
SCF Iter 38:      8033.13285254   -1.58044E+02    6.17128E+02
SCF Iter 39:      7879.71482320   -1.53418E+02    6.07840E+02
SCF Iter 40:      7752.34359964   -1.27371E+02    5.98677E+02
SCF Iter 41:      7602.77200320   -1.49572E+02    5.89731E+02
SCF Iter 42:      7455.35485399   -1.47417E+02    5.80937E+02
SCF Iter 43:      7310.42496907   -1.44930E+02    5.72293E+02
SCF Iter 44:      7167.41087278   -1.43014E+02    5.63796E+02
SCF Iter 45:      7030.78963661   -1.36621E+02    5.55416E+02
SCF Iter 46:      6895.71286456   -1.35077E+02    5.47177E+02
SCF Iter 47:      6760.68557678   -1.35027E+02    5.39106E+02
SCF Iter 48:      6628.66726343   -1.32018E+02    5.31171E+02
SCF Iter 49:      6499.02582791   -1.29641E+02    5.23373E+02
SCF Iter 50:      6371.29512576   -1.27731E+02    5.15706E+02
SCF Iter 51:      6327.77055711   -4.35246E+01    5.10092E+02
SCF Iter 52:      6269.23453626   -5.85360E+01    5.04333E+02
SCF Iter 53:      6148.45637285   -1.20778E+02    4.96902E+02
SCF Iter 54:      6094.59234317   -5.38640E+01    4.91462E+02
SCF Iter 55:      5978.09445642   -1.16498E+02    4.84170E+02
SCF Iter 56:      5863.38205940   -1.14712E+02    4.77007E+02
SCF Iter 57:      5753.08721519   -1.10295E+02    4.69995E+02
SCF Iter 58:      5650.84536382   -1.02242E+02    4.63078E+02
SCF Iter 59:      5548.93822068   -1.01907E+02    4.56279E+02
SCF Iter 60:      5450.32064004   -9.86176E+01    4.49584E+02
SCF Iter 61:      5348.64669403   -1.01674E+02    4.43031E+02
SCF Iter 62:      5245.17934332   -1.03467E+02    4.36599E+02
SCF Iter 63:      5144.03765030   -1.01142E+02    4.30274E+02
SCF Iter 64:      5045.74737608   -9.82903E+01    4.24054E+02
SCF Iter 65:      4953.33243342   -9.24149E+01    4.17912E+02
SCF Iter 66:      4862.80054779   -9.05319E+01    4.11876E+02
SCF Iter 67:      4765.86956800   -9.69310E+01    4.05971E+02
SCF Iter 68:      4674.77780354   -9.10918E+01    4.00161E+02
SCF Iter 69:      4585.26178555   -8.95160E+01    3.94436E+02
SCF Iter 70:      4500.36081693   -8.49010E+01    3.88798E+02
SCF Iter 71:      4412.63228841   -8.77285E+01    3.83280E+02
SCF Iter 72:      4329.31448966   -8.33178E+01    3.77855E+02
SCF Iter 73:      4259.77085241   -6.95436E+01    3.72617E+02
SCF Iter 74:      4194.96789892   -6.48030E+01    3.67380E+02
SCF Iter 75:      4116.35691774   -7.86110E+01    3.62215E+02
SCF Iter 76:      4038.14709024   -7.82098E+01    3.57132E+02
SCF Iter 77:      3959.65561181   -7.84915E+01    3.52138E+02
SCF Iter 78:      3881.01918851   -7.86364E+01    3.47227E+02
SCF Iter 79:      3819.14140242   -6.18778E+01    3.42405E+02
SCF Iter 80:      3757.35780773   -6.17836E+01    3.37665E+02
SCF Iter 81:      3694.58486928   -6.27729E+01    3.32998E+02
SCF Iter 82:      3635.03515014   -5.95497E+01    3.28399E+02
SCF Iter 83:      3577.15234238   -5.78828E+01    3.23878E+02
SCF Iter 84:      3508.94888382   -6.82035E+01    3.19442E+02
SCF Iter 85:      3440.88568381   -6.80632E+01    3.15073E+02
SCF Iter 86:      3426.22513138   -1.46606E+01    3.14815E+02
SCF Iter 87:      3401.77558158   -2.44495E+01    3.14022E+02
SCF Iter 88:      3375.49032908   -2.62853E+01    3.12776E+02
SCF Iter 89:      3305.17470848   -7.03156E+01    3.08477E+02
SCF Iter 90:      3236.09622716   -6.90785E+01    3.04251E+02
SCF Iter 91:      3232.03972337   -4.05650E+00    3.00902E+02
SCF Iter 92:      3166.78403699   -6.52557E+01    2.96799E+02
SCF Iter 93:      3100.75008835   -6.60339E+01    2.92730E+02
SCF Iter 94:      3095.63559366   -5.11449E+00    2.93242E+02
SCF Iter 95:      3105.22601142    9.59042E+00    2.94664E+02
SCF Iter 96:      3121.56729750    1.63413E+01    2.96532E+02
SCF Iter 97:      3142.75652878    2.11892E+01    2.98777E+02
SCF Iter 98:      3080.28239489   -6.24741E+01    2.94624E+02
SCF Iter 99:      3019.84799991   -6.04344E+01    2.90530E+02
SCF Iter100:      2959.71976329   -6.01282E+01    2.86512E+02
SCF Iter101:      2901.29287175   -5.84269E+01    2.82553E+02
SCF Iter102:      2838.92632891   -6.23665E+01    2.78668E+02
SCF Iter103:      2781.36066965   -5.75657E+01    2.74834E+02
SCF Iter104:      2723.96214746   -5.73985E+01    2.71070E+02
SCF Iter105:      2668.50784135   -5.54543E+01    2.67371E+02
SCF Iter106:      2614.54642608   -5.39614E+01    2.63732E+02
SCF Iter107:      2561.01248839   -5.35339E+01    2.60152E+02
SCF Iter108:      2508.66630761   -5.23462E+01    2.56621E+02
SCF Iter109:      2469.96156781   -3.87047E+01    2.53250E+02
SCF Iter110:      2419.85985459   -5.01017E+01    2.49826E+02
SCF Iter111:      2369.00915093   -5.08507E+01    2.46463E+02
SCF Iter112:      2329.68782806   -3.93213E+01    2.43179E+02
SCF Iter113:      2289.72841486   -3.99594E+01    2.39951E+02
SCF Iter114:      2241.21587142   -4.85125E+01    2.36737E+02
SCF Iter115:      2193.11453312   -4.81013E+01    2.33576E+02
SCF Iter116:      2146.43866961   -4.66759E+01    2.30474E+02
SCF Iter117:      2100.65319566   -4.57855E+01    2.27496E+02
SCF Iter118:      2059.06191699   -4.15913E+01    2.24470E+02
SCF Iter119:      2017.84292656   -4.12190E+01    2.21499E+02
SCF Iter120:      1978.93582451   -3.89071E+01    2.18567E+02
SCF Iter121:      1934.37599059   -4.45598E+01    2.15689E+02
SCF Iter122:      1891.43573912   -4.29403E+01    2.12861E+02
SCF Iter123:      1849.75351042   -4.16822E+01    2.10078E+02
SCF Iter124:      1808.30751015   -4.14460E+01    2.07337E+02
SCF Iter125:      1767.62095041   -4.06866E+01    2.04641E+02
SCF Iter126:      1789.45867112    2.18377E+01    2.00950E+02
SCF Iter127:      1753.22729249   -3.62314E+01    1.98376E+02
SCF Iter128:      1715.53060864   -3.76967E+01    1.95799E+02
SCF Iter129:      1676.84046101   -3.86901E+01    1.93237E+02
SCF Iter130:      1638.33943307   -3.85010E+01    1.90712E+02
SCF Iter131:      1604.47724491   -3.38622E+01    1.88415E+02
SCF Iter132:      1585.03575630   -1.94415E+01    1.87096E+02
SCF Iter133:      1565.59255044   -1.94432E+01    1.85718E+02
SCF Iter134:      1529.45942095   -3.61331E+01    1.83304E+02
SCF Iter135:      1494.46984444   -3.49896E+01    1.80929E+02
SCF Iter136:      1459.15467599   -3.53152E+01    1.78590E+02
SCF Iter137:      1483.87999950    2.47253E+01    1.81045E+02
SCF Iter138:      1508.50749672    2.46275E+01    1.83536E+02
SCF Iter139:      1516.23439802    7.72690E+00    1.84720E+02
SCF Iter140:      1480.06069421   -3.61737E+01    1.82291E+02
SCF Iter141:      1444.31974061   -3.57410E+01    1.79900E+02
SCF Iter142:      1409.10199476   -3.52177E+01    1.77530E+02
SCF Iter143:      1376.93101027   -3.21710E+01    1.75261E+02
SCF Iter144:      1345.93419978   -3.09968E+01    1.73049E+02
SCF Iter145:      1348.01840594    2.08421E+00    1.70271E+02
SCF Iter146:      1315.44451411   -3.25739E+01    1.68032E+02
SCF Iter147:      1282.69091406   -3.27536E+01    1.65828E+02
SCF Iter148:      1250.67708738   -3.20138E+01    1.63660E+02
SCF Iter149:      1220.03825504   -3.06388E+01    1.61537E+02
SCF Iter150:      1188.77778679   -3.12605E+01    1.59437E+02
SCF Iter151:      1209.83667648    2.10589E+01    1.56142E+02
SCF Iter152:      1182.41341470   -2.74233E+01    1.54127E+02
SCF Iter153:      1156.24050300   -2.61729E+01    1.52156E+02
SCF Iter154:      1127.67239062   -2.85681E+01    1.50176E+02
SCF Iter155:      1099.14624792   -2.85261E+01    1.48224E+02
SCF Iter156:      1070.01420361   -2.91320E+01    1.46290E+02
SCF Iter157:      1073.72431066    3.71011E+00    1.47079E+02
SCF Iter158:      1073.52422065   -2.00090E-01    1.45869E+02
SCF Iter159:      1057.71867308   -1.58055E+01    1.44870E+02
SCF Iter160:      1034.82748112   -2.28912E+01    1.43322E+02
SCF Iter161:      1006.51150840   -2.83160E+01    1.41427E+02
SCF Iter162:       979.56565618   -2.69459E+01    1.39564E+02
SCF Iter163:       952.48577019   -2.70799E+01    1.37732E+02
SCF Iter164:       937.14323067   -1.53425E+01    1.35891E+02
SCF Iter165:       918.29951786   -1.88437E+01    1.34105E+02
SCF Iter166:       895.88952421   -2.24100E+01    1.32368E+02
SCF Iter167:       890.32619640   -5.56333E+00    1.32196E+02
SCF Iter168:       886.81904776   -3.50715E+00    1.32054E+02
SCF Iter169:       879.12476865   -7.69428E+00    1.31812E+02
SCF Iter170:       875.94267532   -3.18209E+00    1.31970E+02
SCF Iter171:       850.86432616   -2.50783E+01    1.30211E+02
SCF Iter172:       827.67693449   -2.31874E+01    1.28487E+02
SCF Iter173:       814.30561721   -1.33713E+01    1.26736E+02
SCF Iter174:       790.89948962   -2.34061E+01    1.25057E+02
SCF Iter175:       812.80346124    2.19040E+01    1.27437E+02
SCF Iter176:       835.41182505    2.26084E+01    1.29831E+02
SCF Iter177:       817.89964774   -1.75122E+01    1.28088E+02
SCF Iter178:       797.68985764   -2.02098E+01    1.26403E+02
SCF Iter179:       780.39361822   -1.72962E+01    1.24725E+02
SCF Iter180:       756.13845336   -2.42552E+01    1.23041E+02
SCF Iter181:       741.90084746   -1.42376E+01    1.21475E+02
SCF Iter182:       723.39561338   -1.85052E+01    1.19914E+02
SCF Iter183:       702.22233875   -2.11733E+01    1.18324E+02
SCF Iter184:       681.45888251   -2.07635E+01    1.16752E+02
SCF Iter185:       659.88499029   -2.15739E+01    1.15201E+02
SCF Iter186:       644.44887799   -1.54361E+01    1.14188E+02
SCF Iter187:       633.37900275   -1.10699E+01    1.13488E+02
SCF Iter188:       614.59080927   -1.87882E+01    1.11973E+02
SCF Iter189:       603.77759778   -1.08132E+01    1.10390E+02
SCF Iter190:       583.52648711   -2.02511E+01    1.08917E+02
SCF Iter191:       576.18539315   -7.34109E+00    1.07360E+02
SCF Iter192:       556.04913822   -2.01363E+01    1.05928E+02
SCF Iter193:       537.50435798   -1.85448E+01    1.04538E+02
SCF Iter194:       519.09656602   -1.84078E+01    1.03170E+02
SCF Iter195:       523.65713966    4.56057E+00    1.04180E+02
SCF Iter196:       531.24456624    7.58743E+00    1.05212E+02
SCF Iter197:       534.97464527    3.73008E+00    1.05669E+02
SCF Iter198:       522.18774717   -1.27869E+01    1.04211E+02
SCF Iter199:       509.13025970   -1.30575E+01    1.02777E+02
SCF Iter200:       490.79591825   -1.83343E+01    1.01471E+02
SCF Iter201:       482.96801495   -7.82790E+00    1.00194E+02
SCF Iter202:       482.30895926   -6.59056E-01    1.00411E+02
SCF Iter203:       481.50353150   -8.05428E-01    1.00626E+02
SCF Iter204:       471.26824231   -1.02353E+01    9.98091E+01
SCF Iter205:       469.91071416   -1.35753E+00    9.95882E+01
SCF Iter206:       450.83397856   -1.90767E+01    9.81935E+01
SCF Iter207:       435.08859755   -1.57454E+01    9.68610E+01
SCF Iter208:       420.32895786   -1.47596E+01    9.55142E+01
SCF Iter209:       406.35916633   -1.39698E+01    9.41875E+01
SCF Iter210:       397.78541599   -8.57375E+00    9.28259E+01
SCF Iter211:       383.14884563   -1.46366E+01    9.15692E+01
SCF Iter212:       366.56055960   -1.65883E+01    9.02998E+01
SCF Iter213:       352.25130009   -1.43093E+01    8.90831E+01
SCF Iter214:       337.84121298   -1.44101E+01    8.78881E+01
SCF Iter215:       323.83179797   -1.40094E+01    8.67137E+01
SCF Iter216:       346.66764220    2.28358E+01    8.92009E+01
SCF Iter217:       369.68912819    2.30215E+01    9.15526E+01
SCF Iter218:       375.60356850    5.91444E+00    9.27423E+01
SCF Iter219:       378.32433281    2.72076E+00    9.36311E+01
SCF Iter220:       360.98995253   -1.73344E+01    9.23144E+01
SCF Iter221:       349.28979859   -1.17002E+01    9.09790E+01
SCF Iter222:       339.86268629   -9.42711E+00    8.97216E+01
SCF Iter223:       332.58784777   -7.27484E+00    8.84108E+01
SCF Iter224:       317.36168482   -1.52262E+01    8.71637E+01
SCF Iter225:       335.35946693    1.79978E+01    8.90607E+01
SCF Iter226:       345.75315728    1.03937E+01    8.95542E+01
SCF Iter227:       343.35764009   -2.39552E+00    8.83472E+01
SCF Iter228:       339.85282877   -3.50481E+00    8.72437E+01
SCF Iter229:       337.84820826   -2.00462E+00    8.60661E+01
SCF Iter230:       321.39477525   -1.64534E+01    8.47819E+01
SCF Iter231:       323.23593736    1.84116E+00    8.51116E+01
SCF Iter232:       320.80657059   -2.42937E+00    8.52028E+01
SCF Iter233:       303.86508714   -1.69415E+01    8.38726E+01
SCF Iter234:       287.41872939   -1.64464E+01    8.25693E+01
SCF Iter235:       289.27956702    1.86084E+00    8.13303E+01
SCF Iter236:       272.85849397   -1.64211E+01    8.00480E+01
SCF Iter237:       257.62427645   -1.52342E+01    7.88760E+01
SCF Iter238:       242.10665513   -1.55176E+01    7.76431E+01
SCF Iter239:       227.53805973   -1.45686E+01    7.64352E+01
SCF Iter240:       267.17971460    3.96417E+01    7.42983E+01
SCF Iter241:       311.38154558    4.42018E+01    7.50780E+01
SCF Iter242:       360.64046764    4.92589E+01    7.87805E+01
SCF Iter243:       412.77801321    5.21375E+01    8.47783E+01
SCF Iter244:       396.42436612   -1.63536E+01    8.33226E+01
SCF Iter245:       377.60489199   -1.88195E+01    8.16352E+01
SCF Iter246:       359.36221720   -1.82427E+01    8.00189E+01
SCF Iter247:       348.35166817   -1.10105E+01    7.89596E+01
SCF Iter248:       351.64321371    3.29155E+00    7.95621E+01
SCF Iter249:       350.09602882   -1.54718E+00    7.96182E+01
SCF Iter250:       334.34719182   -1.57488E+01    7.81887E+01
SCF Iter251:       317.80596474   -1.65412E+01    7.67355E+01
SCF Iter252:       301.42321851   -1.63827E+01    7.52716E+01
SCF Iter253:       288.44885334   -1.29744E+01    7.40802E+01
SCF Iter254:       280.51937772   -7.92948E+00    7.33790E+01
SCF Iter255:       264.80342344   -1.57160E+01    7.19505E+01
SCF Iter256:       248.36684240   -1.64366E+01    7.04874E+01
SCF Iter257:       233.33519695   -1.50316E+01    6.91415E+01
SCF Iter258:       218.91331665   -1.44219E+01    6.78151E+01
SCF Iter259:       204.66859035   -1.42447E+01    6.65003E+01
SCF Iter260:       192.42714229   -1.22414E+01    6.53551E+01
SCF Iter261:       177.66330087   -1.47638E+01    6.40336E+01
SCF Iter262:       204.30814101    2.66448E+01    6.79364E+01
SCF Iter263:       196.42672392   -7.88142E+00    6.77047E+01
SCF Iter264:       186.24594913   -1.01808E+01    6.70089E+01
SCF Iter265:       171.46362161   -1.47823E+01    6.56094E+01
SCF Iter266:       161.61101984   -9.85260E+00    6.48044E+01
SCF Iter267:       149.12824674   -1.24828E+01    6.35893E+01
SCF Iter268:       157.30345672    8.17521E+00    6.47479E+01
SCF Iter269:       159.47880902    2.17535E+00    6.51789E+01
SCF Iter270:       150.90627425   -8.57253E+00    6.44072E+01
SCF Iter271:       152.88079047    1.97452E+00    6.48844E+01
SCF Iter272:       145.28279577   -7.59799E+00    6.42012E+01
SCF Iter273:       131.55515971   -1.37276E+01    6.28606E+01
SCF Iter274:       126.87176163   -4.68340E+00    6.24968E+01
SCF Iter275:       112.97347238   -1.38983E+01    6.11723E+01
SCF Iter276:       107.96455872   -5.00891E+00    6.08004E+01
SCF Iter277:        94.27751089   -1.36870E+01    5.94973E+01
SCF Iter278:        84.34683794   -9.93067E+00    5.86086E+01
SCF Iter279:        74.41800727   -9.92883E+00    5.77099E+01
SCF Iter280:        64.68238147   -9.73563E+00    5.68244E+01
SCF Iter281:        53.02377302   -1.16586E+01    5.56955E+01
SCF Iter282:        41.93865332   -1.10851E+01    5.46204E+01
SCF Iter283:        30.31181177   -1.16268E+01    5.34995E+01
SCF Iter284:        18.98544923   -1.13264E+01    5.24099E+01
SCF Iter285:        25.06666006    6.08121E+00    5.36603E+01
SCF Iter286:        16.79914995   -8.26751E+00    5.29329E+01
SCF Iter287:         4.96462675   -1.18345E+01    5.17789E+01
SCF Iter288:        -0.66729618   -5.63192E+00    5.12877E+01
SCF Iter289:       -10.70861075   -1.00413E+01    5.02964E+01
SCF Iter290:       -20.58058909   -9.87198E+00    4.93280E+01
SCF Iter291:       -29.59136022   -9.01077E+00    4.84819E+01
SCF Iter292:       -38.59087327   -8.99951E+00    4.76178E+01
SCF Iter293:         6.24466794    4.48355E+01    5.44472E+01
SCF Iter294:        51.62104061    4.53764E+01    6.24379E+01
SCF Iter295:       100.34737807    4.87263E+01    7.12878E+01
SCF Iter296:       111.14513420    1.07978E+01    7.37203E+01
SCF Iter297:        98.88709692   -1.22580E+01    7.23193E+01
SCF Iter298:        85.61602187   -1.32711E+01    7.07728E+01
SCF Iter299:        72.45403571   -1.31620E+01    6.92690E+01
SCF Iter300:        60.22168045   -1.22324E+01    6.78591E+01
SCF Iter301:        47.78269611   -1.24390E+01    6.64451E+01
SCF Iter302:        45.32149752   -2.46120E+00    6.63474E+01
SCF Iter303:        40.24085969   -5.08064E+00    6.59141E+01
SCF Iter304:        37.36546264   -2.87540E+00    6.58137E+01
SCF Iter305:        34.20251087   -3.16295E+00    6.56641E+01
SCF Iter306:        79.27404872    4.50715E+01    7.39978E+01
SCF Iter307:       116.07843411    3.68044E+01    8.11559E+01
SCF Iter308:       129.83305077    1.37546E+01    8.41371E+01
SCF Iter309:       143.53875061    1.37057E+01    8.71012E+01
SCF Iter310:       128.53055832   -1.50082E+01    8.52923E+01
SCF Iter311:       116.46108905   -1.20695E+01    8.38440E+01
SCF Iter312:       103.81163707   -1.26495E+01    8.22680E+01
SCF Iter313:        91.30450784   -1.25071E+01    8.07801E+01
SCF Iter314:        80.48661940   -1.08179E+01    7.94742E+01
SCF Iter315:        68.08836244   -1.23983E+01    7.79052E+01
SCF Iter316:        55.89750095   -1.21909E+01    7.63976E+01
SCF Iter317:        48.73409010   -7.16341E+00    7.57402E+01
SCF Iter318:        43.27524945   -5.45884E+00    7.52170E+01
SCF Iter319:        37.01863047   -6.25662E+00    7.45013E+01
SCF Iter320:        31.25244588   -5.76618E+00    7.38612E+01

In [70]:
GUESS_A = Da
GUESS_B = Db

In [3]:
psi4.core.set_output_file('output.dat', False)

ATOMS = {
    # Period 3 (Na-Ar)
    'Na': {'mult': 2},  # [Ne] 3s1
    'Mg': {'mult': 1},  # [Ne] 3s2
    'Al': {'mult': 2},  # [Ne] 3s2 3p1
    'Si': {'mult': 3},  # [Ne] 3s2 3p2 
    # 'P':  {'mult': 4},  # [Ne] 3s2 3p3 
    # 'S':  {'mult': 3},  # [Ne] 3s2 3p4
    # 'Cl': {'mult': 2},  # [Ne] 3s2 3p5
    # 'Ar': {'mult': 1},  # [Ne] 3s2 3p6
    # Period 4 (Selected)
    # 'K':  {'mult': 2},  # [Ar] 4s1
    # 'Ca': {'mult': 1},  # [Ar] 4s2
    # 'Cu': {'mult': 2},  # [Ar] 3d10 4s1 
    # 'Zn': {'mult': 1},  # [Ar] 3d10 4s2
    # 'Kr': {'mult': 1},  # [Ar] 3d10 4s2 4p6
}

METHOD = "TF0.111111W LDA"
TP = ['LDA_K_TF', 1.0]
LAMBDA = 0.111111
EXC = ['LDA_X', 1.0, 'LDA_C_VWN', 0.0]
# EXC = ['GGA_X_PBE', 1.0, 'LDA_C_VWN', 0.0]
FA = [False, 1.0]
DIIS = True
MAX_ITER = 15000
DAMPING = [0.99, 0.99, 0.00003]
# D_guess = [GUESS_A, GUESS_B]
D_guess = None
verbose=True

psi4.set_options({'basis': 'UGBS_S', 
                  'DFT_SPHERICAL_POINTS': 6, 
                  'DFT_RADIAL_POINTS': 1000})

for atom in ATOMS:
    
    if not df.empty:
        exists = df[
            (df['Atom'] == atom) & 
            (df['Method'] == METHOD) & 
            (df['Basis'] == psi4.core.get_global_option("BASIS"))
        ]
        if not exists.empty:
            print(f"Skipping {atom} (Already exists for {METHOD}/{psi4.core.get_global_option("BASIS")})")
            continue

    print(f"Calculating {atom} with {METHOD}...")
    MOL = psi4.geometry(f"0 {ATOMS[atom]['mult']}\n {atom}\nsymmetry c1")
    try:
        E, Da, Db, iterations = lps_solver(MAX_ITER,TP,EXC,LAMBDA,MOL,DAMPING,FA,D_guess,DIIS,verbose)
        if iterations >= MAX_ITER:
            print("  !!! SCF failed to converge (Max cycles exceeded).")
        else:
            print(f"Calculated Energy: {E:.4f} Hartree")
            row = {
                "Method": METHOD,
                "Atom": atom,
                "Basis": psi4.core.get_global_option("BASIS"),
                "Grid_Sph": psi4.core.get_global_option("DFT_SPHERICAL_POINTS"),
                "Grid_Rad": psi4.core.get_global_option("DFT_RADIAL_POINTS"),
                "Energy,Ha": round(E, 6),
                "Iterations": iterations,
                "DIIS": DIIS,
                "Damp_Start": DAMPING[0],
                "Damp_End": DAMPING[1],
                "Damp_Cutoff": DAMPING[2]
            }
            
            df = pd.concat([df, pd.DataFrame([row])], ignore_index=True)
    
    except Exception as e:
        print(f"  !!! Failed {atom}. Error: {e}")
        continue

Calculating Na with TF0.111111W LDA...
Number of basis functions:   31

Starting SCF iterations:

    Iter            Energy            Delta E         dRMS

SCF Iter  1:      1013.66449694    1.01366E+03    9.26732E+01
SCF Iter  2:       986.95713182   -2.67074E+01    9.09041E+01
SCF Iter  3:       960.80417751   -2.61530E+01    8.91681E+01
SCF Iter  4:       935.99791645   -2.48063E+01    8.78138E+01
SCF Iter  5:       911.68973227   -2.43082E+01    8.71928E+01
SCF Iter  6:       887.88597139   -2.38038E+01    8.72969E+01
SCF Iter  7:       864.57851009   -2.33075E+01    8.80979E+01
SCF Iter  8:       841.44325652   -2.31353E+01    8.66941E+01
SCF Iter  9:       824.84699834   -1.65963E+01    8.51342E+01
SCF Iter 10:       803.45991924   -2.13871E+01    8.36134E+01
SCF Iter 11:       782.79111186   -2.06688E+01    8.21215E+01
SCF Iter 12:       761.05745521   -2.17337E+01    8.06503E+01
SCF Iter 13:       740.26518488   -2.07923E+01    7.92054E+01
SCF Iter 14:       719.59235259   -2.06728E+01    7.77889E+01
SCF Iter 15:       699.29916751   -2.02932E+01    7.63989E+01
SCF Iter 16:       679.74225639   -1.95569E+01    7.50351E+01
SCF Iter 17:       660.47759019   -1.92647E+01    7.36969E+01
SCF Iter 18:       643.20373413   -1.72739E+01    7.23761E+01
SCF Iter 19:       624.66669815   -1.85370E+01    7.10878E+01
SCF Iter 20:       607.18021909   -1.74865E+01    6.98230E+01
SCF Iter 21:       590.49398460   -1.66862E+01    6.85799E+01
SCF Iter 22:       573.50651922   -1.69875E+01    6.73623E+01
SCF Iter 23:       557.94892497   -1.55576E+01    6.61654E+01
SCF Iter 24:       544.03059855   -1.39183E+01    6.49823E+01
SCF Iter 25:       528.97854599   -1.50521E+01    6.38297E+01
SCF Iter 26:       513.96640767   -1.50121E+01    6.26943E+01
SCF Iter 27:       498.55066559   -1.54157E+01    6.15859E+01
SCF Iter 28:       483.38630724   -1.51644E+01    6.04986E+01
SCF Iter 29:       468.75558894   -1.46307E+01    5.94354E+01
SCF Iter 30:       454.84788192   -1.39077E+01    5.83881E+01
SCF Iter 31:       440.34184920   -1.45060E+01    5.73653E+01
SCF Iter 32:       442.65887366    2.31702E+00    5.74712E+01
SCF Iter 33:       432.01117685   -1.06477E+01    5.64444E+01
SCF Iter 34:       421.45875386   -1.05524E+01    5.55052E+01
SCF Iter 35:       408.77171632   -1.26870E+01    5.45324E+01
SCF Iter 36:       399.86693997   -8.90478E+00    5.35565E+01
SCF Iter 37:       386.82955594   -1.30374E+01    5.26248E+01
SCF Iter 38:       378.71702419   -8.11253E+00    5.16901E+01
SCF Iter 39:       370.66218004   -8.05484E+00    5.07739E+01
SCF Iter 40:       362.44524989   -8.21693E+00    4.98773E+01
SCF Iter 41:       350.60431735   -1.18409E+01    4.90160E+01
SCF Iter 42:       343.43639276   -7.16792E+00    4.81607E+01
SCF Iter 43:       332.42549871   -1.10109E+01    4.73324E+01
SCF Iter 44:       324.60622781   -7.81927E+00    4.65190E+01
SCF Iter 45:       316.22596283   -8.38026E+00    4.57244E+01
SCF Iter 46:       307.19269951   -9.03326E+00    4.49474E+01
SCF Iter 47:       299.23283147   -7.95987E+00    4.41799E+01
SCF Iter 48:       290.14046642   -9.09237E+00    4.34278E+01
SCF Iter 49:       281.79426114   -8.34621E+00    4.26925E+01
SCF Iter 50:       272.60684854   -9.18741E+00    4.19698E+01
SCF Iter 51:       264.06194382   -8.54490E+00    4.12625E+01
SCF Iter 52:       255.72777866   -8.33417E+00    4.05692E+01
SCF Iter 53:       247.23408652   -8.49369E+00    3.98885E+01
SCF Iter 54:       238.63533748   -8.59875E+00    3.92207E+01
SCF Iter 55:       230.10196395   -8.53337E+00    3.85663E+01
SCF Iter 56:       221.48331054   -8.61865E+00    3.79243E+01
SCF Iter 57:       212.92935210   -8.55396E+00    3.72949E+01
SCF Iter 58:       204.67497557   -8.25438E+00    3.66779E+01
SCF Iter 59:       196.52572581   -8.14925E+00    3.60728E+01
SCF Iter 60:       188.91978384   -7.60594E+00    3.54794E+01
SCF Iter 61:       181.47037719   -7.44941E+00    3.48977E+01
SCF Iter 62:       174.11974768   -7.35063E+00    3.43274E+01
SCF Iter 63:       167.39128714   -6.72846E+00    3.37670E+01
SCF Iter 64:       161.13322683   -6.25806E+00    3.32148E+01
SCF Iter 65:       160.35334934   -7.79877E-01    3.30587E+01
SCF Iter 66:       158.27299190   -2.08036E+00    3.28056E+01
SCF Iter 67:       155.98977129   -2.28322E+00    3.25411E+01
SCF Iter 68:       148.67933378   -7.31044E+00    3.20137E+01
SCF Iter 69:       141.56441134   -7.11492E+00    3.14961E+01
SCF Iter 70:       134.72531574   -6.83910E+00    3.09887E+01
SCF Iter 71:       128.18293194   -6.54238E+00    3.04911E+01
SCF Iter 72:       121.80995791   -6.37297E+00    3.00033E+01
SCF Iter 73:       115.65368300   -6.15627E+00    2.95253E+01
SCF Iter 74:       109.64625680   -6.00743E+00    2.90566E+01
SCF Iter 75:       110.85478662    1.20853E+00    2.91402E+01
SCF Iter 76:       112.06984960    1.21506E+00    2.92240E+01
SCF Iter 77:       105.99422858   -6.07562E+00    2.87597E+01
SCF Iter 78:       100.15074851   -5.84348E+00    2.83123E+01
SCF Iter 79:        94.35954608   -5.79120E+00    2.78680E+01
SCF Iter 80:        88.68285104   -5.67670E+00    2.74325E+01
SCF Iter 81:        89.00977363    3.26923E-01    2.74554E+01
SCF Iter 82:        89.28792833    2.78155E-01    2.74768E+01
SCF Iter 83:        87.30412044   -1.98381E+00    2.72966E+01
SCF Iter 84:        85.28719453   -2.01693E+00    2.71230E+01
SCF Iter 85:        79.89127013   -5.39592E+00    2.66970E+01
SCF Iter 86:        77.52252693   -2.36874E+00    2.62673E+01
SCF Iter 87:        73.44020595   -4.08232E+00    2.58497E+01
SCF Iter 88:        69.53755238   -3.90265E+00    2.54419E+01
SCF Iter 89:        64.86061432   -4.67694E+00    2.50490E+01
SCF Iter 90:        60.45062857   -4.40999E+00    2.46646E+01
SCF Iter 91:        55.82218810   -4.62844E+00    2.42869E+01
SCF Iter 92:        51.76287354   -4.05931E+00    2.39417E+01
SCF Iter 93:        47.96911498   -3.79376E+00    2.36108E+01
SCF Iter 94:        44.23506468   -3.73405E+00    2.32657E+01
SCF Iter 95:        41.02367091   -3.21139E+00    2.29185E+01
SCF Iter 96:        37.56453363   -3.45914E+00    2.25925E+01
SCF Iter 97:        34.21801857   -3.34652E+00    2.22698E+01
SCF Iter 98:        30.24839269   -3.96963E+00    2.19386E+01
SCF Iter 99:        35.62111312    5.37272E+00    2.23264E+01
SCF Iter100:        31.70046404   -3.92065E+00    2.20225E+01
SCF Iter101:        28.83611246   -2.86435E+00    2.17916E+01
SCF Iter102:        25.71166975   -3.12444E+00    2.15167E+01
SCF Iter103:        22.67515926   -3.03651E+00    2.12737E+01
SCF Iter104:        19.09594606   -3.57921E+00    2.09720E+01
SCF Iter105:        15.47371428   -3.62223E+00    2.06758E+01
SCF Iter106:        11.81469512   -3.65902E+00    2.03790E+01
SCF Iter107:        13.95035395    2.13566E+00    2.05377E+01
SCF Iter108:        16.93978212    2.98943E+00    2.07305E+01
SCF Iter109:        19.16921715    2.22944E+00    2.08521E+01
SCF Iter110:        15.96781272   -3.20140E+00    2.05530E+01
SCF Iter111:        13.18089479   -2.78692E+00    2.02571E+01
SCF Iter112:        10.42463751   -2.75626E+00    1.99682E+01
SCF Iter113:         7.48511990   -2.93952E+00    1.96915E+01
SCF Iter114:         8.40963916    9.24519E-01    1.97470E+01
SCF Iter115:         8.78936432    3.79725E-01    1.98108E+01
SCF Iter116:         9.22510412    4.35740E-01    1.98555E+01
SCF Iter117:         5.52251242   -3.70259E+00    1.95650E+01
SCF Iter118:         2.16444785   -3.35806E+00    1.92967E+01
SCF Iter119:        -1.10595243   -3.27040E+00    1.90332E+01
SCF Iter120:        -4.43237632   -3.32642E+00    1.87624E+01
SCF Iter121:        -5.79233017   -1.35995E+00    1.86420E+01
SCF Iter122:        -7.59883895   -1.80651E+00    1.84761E+01
SCF Iter123:        -9.46134858   -1.86251E+00    1.83177E+01
SCF Iter124:       -12.25494580   -2.79360E+00    1.80737E+01
SCF Iter125:       -15.17044613   -2.91550E+00    1.78276E+01
SCF Iter126:       -17.87712855   -2.70668E+00    1.75863E+01
SCF Iter127:       -17.19984066    6.77288E-01    1.76503E+01
SCF Iter128:       -16.19449912    1.00534E+00    1.77691E+01
SCF Iter129:       -16.62322662   -4.28728E-01    1.77466E+01
SCF Iter130:       -16.79638820   -1.73162E-01    1.77456E+01
SCF Iter131:       -17.24398763   -4.47599E-01    1.77164E+01
SCF Iter132:       -18.80039232   -1.55640E+00    1.75956E+01
SCF Iter133:       -21.18462762   -2.38424E+00    1.73568E+01
SCF Iter134:       -21.65911899   -4.74491E-01    1.70927E+01
SCF Iter135:       -22.50041542   -8.41296E-01    1.68367E+01
SCF Iter136:       -23.61962485   -1.11921E+00    1.65885E+01
SCF Iter137:       -24.95831103   -1.33869E+00    1.63495E+01
SCF Iter138:       -26.65422232   -1.69591E+00    1.61219E+01
SCF Iter139:       -24.93231730    1.72191E+00    1.63106E+01
SCF Iter140:       -23.70202028    1.23030E+00    1.64614E+01
SCF Iter141:       -26.19059949   -2.48858E+00    1.62401E+01
SCF Iter142:       -28.72960932   -2.53901E+00    1.60105E+01
SCF Iter143:       -31.34125268   -2.61164E+00    1.57857E+01
SCF Iter144:       -29.10820772    2.23304E+00    1.60703E+01
SCF Iter145:       -28.10760393    1.00060E+00    1.61792E+01
SCF Iter146:       -27.76479096    3.42813E-01    1.62168E+01
SCF Iter147:       -30.37345856   -2.60867E+00    1.59859E+01
SCF Iter148:       -30.24857617    1.24882E-01    1.60132E+01
SCF Iter149:       -32.80381380   -2.55524E+00    1.57855E+01
SCF Iter150:       -28.36920646    4.43461E+00    1.62312E+01
SCF Iter151:       -31.09242414   -2.72322E+00    1.60004E+01
SCF Iter152:       -33.79598144   -2.70356E+00    1.57743E+01
SCF Iter153:       -33.09643071    6.99551E-01    1.58773E+01
SCF Iter154:       -35.66159281   -2.56516E+00    1.56607E+01
SCF Iter155:       -33.07535883    2.58623E+00    1.59341E+01
SCF Iter156:       -29.25913930    3.81622E+00    1.62903E+01
SCF Iter157:       -30.10178969   -8.42650E-01    1.62348E+01
SCF Iter158:       -31.60153922   -1.49975E+00    1.60961E+01
SCF Iter159:       -34.21371888   -2.61218E+00    1.58615E+01
SCF Iter160:       -36.79066542   -2.57695E+00    1.56323E+01
SCF Iter161:       -32.23416896    4.55650E+00    1.60549E+01
SCF Iter162:       -26.70165329    5.53252E+00    1.65208E+01
SCF Iter163:       -22.85979331    3.84186E+00    1.67916E+01
SCF Iter164:       -20.60335606    2.25644E+00    1.69940E+01
SCF Iter165:       -23.30467417   -2.70132E+00    1.67603E+01
SCF Iter166:       -26.16608763   -2.86141E+00    1.65135E+01
SCF Iter167:       -27.92894725   -1.76286E+00    1.64019E+01
SCF Iter168:       -30.77778764   -2.84884E+00    1.61570E+01
SCF Iter169:       -25.41733234    5.36046E+00    1.66722E+01
SCF Iter170:       -16.99885411    8.41848E+00    1.75157E+01
SCF Iter171:        -8.24833194    8.75052E+00    1.83086E+01
SCF Iter172:        -9.26669051   -1.01836E+00    1.82657E+01
SCF Iter173:       -10.07060442   -8.03914E-01    1.82454E+01
SCF Iter174:       -13.41954944   -3.34895E+00    1.79610E+01
SCF Iter175:       -15.27778811   -1.85824E+00    1.78811E+01
SCF Iter176:       -17.03238804   -1.75460E+00    1.77721E+01
SCF Iter177:       -18.78396069   -1.75157E+00    1.76578E+01
SCF Iter178:       -21.11980889   -2.33585E+00    1.74790E+01
SCF Iter179:       -13.34302887    7.77678E+00    1.81634E+01
SCF Iter180:       -16.30856841   -2.96554E+00    1.79084E+01
SCF Iter181:       -19.51558539   -3.20702E+00    1.76216E+01
SCF Iter182:       -22.47308628   -2.95750E+00    1.73514E+01
SCF Iter183:       -24.76892522   -2.29584E+00    1.71447E+01
SCF Iter184:       -26.78202377   -2.01310E+00    1.69842E+01
SCF Iter185:       -28.04142821   -1.25940E+00    1.69358E+01
SCF Iter186:       -29.02250333   -9.81075E-01    1.69268E+01
SCF Iter187:       -22.56587826    6.45663E+00    1.75264E+01
SCF Iter188:       -18.70867810    3.85720E+00    1.78977E+01
SCF Iter189:       -14.80860272    3.90008E+00    1.82896E+01
SCF Iter190:       -17.60191374   -2.79331E+00    1.80498E+01
SCF Iter191:       -20.86324254   -3.26133E+00    1.77513E+01
SCF Iter192:       -24.02477471   -3.16153E+00    1.74594E+01
SCF Iter193:       -20.51226988    3.51250E+00    1.77879E+01
SCF Iter194:       -15.65139570    4.86087E+00    1.82353E+01
SCF Iter195:       -11.10814060    4.54326E+00    1.86689E+01
SCF Iter196:        -7.02290966    4.08523E+00    1.90565E+01
SCF Iter197:        -8.14411601   -1.12121E+00    1.89877E+01
SCF Iter198:        -5.83087330    2.31324E+00    1.92684E+01
SCF Iter199:        -9.34219759   -3.51132E+00    1.89397E+01
SCF Iter200:       -10.60130094   -1.25910E+00    1.89273E+01
SCF Iter201:       -13.72430292   -3.12300E+00    1.86508E+01
SCF Iter202:       -15.93931684   -2.21501E+00    1.84964E+01
SCF Iter203:       -19.19926064   -3.25994E+00    1.81881E+01
SCF Iter204:       -16.27672981    2.92253E+00    1.85264E+01
SCF Iter205:       -15.41298580    8.63744E-01    1.85885E+01
SCF Iter206:       -18.69195755   -3.27897E+00    1.82739E+01
SCF Iter207:       -21.85108583   -3.15913E+00    1.79670E+01
SCF Iter208:       -24.91618826   -3.06510E+00    1.76646E+01
SCF Iter209:       -27.88840666   -2.97222E+00    1.73660E+01
SCF Iter210:       -30.69887562   -2.81047E+00    1.70724E+01
SCF Iter211:       -29.20593053    1.49295E+00    1.73467E+01
SCF Iter212:       -27.49642231    1.70951E+00    1.76093E+01
SCF Iter213:       -27.13821888    3.58203E-01    1.76638E+01
SCF Iter214:       -28.13048886   -9.92270E-01    1.76263E+01
SCF Iter215:       -28.18450897   -5.40201E-02    1.76796E+01
SCF Iter216:       -29.21487021   -1.03036E+00    1.76416E+01
SCF Iter217:       -32.16462004   -2.94975E+00    1.73360E+01
SCF Iter218:       -34.43750923   -2.27289E+00    1.70471E+01
SCF Iter219:       -36.22644576   -1.78894E+00    1.68564E+01
SCF Iter220:       -38.03695336   -1.81051E+00    1.66957E+01
SCF Iter221:       -39.33131070   -1.29436E+00    1.65734E+01
SCF Iter222:       -40.74320142   -1.41189E+00    1.64470E+01
SCF Iter223:       -43.11593436   -2.37273E+00    1.61633E+01
SCF Iter224:       -44.59847648   -1.48254E+00    1.60140E+01
SCF Iter225:       -45.72387653   -1.12540E+00    1.59263E+01
SCF Iter226:       -46.81253347   -1.08866E+00    1.58415E+01
SCF Iter227:       -47.51642222   -7.03889E-01    1.58257E+01
SCF Iter228:       -48.47884251   -9.62420E-01    1.57573E+01
SCF Iter229:       -50.93503013   -2.45619E+00    1.54842E+01
SCF Iter230:       -47.03196675    3.90306E+00    1.59162E+01
SCF Iter231:       -48.14445133   -1.11248E+00    1.58275E+01
SCF Iter232:       -49.21758999   -1.07314E+00    1.57468E+01
SCF Iter233:       -50.50201666   -1.28443E+00    1.56358E+01
SCF Iter234:       -51.82251347   -1.32050E+00    1.55221E+01
SCF Iter235:       -51.71209269    1.10421E-01    1.55794E+01
SCF Iter236:       -53.91215156   -2.20006E+00    1.53024E+01
SCF Iter237:       -54.67509286   -7.62941E-01    1.52425E+01
SCF Iter238:       -55.45577974   -7.80687E-01    1.51835E+01
SCF Iter239:       -56.24408884   -7.88309E-01    1.51334E+01
SCF Iter240:       -56.73488249   -4.90794E-01    1.51120E+01
SCF Iter241:       -57.57476955   -8.39887E-01    1.50526E+01
SCF Iter242:       -59.85775149   -2.28298E+00    1.47876E+01
SCF Iter243:       -60.62836104   -7.70610E-01    1.47491E+01
SCF Iter244:       -61.32505342   -6.96692E-01    1.47258E+01
SCF Iter245:       -62.20834564   -8.83292E-01    1.46813E+01
SCF Iter246:       -63.27964064   -1.07129E+00    1.46125E+01
SCF Iter247:       -63.62184947   -3.42209E-01    1.46039E+01
SCF Iter248:       -63.46609009    1.55759E-01    1.45932E+01
SCF Iter249:       -64.17961856   -7.13528E-01    1.44721E+01
SCF Iter250:       -65.79886610   -1.61925E+00    1.43306E+01
SCF Iter251:       -66.94047199   -1.14161E+00    1.41839E+01
SCF Iter252:       -67.70250214   -7.62030E-01    1.40024E+01
SCF Iter253:       -68.60644764   -9.03945E-01    1.38773E+01
SCF Iter254:       -70.01275809   -1.40631E+00    1.37141E+01
SCF Iter255:       -71.07170333   -1.05895E+00    1.35882E+01
SCF Iter256:       -71.75703299   -6.85330E-01    1.33649E+01
SCF Iter257:       -72.51531190   -7.58279E-01    1.31438E+01
SCF Iter258:       -74.40705299   -1.89174E+00    1.29071E+01
SCF Iter259:       -72.69706439    1.70999E+00    1.31968E+01
SCF Iter260:       -73.69470253   -9.97638E-01    1.30695E+01
SCF Iter261:       -74.85394869   -1.15925E+00    1.29338E+01
SCF Iter262:       -75.64403256   -7.90084E-01    1.28144E+01
SCF Iter263:       -76.07785569   -4.33823E-01    1.27292E+01
SCF Iter264:       -78.10506024   -2.02720E+00    1.25008E+01
SCF Iter265:       -79.07966668   -9.74606E-01    1.23384E+01
SCF Iter266:       -79.73430201   -6.54635E-01    1.22699E+01
SCF Iter267:       -81.11642400   -1.38212E+00    1.21019E+01
SCF Iter268:       -82.07988672   -9.63463E-01    1.19596E+01
SCF Iter269:       -83.01086915   -9.30982E-01    1.18189E+01
SCF Iter270:       -84.15574683   -1.14488E+00    1.17252E+01
SCF Iter271:       -85.84045114   -1.68470E+00    1.15210E+01
SCF Iter272:       -85.49386942    3.46582E-01    1.16543E+01
SCF Iter273:       -86.28728679   -7.93417E-01    1.15387E+01
SCF Iter274:       -87.12913531   -8.41849E-01    1.14054E+01
SCF Iter275:       -88.49472425   -1.36559E+00    1.12050E+01
SCF Iter276:       -89.72783422   -1.23311E+00    1.10094E+01
SCF Iter277:       -89.76214207   -3.43079E-02    1.10975E+01
SCF Iter278:       -90.29950571   -5.37364E-01    1.10669E+01
SCF Iter279:       -89.81839507    4.81111E-01    1.11987E+01
SCF Iter280:       -90.13015946   -3.11764E-01    1.12428E+01
SCF Iter281:       -91.29965235   -1.16949E+00    1.10608E+01
SCF Iter282:       -92.60771436   -1.30806E+00    1.08610E+01
SCF Iter283:       -91.66868175    9.39033E-01    1.10769E+01
SCF Iter284:       -91.85404241   -1.85361E-01    1.10907E+01
SCF Iter285:       -90.31407095    1.53997E+00    1.14679E+01
SCF Iter286:       -89.07255014    1.24152E+00    1.17322E+01
SCF Iter287:       -88.42564722    6.46903E-01    1.18385E+01
SCF Iter288:       -87.26990423    1.15574E+00    1.20052E+01
SCF Iter289:       -88.85363520   -1.58373E+00    1.17738E+01
SCF Iter290:       -89.11056468   -2.56929E-01    1.17650E+01
SCF Iter291:       -89.88797888   -7.77414E-01    1.17048E+01
SCF Iter292:       -90.25116806   -3.63189E-01    1.16255E+01
SCF Iter293:       -90.74475654   -4.93588E-01    1.15913E+01
SCF Iter294:       -84.83008810    5.91467E+00    1.24797E+01
SCF Iter295:       -80.58314776    4.24694E+00    1.31509E+01
SCF Iter296:       -77.36013287    3.22301E+00    1.36183E+01
SCF Iter297:       -78.76362311   -1.40349E+00    1.34856E+01
SCF Iter298:       -79.92180820   -1.15819E+00    1.33948E+01
SCF Iter299:       -81.98794646   -2.06614E+00    1.31298E+01
SCF Iter300:       -82.80527704   -8.17331E-01    1.30327E+01
SCF Iter301:       -83.06197422   -2.56697E-01    1.29792E+01
SCF Iter302:       -83.24704525   -1.85071E-01    1.29719E+01
SCF Iter303:       -82.80325024    4.43795E-01    1.30719E+01
SCF Iter304:       -83.44099014   -6.37740E-01    1.30287E+01
SCF Iter305:       -85.47646682   -2.03548E+00    1.27646E+01
SCF Iter306:       -85.33821676    1.38250E-01    1.28402E+01
SCF Iter307:       -85.24431568    9.39011E-02    1.28935E+01
SCF Iter308:       -85.18858116    5.57345E-02    1.29394E+01
SCF Iter309:       -84.61951720    5.69064E-01    1.30675E+01
SCF Iter310:       -84.49186907    1.27648E-01    1.31370E+01
SCF Iter311:       -86.52121260   -2.02934E+00    1.28584E+01
SCF Iter312:       -87.51704000   -9.95827E-01    1.27265E+01
SCF Iter313:       -88.24516534   -7.28125E-01    1.26505E+01
SCF Iter314:       -89.27282427   -1.02766E+00    1.25361E+01
SCF Iter315:       -90.03337916   -7.60555E-01    1.24484E+01
SCF Iter316:       -91.30784475   -1.27447E+00    1.22964E+01
SCF Iter317:       -93.22410966   -1.91626E+00    1.20356E+01
SCF Iter318:       -90.49176875    2.73234E+00    1.25001E+01
SCF Iter319:       -90.58770056   -9.59318E-02    1.25407E+01
SCF Iter320:       -90.32521418    2.62486E-01    1.26085E+01

In [4]:
df.to_csv(csv_file, index=False)
df

,Method,Atom,Basis,Grid_Sph,Grid_Rad,"Energy,Ha",Iterations,DIIS,Damp_Start,Damp_End,Damp_Cutoff
0,TFW LDA,Na,UGBS_S,6,1000,-108.912083,284,True,0.90,0.90,0.00009
1,TFW LDA,Mg,UGBS_S,6,1000,-135.553609,237,True,0.90,0.90,0.00009
2,TFW LDA,Al,UGBS_S,6,1000,-165.669941,387,True,0.90,0.90,0.00009
3,TFW LDA,Si,UGBS_S,6,1000,-199.392286,517,True,0.90,0.90,0.00009
4,TFW LDA,P,UGBS_S,6,1000,-236.833553,342,True,0.90,0.90,0.00009
...,...,...,...,...,...,...,...,...,...,...,...
137,TF0.2W FA,Cl,UGBS_S,6,1000,-445.209435,4560,True,0.99,0.90,0.00003
138,TF0.166666W FA,Cl,UGBS_S,6,1000,-456.106275,10340,True,0.99,0.90,0.00003
139,TF0.111111W LDA,Na,UGBS_S,6,1000,-175.220390,4870,True,0.99,0.99,0.00003
140,TF0.111111W LDA,Mg,UGBS_S,6,1000,-215.265035,4402,True,0.99,0.99,0.00003
141,TF0.111111W LDA,Al,UGBS_S,6,1000,-260.117429,14370,True,0.99,0.99,0.00003

In [ ]:
## TF0.111111W PBE for O and F used TF0.111111W FA densities of O and F as initial guesses
## TF0.111111W FA for Si, Kr used TF0.166666W FA initial guess
## TF0.2W FA for Cl used TF0.333333W FA initial guess
## TF0.166666W FA for Cl used TF0.2W FA initial guess

In [22]:
ATOMS = {
    'He':  {'mult': 1}, 
    'Be': {'mult': 1},
    'Ne': {'mult': 1}, 
    'Mg': {'mult': 1},
    'Ar':  {'mult': 1}, 
    'Ca':  {'mult': 1},
    'Zn':  {'mult': 1}, 
    'Kr':  {'mult': 1}
}
psi4.core.set_output_file('output.dat', False)
psi4.set_options({'basis': 'UGBS',
                  'scf_type': 'PK'})
rhf_energies = {}
rhf_homos = {}
for atom in ATOMS:
    MOL = psi4.geometry(f"0 {ATOMS[atom]['mult']}\n {atom}\nsymmetry c1")
    E, wfn = psi4.energy('SCF', return_wfn=True)
    homo = wfn.epsilon_a().np[wfn.nalpha()-1]
    rhf_energies[atom] = round(E, 6)
    rhf_homos[atom] = round(homo, 6)
    print(f"RHF/UGBS {atom} Energy: {E:.4f} Hartree, IP: {homo:.4f}")

RHF/UGBS He Energy: -2.8617 Hartree, IP: -0.9180
RHF/UGBS Be Energy: -14.5730 Hartree, IP: -0.3093
RHF/UGBS Ne Energy: -128.5471 Hartree, IP: -0.8504
RHF/UGBS Mg Energy: -199.6146 Hartree, IP: -0.2530
RHF/UGBS Ar Energy: -526.8175 Hartree, IP: -0.5910
RHF/UGBS Ca Energy: -676.7582 Hartree, IP: -0.1955
RHF/UGBS Zn Energy: -1777.8481 Hartree, IP: -0.2925
RHF/UGBS Kr Energy: -2752.0549 Hartree, IP: -0.5242

In [26]:
atom_order = ['He', 'Be', 'Ne', 'Mg', 'Ar', 'Ca', 'Zn', 'Kr']
energy_table = df.pivot(index='Atom', columns='Method', values='Energy,Ha')
energy_table = energy_table.reindex(atom_order)
energy_table['RHF/UGBS'] = pd.Series(rhf_energies)
new_order = ['TFD0.166666W', 'TF0.166666W PBEx', 'TF0.166666W FA', 'RHF/UGBS']
energy_table = energy_table[new_order]

In [28]:
reference = energy_table['RHF/UGBS']

res = {}
for method, energies in energy_table.items():
    if method == 'RHF/UGBS': 
        continue 
    
    mae  = (energies - reference).abs().mean()
    rmae = (((energies - reference).abs()) / reference * -100).mean()
    res[method] = round(mae, 2), round(rmae, 2)

mae_row  = {method: values[0] for method, values in res.items()}
rmae_row = {method: values[1] for method, values in res.items()}
stats_df = pd.DataFrame([mae_row, rmae_row], index=['MAE(Ha)', 'rMAE(%)'])
energy_table = pd.concat([energy_table, stats_df], sort=False)

In [29]:
display(energy_table)

         TFD0.166666W  TF0.166666W PBEx  TF0.166666W FA     RHF/UGBS
He          -2.951247         -3.097069       -3.019526    -2.861680
Be         -15.040391        -15.388877      -14.660508   -14.573023
Ne        -132.508856       -133.573716     -128.291707  -128.547083
Mg        -204.540690       -205.864549     -198.305386  -199.614621
Ar        -537.208760       -539.346529     -522.928926  -526.817486
Ca        -690.396266       -692.814969     -672.808485  -676.758154
Zn       -1812.192490      -1816.067937    -1773.727670 -1777.848060
Kr       -2795.914635      -2800.696590    -2741.665221 -2752.054860
MAE(Ha)     13.960000         15.970000        3.020000          NaN
rMAE(%)      2.420000          3.690000        1.110000          NaN

In [33]:
atom_order = ['He', 'Be', 'Ne', 'Mg', 'Ar', 'Ca', 'Zn', 'Kr']
mu_table = df.pivot(index='Atom', columns='Method', values='ChemPot,Ha')
mu_table = mu_table.reindex(atom_order)
mu_table['RHF/UGBS'] = pd.Series(rhf_homos)
new_order = ['TFD0.166666W', 'TF0.166666W PBEx', 'TF0.166666W FA', 'RHF/UGBS']
mu_table = mu_table[new_order]

In [35]:
reference = mu_table['RHF/UGBS']

res = {}
for method, energies in mu_table.items():
    if method == 'RHF/UGBS': 
        continue 
    
    mae  = (energies - reference).abs().mean()
    rmae = (((energies - reference).abs()) / reference * -100).mean()
    res[method] = round(mae, 2), round(rmae, 2)

mae_row  = {method: values[0] for method, values in res.items()}
rmae_row = {method: values[1] for method, values in res.items()}
stats_df = pd.DataFrame([mae_row, rmae_row], index=['MAE(Ha)', 'rMAE(%)'])
mu_table = pd.concat([mu_table, stats_df], sort=False)

In [36]:
display(mu_table)

         TFD0.166666W  TF0.166666W PBEx  TF0.166666W FA  RHF/UGBS
He          -0.067106         -0.081193       -0.313483 -0.917956
Be          -0.069849         -0.081756       -0.272375 -0.309271
Ne          -0.072529         -0.082214       -0.231390 -0.850411
Mg          -0.072963         -0.082281       -0.224844 -0.253048
Ar          -0.073833         -0.082424       -0.211897 -0.590989
Ca          -0.074040         -0.082458       -0.208863 -0.195527
Zn          -0.074767         -0.082581       -0.198303 -0.292463
Kr          -0.075063         -0.082633       -0.194080 -0.524161
MAE(Ha)      0.420000          0.410000        0.260000       NaN
rMAE(%)     80.310000         77.800000       40.980000       NaN