In [1]:
import psi4
import pandas as pd
import os
import numpy as np
from lps_uscf import lps_solver

In [31]:
csv_file = 'open_shell_15atoms_vs_uhf.csv'

if os.path.exists(csv_file):
    df = pd.read_csv(csv_file)
    print(f"-> Loaded existing results: {len(df)} rows found.")
else:
    df = pd.DataFrame()
    print("-> No existing file found. Starting fresh.")

-> Loaded existing results: 144 rows found.

In [32]:
TP = ['LDA_K_TF', 1.0]
LAMBDA = 0.111111
EXC = ['LDA_X', 0.0, 'LDA_C_VWN', 0.0]
FA = [True, 1.0]
DIIS = True
MAX_ITER = 15000
DAMPING = [0.99, 0.9, 0.00009]
# D_guess = [GUESS_A, GUESS_B]
D_guess = None
verbose=True

psi4.set_options({'basis': 'UGBS_S', 
                  'DFT_SPHERICAL_POINTS': 6, 
                  'DFT_RADIAL_POINTS': 1000})

mol = psi4.geometry("""
units bohr
0 3
S
symmetry c1
""")

E, Da, Db, iterations = lps_solver(MAX_ITER,TP,EXC,LAMBDA,mol,DAMPING,FA,D_guess,DIIS,verbose)
print('\nFinal SCF energy: %.4f Hartree' % E)

Number of basis functions:   31

Starting SCF iterations:

    Iter            Energy            Delta E         dRMS

SCF Iter  1:      4916.48420144    4.91648E+03    3.89692E+02
SCF Iter  2:      4805.27925502   -1.11205E+02    3.82441E+02
SCF Iter  3:      4696.25357334   -1.09026E+02    3.75321E+02
SCF Iter  4:      4597.87521992   -9.83784E+01    3.69877E+02
SCF Iter  5:      4501.27064076   -9.66046E+01    3.67670E+02
SCF Iter  6:      4406.54668257   -9.47240E+01    3.68649E+02
SCF Iter  7:      4313.69984647   -9.28468E+01    3.72681E+02
SCF Iter  8:      4220.48714825   -9.32127E+01    3.66427E+02
SCF Iter  9:      4129.78727782   -9.06999E+01    3.60262E+02
SCF Iter 10:      4042.04976984   -8.77375E+01    3.54043E+02
SCF Iter 11:      3956.33474037   -8.57150E+01    3.48018E+02
SCF Iter 12:      3878.42780872   -7.79069E+01    3.42271E+02
SCF Iter 13:      3799.28568089   -7.91421E+01    3.36792E+02
SCF Iter 14:      3721.57895352   -7.77067E+01    3.31035E+02
SCF Iter 15:      3655.03550957   -6.65434E+01    3.25362E+02
SCF Iter 16:      3584.49850375   -7.05370E+01    3.19707E+02
SCF Iter 17:      3509.65177267   -7.48467E+01    3.14175E+02
SCF Iter 18:      3442.38213848   -6.72696E+01    3.08677E+02
SCF Iter 19:      3373.29336375   -6.90888E+01    3.03284E+02
SCF Iter 20:      3297.53173338   -7.57616E+01    2.98013E+02
SCF Iter 21:      3225.82777302   -7.17040E+01    2.92859E+02
SCF Iter 22:      3154.16290039   -7.16649E+01    2.87792E+02
SCF Iter 23:      3089.95509963   -6.42078E+01    2.82775E+02
SCF Iter 24:      3023.97912887   -6.59760E+01    2.77834E+02
SCF Iter 25:      2957.26593768   -6.67132E+01    2.72992E+02
SCF Iter 26:      2891.02939943   -6.62365E+01    2.68254E+02
SCF Iter 27:      2825.57011007   -6.54593E+01    2.63603E+02
SCF Iter 28:      2760.74441480   -6.48257E+01    2.59054E+02
SCF Iter 29:      2699.61072696   -6.11337E+01    2.54595E+02
SCF Iter 30:      2642.41111016   -5.71996E+01    2.50220E+02
SCF Iter 31:      2585.71969636   -5.66914E+01    2.45925E+02
SCF Iter 32:      2526.93564787   -5.87840E+01    2.41710E+02
SCF Iter 33:      2467.59633441   -5.93393E+01    2.37570E+02
SCF Iter 34:      2409.63483453   -5.79615E+01    2.33505E+02
SCF Iter 35:      2395.34236430   -1.42925E+01    2.32083E+02
SCF Iter 36:      2371.17112276   -2.41712E+01    2.30030E+02
SCF Iter 37:      2339.64758449   -3.15235E+01    2.27484E+02
SCF Iter 38:      2286.58094987   -5.30666E+01    2.23556E+02
SCF Iter 39:      2234.09351392   -5.24874E+01    2.19701E+02
SCF Iter 40:      2182.14087824   -5.19526E+01    2.15933E+02
SCF Iter 41:      2127.14228351   -5.49986E+01    2.12247E+02
SCF Iter 42:      2092.51566040   -3.46266E+01    2.09786E+02
SCF Iter 43:      2064.38373781   -2.81319E+01    2.07663E+02
SCF Iter 44:      2031.06720295   -3.33165E+01    2.05113E+02
SCF Iter 45:      1995.65731834   -3.54099E+01    2.02296E+02
SCF Iter 46:      1946.49151490   -4.91658E+01    1.98845E+02
SCF Iter 47:      1898.60729107   -4.78842E+01    1.95472E+02
SCF Iter 48:      1854.83568412   -4.37716E+01    1.92242E+02
SCF Iter 49:      1820.01488064   -3.48208E+01    1.89409E+02
SCF Iter 50:      1793.67463743   -2.63402E+01    1.87203E+02
SCF Iter 51:      1747.47699037   -4.61976E+01    1.84022E+02
SCF Iter 52:      1704.30207843   -4.31749E+01    1.80901E+02
SCF Iter 53:      1661.84316999   -4.24589E+01    1.77837E+02
SCF Iter 54:      1619.97350600   -4.18697E+01    1.74831E+02
SCF Iter 55:      1578.36679801   -4.16067E+01    1.71881E+02
SCF Iter 56:      1537.07258329   -4.12942E+01    1.68985E+02
SCF Iter 57:      1496.89230043   -4.01803E+01    1.66144E+02
SCF Iter 58:      1458.68963288   -3.82027E+01    1.63355E+02
SCF Iter 59:      1420.34856260   -3.83411E+01    1.60619E+02
SCF Iter 60:      1384.46889429   -3.58797E+01    1.57934E+02
SCF Iter 61:      1348.37319219   -3.60957E+01    1.55296E+02
SCF Iter 62:      1314.83467957   -3.35385E+01    1.52709E+02
SCF Iter 63:      1281.82417319   -3.30105E+01    1.50171E+02
SCF Iter 64:      1248.05749160   -3.37667E+01    1.47677E+02
SCF Iter 65:      1215.15595526   -3.29015E+01    1.45220E+02
SCF Iter 66:      1185.33365360   -2.98223E+01    1.42811E+02
SCF Iter 67:      1155.35984388   -2.99738E+01    1.40450E+02
SCF Iter 68:      1124.27363060   -3.10862E+01    1.38138E+02
SCF Iter 69:      1121.32015745   -2.95347E+00    1.37702E+02
SCF Iter 70:      1095.01136979   -2.63088E+01    1.35409E+02
SCF Iter 71:      1067.79231684   -2.72191E+01    1.33150E+02
SCF Iter 72:      1038.09792821   -2.96944E+01    1.30949E+02
SCF Iter 73:      1010.08290977   -2.80150E+01    1.28780E+02
SCF Iter 74:       984.27794133   -2.58050E+01    1.26646E+02
SCF Iter 75:       958.17820967   -2.60997E+01    1.24557E+02
SCF Iter 76:       937.04082087   -2.11374E+01    1.22529E+02
SCF Iter 77:       914.51434027   -2.25265E+01    1.20542E+02
SCF Iter 78:       892.31097434   -2.22034E+01    1.18589E+02
SCF Iter 79:       871.05348974   -2.12575E+01    1.16668E+02
SCF Iter 80:       844.41504319   -2.66384E+01    1.14791E+02
SCF Iter 81:       817.89125176   -2.65238E+01    1.12948E+02
SCF Iter 82:       792.26822571   -2.56230E+01    1.11139E+02
SCF Iter 83:       767.47452354   -2.47937E+01    1.09365E+02
SCF Iter 84:       743.17898365   -2.42955E+01    1.07623E+02
SCF Iter 85:       790.39924765    4.72203E+01    1.10585E+02
SCF Iter 86:       811.20800086    2.08088E+01    1.11791E+02
SCF Iter 87:       824.92447048    1.37165E+01    1.12556E+02
SCF Iter 88:       800.16418242   -2.47603E+01    1.10733E+02
SCF Iter 89:       776.04349214   -2.41207E+01    1.08942E+02
SCF Iter 90:       751.84093223   -2.42026E+01    1.07184E+02
SCF Iter 91:       728.17448860   -2.36664E+01    1.05461E+02
SCF Iter 92:       705.04130402   -2.31332E+01    1.03768E+02
SCF Iter 93:       689.97925487   -1.50620E+01    1.02661E+02
SCF Iter 94:       668.33207311   -2.16472E+01    1.01093E+02
SCF Iter 95:       646.18437380   -2.21477E+01    9.94757E+01
SCF Iter 96:       668.60374737    2.24194E+01    1.00870E+02
SCF Iter 97:       686.32416892    1.77204E+01    1.02022E+02
SCF Iter 98:       681.86746449   -4.45670E+00    1.01550E+02
SCF Iter 99:       691.94713079    1.00797E+01    1.02131E+02
SCF Iter100:       669.59240977   -2.23547E+01    1.00469E+02
SCF Iter101:       647.93322354   -2.16592E+01    9.88386E+01
SCF Iter102:       628.06396750   -1.98693E+01    9.72392E+01
SCF Iter103:       608.27230454   -1.97917E+01    9.56723E+01
SCF Iter104:       587.62382330   -2.06485E+01    9.41331E+01
SCF Iter105:       570.22276604   -1.74011E+01    9.26299E+01
SCF Iter106:       554.55673709   -1.56660E+01    9.11448E+01
SCF Iter107:       537.73860229   -1.68181E+01    8.96924E+01
SCF Iter108:       518.14163311   -1.95970E+01    8.82664E+01
SCF Iter109:       501.49025011   -1.66514E+01    8.68585E+01
SCF Iter110:       483.03625715   -1.84540E+01    8.54848E+01
SCF Iter111:       464.69334120   -1.83429E+01    8.41373E+01
SCF Iter112:       515.95576000    5.12624E+01    8.75689E+01
SCF Iter113:       567.52953251    5.15738E+01    9.10424E+01
SCF Iter114:       563.44888302   -4.08065E+00    9.06359E+01
SCF Iter115:       544.46119112   -1.89877E+01    8.91925E+01
SCF Iter116:       524.88755914   -1.95736E+01    8.77545E+01
SCF Iter117:       505.30789359   -1.95797E+01    8.63371E+01
SCF Iter118:       487.15505321   -1.81528E+01    8.49539E+01
SCF Iter119:       469.26524987   -1.78898E+01    8.35922E+01
SCF Iter120:       455.50776014   -1.37575E+01    8.22431E+01
SCF Iter121:       440.22496857   -1.52828E+01    8.09265E+01
SCF Iter122:       423.53110055   -1.66939E+01    7.96385E+01
SCF Iter123:       412.08059288   -1.14505E+01    7.84850E+01
SCF Iter124:       399.48861112   -1.25920E+01    7.72340E+01
SCF Iter125:       386.42107615   -1.30675E+01    7.61301E+01
SCF Iter126:       373.99457517   -1.24265E+01    7.50276E+01
SCF Iter127:       358.99652132   -1.49981E+01    7.38484E+01
SCF Iter128:       344.32477163   -1.46717E+01    7.26920E+01
SCF Iter129:       345.66437110    1.33960E+00    7.26709E+01
SCF Iter130:       331.67650322   -1.39879E+01    7.15331E+01
SCF Iter131:       317.72532640   -1.39512E+01    7.04186E+01
SCF Iter132:       304.56338117   -1.31619E+01    6.93248E+01
SCF Iter133:       291.22799631   -1.33354E+01    6.82496E+01
SCF Iter134:       293.15970999    1.93171E+00    6.83630E+01
SCF Iter135:       296.12577911    2.96607E+00    6.84917E+01
SCF Iter136:       282.49418667   -1.36316E+01    6.74216E+01
SCF Iter137:       268.18584128   -1.43083E+01    6.63720E+01
SCF Iter138:       254.81973795   -1.33661E+01    6.53522E+01
SCF Iter139:       241.79355022   -1.30262E+01    6.43490E+01
SCF Iter140:       229.06272708   -1.27308E+01    6.33651E+01
SCF Iter141:       237.44366952    8.38094E+00    6.39215E+01
SCF Iter142:       246.31671813    8.87305E+00    6.44914E+01
SCF Iter143:       253.80091173    7.48419E+00    6.49259E+01
SCF Iter144:       256.80568854    3.00478E+00    6.50919E+01
SCF Iter145:       245.48031629   -1.13254E+01    6.42857E+01
SCF Iter146:       231.98041094   -1.34999E+01    6.32821E+01
SCF Iter147:       229.48136313   -2.49905E+00    6.31454E+01
SCF Iter148:       230.18628991    7.04927E-01    6.32272E+01
SCF Iter149:       218.90179730   -1.12845E+01    6.22274E+01
SCF Iter150:       217.15341939   -1.74838E+00    6.19892E+01
SCF Iter151:       204.28456877   -1.28689E+01    6.10128E+01
SCF Iter152:       191.49629297   -1.27883E+01    6.00519E+01
SCF Iter153:       182.71201831   -8.78427E+00    5.93302E+01
SCF Iter154:       173.04737653   -9.66464E+00    5.85405E+01
SCF Iter155:       163.18922875   -9.85815E+00    5.77501E+01
SCF Iter156:       154.64796700   -8.54126E+00    5.69633E+01
SCF Iter157:       146.55705843   -8.09091E+00    5.61929E+01
SCF Iter158:       135.71466338   -1.08424E+01    5.53257E+01
SCF Iter159:       128.00707165   -7.70759E+00    5.46049E+01
SCF Iter160:       120.44508244   -7.56199E+00    5.38795E+01
SCF Iter161:       113.75519223   -6.68989E+00    5.31575E+01
SCF Iter162:       107.10665876   -6.64853E+00    5.24485E+01
SCF Iter163:        99.37203846   -7.73462E+00    5.17240E+01
SCF Iter164:        90.23549624   -9.13654E+00    5.09322E+01
SCF Iter165:        83.20118732   -7.03431E+00    5.02258E+01
SCF Iter166:        74.39922549   -8.80196E+00    4.95383E+01
SCF Iter167:        69.39769081   -5.00153E+00    4.90018E+01
SCF Iter168:        64.89815421   -4.49954E+00    4.84426E+01
SCF Iter169:        59.93756063   -4.96059E+00    4.78373E+01
SCF Iter170:        51.01295485   -8.92461E+00    4.71158E+01
SCF Iter171:        46.26559536   -4.74736E+00    4.66037E+01
SCF Iter172:        41.49393215   -4.77166E+00    4.61930E+01
SCF Iter173:        36.27196921   -5.22196E+00    4.58039E+01
SCF Iter174:        30.47090046   -5.80107E+00    4.53000E+01
SCF Iter175:        24.94744591   -5.52345E+00    4.48394E+01
SCF Iter176:        21.54859751   -3.39885E+00    4.42099E+01
SCF Iter177:        17.60858713   -3.94001E+00    4.35726E+01
SCF Iter178:         9.89161926   -7.71697E+00    4.29314E+01
SCF Iter179:         5.42645876   -4.46516E+00    4.26031E+01
SCF Iter180:         5.24169527   -1.84763E-01    4.25910E+01
SCF Iter181:        -1.11519134   -6.35689E+00    4.20699E+01
SCF Iter182:        -7.49436240   -6.37917E+00    4.15481E+01
SCF Iter183:       -14.43513559   -6.94077E+00    4.09945E+01
SCF Iter184:       -13.75773654    6.77399E-01    4.11775E+01
SCF Iter185:       -16.26205223   -2.50432E+00    4.10642E+01
SCF Iter186:       -14.36424334    1.89781E+00    4.13592E+01
SCF Iter187:       -16.16896481   -1.80472E+00    4.13036E+01
SCF Iter188:       -21.17425120   -5.00529E+00    4.09320E+01
SCF Iter189:       -28.69907330   -7.52482E+00    4.03217E+01
SCF Iter190:       -34.54199242   -5.84292E+00    3.98945E+01
SCF Iter191:       -40.36767606   -5.82568E+00    3.94655E+01
SCF Iter192:       -45.51006945   -5.14239E+00    3.90790E+01
SCF Iter193:       -51.54979300   -6.03972E+00    3.86003E+01
SCF Iter194:       -57.41830852   -5.86852E+00    3.81256E+01
SCF Iter195:       -64.11570887   -6.69740E+00    3.75780E+01
SCF Iter196:       -42.70469358    2.14110E+01    3.93551E+01
SCF Iter197:       -32.99689843    9.70780E+00    4.01707E+01
SCF Iter198:       -29.71971993    3.27718E+00    4.04239E+01
SCF Iter199:       -30.24284216   -5.23122E-01    4.04004E+01
SCF Iter200:       -31.07632135   -8.33479E-01    4.03980E+01
SCF Iter201:       -38.68845562   -7.61213E+00    3.97623E+01
SCF Iter202:       -44.76787845   -6.07942E+00    3.91786E+01
SCF Iter203:       -50.29863208   -5.53075E+00    3.86288E+01
SCF Iter204:       -56.89976199   -6.60113E+00    3.80296E+01
SCF Iter205:       -36.60603219    2.02937E+01    3.98872E+01
SCF Iter206:       -12.90579080    2.37002E+01    4.18726E+01
SCF Iter207:       -16.71339756   -3.80761E+00    4.15216E+01
SCF Iter208:       -20.41561948   -3.70222E+00    4.12004E+01
SCF Iter209:       -23.74207115   -3.32645E+00    4.09221E+01
SCF Iter210:       -30.69862960   -6.95656E+00    4.02695E+01
SCF Iter211:       -36.46187334   -5.76324E+00    3.96994E+01
SCF Iter212:       -43.26108907   -6.79922E+00    3.91133E+01
SCF Iter213:       -49.06999175   -5.80890E+00    3.85628E+01
SCF Iter214:       -54.60984840   -5.53986E+00    3.80146E+01
SCF Iter215:       -59.91364483   -5.30380E+00    3.74766E+01
SCF Iter216:       -60.83568449   -9.22040E-01    3.74109E+01
SCF Iter217:       -63.15581466   -2.32013E+00    3.73891E+01
SCF Iter218:       -69.48882342   -6.33301E+00    3.68120E+01
SCF Iter219:       -75.73200972   -6.24319E+00    3.62379E+01
SCF Iter220:       -81.71207303   -5.98006E+00    3.56769E+01
SCF Iter221:       -85.37753800   -3.66546E+00    3.54394E+01
SCF Iter222:       -87.18670294   -1.80916E+00    3.54169E+01
SCF Iter223:       -88.65442942   -1.46773E+00    3.54250E+01
SCF Iter224:       -90.16734890   -1.51292E+00    3.54141E+01
SCF Iter225:       -89.15760009    1.00975E+00    3.55967E+01
SCF Iter226:       -94.53631710   -5.37872E+00    3.50347E+01
SCF Iter227:       -95.53296264   -9.96646E-01    3.50800E+01
SCF Iter228:       -98.72628799   -3.19333E+00    3.49102E+01
SCF Iter229:      -100.34280590   -1.61652E+00    3.48450E+01
SCF Iter230:      -102.01199301   -1.66919E+00    3.49062E+01
SCF Iter231:       -85.92886521    1.60831E+01    3.67369E+01
SCF Iter232:       -91.67737167   -5.74851E+00    3.62470E+01
SCF Iter233:       -97.81608471   -6.13871E+00    3.57027E+01
SCF Iter234:      -103.99118048   -6.17510E+00    3.51198E+01
SCF Iter235:      -108.71360018   -4.72242E+00    3.47315E+01
SCF Iter236:      -112.20327786   -3.48968E+00    3.45181E+01
SCF Iter237:      -114.13438151   -1.93110E+00    3.44842E+01
SCF Iter238:      -115.97325126   -1.83887E+00    3.44683E+01
SCF Iter239:      -119.65264626   -3.67940E+00    3.41997E+01
SCF Iter240:      -125.17553055   -5.52288E+00    3.36829E+01
SCF Iter241:      -118.46096940    6.71456E+00    3.44962E+01
SCF Iter242:      -119.09264073   -6.31671E-01    3.46264E+01
SCF Iter243:      -118.78612702    3.06514E-01    3.48519E+01
SCF Iter244:       -99.63477690    1.91514E+01    3.68050E+01
SCF Iter245:       -86.15055975    1.34842E+01    3.82316E+01
SCF Iter246:       -92.47537323   -6.32481E+00    3.76249E+01
SCF Iter247:       -98.60521630   -6.12984E+00    3.70368E+01
SCF Iter248:      -101.42090132   -2.81569E+00    3.68212E+01
SCF Iter249:       -97.93103859    3.48986E+00    3.72136E+01
SCF Iter250:      -104.48069748   -6.54966E+00    3.65573E+01
SCF Iter251:       -95.62410076    8.85660E+00    3.79028E+01
SCF Iter252:       -94.39166555    1.23244E+00    3.83916E+01
SCF Iter253:       -95.33138500   -9.39719E-01    3.85783E+01
SCF Iter254:       -96.77455293   -1.44317E+00    3.84070E+01
SCF Iter255:       -87.85667660    8.91788E+00    3.95179E+01
SCF Iter256:       -94.91381981   -7.05714E+00    3.87921E+01
SCF Iter257:      -101.13703284   -6.22321E+00    3.81363E+01
SCF Iter258:      -107.21578231   -6.07875E+00    3.74776E+01
SCF Iter259:      -113.13685735   -5.92108E+00    3.68330E+01
SCF Iter260:       -94.82462177    1.83122E+01    3.90242E+01
SCF Iter261:       -73.38935679    2.14353E+01    4.12039E+01
SCF Iter262:       -52.45912937    2.09302E+01    4.32998E+01
SCF Iter263:       -29.75634710    2.27028E+01    4.54898E+01
SCF Iter264:       -37.96139928   -8.20505E+00    4.46384E+01
SCF Iter265:       -45.55122527   -7.58983E+00    4.38806E+01
SCF Iter266:       -52.13972660   -6.58850E+00    4.32170E+01
SCF Iter267:       -59.82485111   -7.68512E+00    4.24143E+01
SCF Iter268:       -67.07789353   -7.25304E+00    4.16284E+01
SCF Iter269:       -74.07055964   -6.99267E+00    4.08601E+01
SCF Iter270:       -78.36835431   -4.29779E+00    4.04710E+01
SCF Iter271:       -79.54881092   -1.18046E+00    4.03973E+01
SCF Iter272:       -81.07515108   -1.52634E+00    4.02681E+01
SCF Iter273:       -83.10476274   -2.02961E+00    4.00899E+01
SCF Iter274:       -86.47840767   -3.37364E+00    3.97375E+01
SCF Iter275:       -93.18652820   -6.70812E+00    3.89928E+01
SCF Iter276:       -95.88210083   -2.69557E+00    3.87542E+01
SCF Iter277:       -95.59967161    2.82429E-01    3.89086E+01
SCF Iter278:       -99.70595771   -4.10629E+00    3.84684E+01
SCF Iter279:      -101.33345055   -1.62749E+00    3.83237E+01
SCF Iter280:      -104.55861157   -3.22516E+00    3.80162E+01
SCF Iter281:      -111.07171123   -6.51310E+00    3.72878E+01
SCF Iter282:      -114.66304900   -3.59134E+00    3.69124E+01
SCF Iter283:      -104.57490432    1.00881E+01    3.82678E+01
SCF Iter284:      -110.08171473   -5.50681E+00    3.76449E+01
SCF Iter285:      -111.72281393   -1.64110E+00    3.75213E+01
SCF Iter286:      -113.09396226   -1.37115E+00    3.74800E+01
SCF Iter287:      -110.65746817    2.43649E+00    3.78625E+01
SCF Iter288:      -110.77129617   -1.13828E-01    3.79659E+01
SCF Iter289:      -112.41639569   -1.64510E+00    3.76850E+01
SCF Iter290:      -107.86010900    4.55629E+00    3.83343E+01
SCF Iter291:      -114.47124779   -6.61114E+00    3.75695E+01
SCF Iter292:      -120.61537256   -6.14412E+00    3.68553E+01
SCF Iter293:      -124.46236429   -3.84699E+00    3.64901E+01
SCF Iter294:      -128.13666013   -3.67430E+00    3.60813E+01
SCF Iter295:      -132.74050438   -4.60384E+00    3.55213E+01
SCF Iter296:      -136.93448334   -4.19398E+00    3.50103E+01
SCF Iter297:      -132.75026303    4.18422E+00    3.56184E+01
SCF Iter298:      -138.77322745   -6.02296E+00    3.49067E+01
SCF Iter299:      -142.49662363   -3.72340E+00    3.44476E+01
SCF Iter300:      -146.44327424   -3.94665E+00    3.39141E+01
SCF Iter301:      -151.27400123   -4.83073E+00    3.32940E+01
SCF Iter302:      -155.85657434   -4.58257E+00    3.27262E+01
SCF Iter303:      -142.60657576    1.32500E+01    3.43436E+01
SCF Iter304:      -130.17395649    1.24326E+01    3.58580E+01
SCF Iter305:      -124.10594365    6.06801E+00    3.67145E+01
SCF Iter306:      -119.96616197    4.13978E+00    3.74054E+01
SCF Iter307:      -111.90773657    8.05843E+00    3.84683E+01
SCF Iter308:       -97.92972476    1.39780E+01    4.00628E+01
SCF Iter309:       -70.49256100    2.74372E+01    4.26251E+01
SCF Iter310:       -54.94368345    1.55489E+01    4.46302E+01
SCF Iter311:       -62.88390719   -7.94022E+00    4.37244E+01
SCF Iter312:       -70.33752090   -7.45361E+00    4.28535E+01
SCF Iter313:       -77.41587185   -7.07835E+00    4.19851E+01
SCF Iter314:       -84.21059490   -6.79472E+00    4.11378E+01
SCF Iter315:       -79.25856844    4.95203E+00    4.21471E+01
SCF Iter316:       -67.74985324    1.15087E+01    4.38359E+01
SCF Iter317:       -65.43854020    2.31131E+00    4.43419E+01
SCF Iter318:       -69.68264879   -4.24411E+00    4.40255E+01
SCF Iter319:       -50.56680391    1.91158E+01    4.68386E+01
SCF Iter320:       -58.66299253   -8.09619E+00    4.58937E+01

In [33]:
GUESS_A = Da
GUESS_B = Db

In [34]:
psi4.core.set_output_file('output.dat', False)

ATOMS = {
    # Period 3 (Na-Ar)
    'Na': {'mult': 2},  # [Ne] 3s1
    'Mg': {'mult': 1},  # [Ne] 3s2
    'Al': {'mult': 2},  # [Ne] 3s2 3p1
    'Si': {'mult': 3},  # [Ne] 3s2 3p2 
    'P':  {'mult': 4},  # [Ne] 3s2 3p3 
    'S':  {'mult': 3},  # [Ne] 3s2 3p4
    # 'Cl': {'mult': 2},  # [Ne] 3s2 3p5
    # 'Ar': {'mult': 1},  # [Ne] 3s2 3p6
    # Period 4 (Selected)
    # 'K':  {'mult': 2},  # [Ar] 4s1
    # 'Ca': {'mult': 1},  # [Ar] 4s2
    # 'Cu': {'mult': 2},  # [Ar] 3d10 4s1 
    # 'Zn': {'mult': 1},  # [Ar] 3d10 4s2
    # 'Kr': {'mult': 1},  # [Ar] 3d10 4s2 4p6
}

METHOD = "TF0.111111W LDA"
TP = ['LDA_K_TF', 1.0]
LAMBDA = 0.111111
EXC = ['LDA_X', 1.0, 'LDA_C_VWN', 0.0]
# EXC = ['GGA_X_PBE', 1.0, 'LDA_C_VWN', 0.0]
FA = [False, 1.0]
DIIS = True
MAX_ITER = 25000
DAMPING = [0.99, 0.9, 0.00009]
D_guess = [GUESS_A, GUESS_B]
# D_guess = None
verbose=True

psi4.set_options({'basis': 'UGBS_S', 
                  'DFT_SPHERICAL_POINTS': 6, 
                  'DFT_RADIAL_POINTS': 1000})

for atom in ATOMS:
    
    if not df.empty:
        exists = df[
            (df['Atom'] == atom) & 
            (df['Method'] == METHOD) & 
            (df['Basis'] == psi4.core.get_global_option("BASIS"))
        ]
        if not exists.empty:
            print(f"Skipping {atom} (Already exists for {METHOD}/{psi4.core.get_global_option("BASIS")})")
            continue

    print(f"Calculating {atom} with {METHOD}...")
    MOL = psi4.geometry(f"0 {ATOMS[atom]['mult']}\n {atom}\nsymmetry c1")
    try:
        E, Da, Db, iterations = lps_solver(MAX_ITER,TP,EXC,LAMBDA,MOL,DAMPING,FA,D_guess,DIIS,verbose)
        if iterations >= MAX_ITER:
            print("  !!! SCF failed to converge (Max cycles exceeded).")
        else:
            print(f"Calculated Energy: {E:.4f} Hartree")
            row = {
                "Method": METHOD,
                "Atom": atom,
                "Basis": psi4.core.get_global_option("BASIS"),
                "Grid_Sph": psi4.core.get_global_option("DFT_SPHERICAL_POINTS"),
                "Grid_Rad": psi4.core.get_global_option("DFT_RADIAL_POINTS"),
                "Energy,Ha": round(E, 6),
                "Iterations": iterations,
                "DIIS": DIIS,
                "Damp_Start": DAMPING[0],
                "Damp_End": DAMPING[1],
                "Damp_Cutoff": DAMPING[2]
            }
            
            df = pd.concat([df, pd.DataFrame([row])], ignore_index=True)
    
    except Exception as e:
        print(f"  !!! Failed {atom}. Error: {e}")
        continue

Skipping Na (Already exists for TF0.111111W LDA/UGBS_S)
Skipping Mg (Already exists for TF0.111111W LDA/UGBS_S)
Skipping Al (Already exists for TF0.111111W LDA/UGBS_S)
Skipping Si (Already exists for TF0.111111W LDA/UGBS_S)
Skipping P (Already exists for TF0.111111W LDA/UGBS_S)
Calculating S with TF0.111111W LDA...
Number of basis functions:   31

Starting SCF iterations:

    Iter            Energy            Delta E         dRMS

SCF Iter  1:      -424.99168312   -4.24992E+02    1.02316E+00
SCF Iter  2:      -425.02108804   -2.94049E-02    3.60165E-01
SCF Iter  3:      -425.02587433   -4.78630E-03    3.74996E-01
SCF Iter  4:      -424.93898872    8.68856E-02    5.58339E-01
SCF Iter  5:      -424.78658172    1.52407E-01    1.11946E+00
SCF Iter  6:      -424.55914192    2.27440E-01    1.71169E+00
SCF Iter  7:      -424.27432795    2.84814E-01    2.29612E+00
SCF Iter  8:      -423.89181510    3.82513E-01    2.86715E+00
SCF Iter  9:      -423.44974249    4.42073E-01    3.42381E+00
SCF Iter 10:      -423.26737564    1.82367E-01    3.59121E+00
SCF Iter 11:      -422.99765323    2.69722E-01    3.87194E+00
SCF Iter 12:      -422.70628692    2.91366E-01    4.15135E+00
SCF Iter 13:      -422.16596609    5.40321E-01    4.67240E+00
SCF Iter 14:      -421.56023013    6.05736E-01    5.17891E+00
SCF Iter 15:      -421.29599049    2.64240E-01    5.31494E+00
SCF Iter 16:      -421.01016818    2.85822E-01    5.45017E+00
SCF Iter 17:      -420.73394410    2.76224E-01    5.53256E+00
SCF Iter 18:      -421.38587275   -6.51929E-01    4.59749E+00
SCF Iter 19:      -421.68130713   -2.95434E-01    4.27367E+00
SCF Iter 20:      -421.36757102    3.13736E-01    4.49990E+00
SCF Iter 21:      -421.04058924    3.26982E-01    4.72481E+00
SCF Iter 22:      -420.78349292    2.57096E-01    4.91424E+00
SCF Iter 23:      -420.40381177    3.79681E-01    5.16918E+00
SCF Iter 24:      -419.67713138    7.26680E-01    5.64601E+00
SCF Iter 25:      -418.90700794    7.70123E-01    6.10949E+00
SCF Iter 26:      -418.08506908    8.21939E-01    6.55984E+00
SCF Iter 27:      -417.89235208    1.92717E-01    5.59329E+00
SCF Iter 28:      -417.47313606    4.19216E-01    5.07826E+00
SCF Iter 29:      -415.53317725    1.93996E+00    6.87964E+00
SCF Iter 30:      -414.87956805    6.53609E-01    6.80402E+00
SCF Iter 31:      -414.14497887    7.34589E-01    6.73997E+00
SCF Iter 32:      -413.39100646    7.53972E-01    6.69170E+00
SCF Iter 33:      -412.58743884    8.03568E-01    6.66546E+00
SCF Iter 34:      -413.23288586   -6.45447E-01    7.03489E+00
SCF Iter 35:      -412.50785208    7.25034E-01    8.09673E+00
SCF Iter 36:      -410.85022026    1.65763E+00    9.48482E+00
SCF Iter 37:      -410.37695862    4.73262E-01    9.33794E+00
SCF Iter 38:      -409.83305106    5.43908E-01    9.19510E+00
SCF Iter 39:      -409.24984024    5.83211E-01    9.05647E+00
SCF Iter 40:      -410.19779621   -9.47956E-01    8.21980E+00
SCF Iter 41:      -409.56471744    6.33079E-01    8.70145E+00
SCF Iter 42:      -407.47500490    2.08971E+00    1.00904E+01
SCF Iter 43:      -407.08984992    3.85155E-01    1.03006E+01
SCF Iter 44:      -406.78986830    2.99982E-01    1.04117E+01
SCF Iter 45:      -406.44882300    3.41045E-01    1.05304E+01
SCF Iter 46:      -406.07735700    3.71466E-01    1.03489E+01
SCF Iter 47:      -405.66394295    4.13414E-01    1.01716E+01
SCF Iter 48:      -391.08574568    1.45782E+01    1.49926E+01
SCF Iter 49:      -373.08549318    1.80003E+01    2.00819E+01
SCF Iter 50:      -351.83460102    2.12509E+01    2.53171E+01
SCF Iter 51:      -329.72411137    2.21105E+01    2.83567E+01
SCF Iter 52:      -329.76028478   -3.61734E-02    2.85472E+01
SCF Iter 53:      -330.96685836   -1.20657E+00    2.76859E+01
SCF Iter 54:      -332.03944702   -1.07259E+00    2.73934E+01
SCF Iter 55:      -332.81913551   -7.79688E-01    2.72324E+01
SCF Iter 56:      -334.36874836   -1.54961E+00    2.67782E+01
SCF Iter 57:      -335.91431591   -1.54557E+00    2.63251E+01
SCF Iter 58:      -338.35108431   -2.43677E+00    2.56049E+01
SCF Iter 59:      -340.81218394   -2.46110E+00    2.49336E+01
SCF Iter 60:      -343.14830451   -2.33612E+00    2.44250E+01
SCF Iter 61:      -345.44231703   -2.29401E+00    2.39838E+01
SCF Iter 62:      -347.51457917   -2.07226E+00    2.37998E+01
SCF Iter 63:      -349.42462082   -1.91004E+00    2.33237E+01
SCF Iter 64:      -351.29948126   -1.87486E+00    2.29416E+01
SCF Iter 65:      -353.06613488   -1.76665E+00    2.25955E+01
SCF Iter 66:      -354.72423077   -1.65810E+00    2.22980E+01
SCF Iter 67:      -356.35343827   -1.62921E+00    2.20990E+01
SCF Iter 68:      -358.05732385   -1.70389E+00    2.16766E+01
SCF Iter 69:      -357.87123796    1.86086E-01    2.19606E+01
SCF Iter 70:      -359.49655817   -1.62532E+00    2.15007E+01
SCF Iter 71:      -360.80491142   -1.30835E+00    2.11752E+01
SCF Iter 72:      -362.06137790   -1.25647E+00    2.09142E+01
SCF Iter 73:      -363.44038513   -1.37901E+00    2.05321E+01
SCF Iter 74:      -364.82552811   -1.38514E+00    2.01488E+01
SCF Iter 75:      -366.32189115   -1.49636E+00    1.97067E+01
SCF Iter 76:      -367.49326003   -1.17137E+00    1.92090E+01
SCF Iter 77:      -368.54052289   -1.04726E+00    1.87473E+01
SCF Iter 78:      -369.53116070   -9.90638E-01    1.83334E+01
SCF Iter 79:      -370.47537104   -9.44210E-01    1.78675E+01
SCF Iter 80:      -371.38335546   -9.07984E-01    1.74288E+01
SCF Iter 81:      -372.10349640   -7.20141E-01    1.70054E+01
SCF Iter 82:      -372.93808634   -8.34590E-01    1.69996E+01
SCF Iter 83:      -374.24025276   -1.30217E+00    1.66530E+01
SCF Iter 84:      -375.42895867   -1.18871E+00    1.61656E+01
SCF Iter 85:      -375.92439601   -4.95437E-01    1.62364E+01
SCF Iter 86:      -376.34821729   -4.23821E-01    1.63137E+01
SCF Iter 87:      -377.14922975   -8.01012E-01    1.57388E+01
SCF Iter 88:      -378.38495468   -1.23572E+00    1.54175E+01
SCF Iter 89:      -379.14801526   -7.63061E-01    1.53749E+01
SCF Iter 90:      -379.98781586   -8.39801E-01    1.52972E+01
SCF Iter 91:      -380.83573237   -8.47917E-01    1.51386E+01
SCF Iter 92:      -381.59189637   -7.56164E-01    1.48807E+01
SCF Iter 93:      -382.51266672   -9.20770E-01    1.45190E+01
SCF Iter 94:      -383.16664384   -6.53977E-01    1.42476E+01
SCF Iter 95:      -383.64998888   -4.83345E-01    1.39077E+01
SCF Iter 96:      -384.55949124   -9.09502E-01    1.33572E+01
SCF Iter 97:      -384.90952807   -3.50037E-01    1.29832E+01
SCF Iter 98:      -385.25665985   -3.47132E-01    1.26171E+01
SCF Iter 99:      -385.42945237   -1.72793E-01    1.23626E+01
SCF Iter100:      -385.97978000   -5.50328E-01    1.29190E+01
SCF Iter101:      -386.50710596   -5.27326E-01    1.29615E+01
SCF Iter102:      -387.01504899   -5.07943E-01    1.30388E+01
SCF Iter103:      -387.35971333   -3.44664E-01    1.32082E+01
SCF Iter104:      -388.24708070   -8.87367E-01    1.28911E+01
SCF Iter105:      -388.58928120   -3.42201E-01    1.27761E+01
SCF Iter106:      -388.86666022   -2.77379E-01    1.24085E+01
SCF Iter107:      -389.41002390   -5.43364E-01    1.23246E+01
SCF Iter108:      -389.90031789   -4.90294E-01    1.22857E+01
SCF Iter109:      -390.41696493   -5.16647E-01    1.22951E+01
SCF Iter110:      -390.83168624   -4.14721E-01    1.24434E+01
SCF Iter111:      -391.15227454   -3.20588E-01    1.25783E+01
SCF Iter112:      -391.52612788   -3.73853E-01    1.26542E+01
SCF Iter113:      -391.97250101   -4.46373E-01    1.22889E+01
SCF Iter114:      -392.32881378   -3.56313E-01    1.23535E+01
SCF Iter115:      -392.51187644   -1.83063E-01    1.24873E+01
SCF Iter116:      -392.75700464   -2.45128E-01    1.25987E+01
SCF Iter117:      -392.93919706   -1.82192E-01    1.27741E+01
SCF Iter118:      -393.09707910   -1.57882E-01    1.28688E+01
SCF Iter119:      -393.68781595   -5.90737E-01    1.26629E+01
SCF Iter120:      -394.12943551   -4.41620E-01    1.25615E+01
SCF Iter121:      -394.66737149   -5.37936E-01    1.24042E+01
SCF Iter122:      -395.26603801   -5.98667E-01    1.21609E+01
SCF Iter123:      -395.90637155   -6.40334E-01    1.19103E+01
SCF Iter124:      -396.55782949   -6.51458E-01    1.16663E+01
SCF Iter125:      -397.00690620   -4.49077E-01    1.15429E+01
SCF Iter126:      -397.40783634   -4.00930E-01    1.14495E+01
SCF Iter127:      -398.06758355   -6.59747E-01    1.11989E+01
SCF Iter128:      -398.74139396   -6.73810E-01    1.07902E+01
SCF Iter129:      -399.33573913   -5.94345E-01    1.04293E+01
SCF Iter130:      -399.91027989   -5.74541E-01    1.00934E+01
SCF Iter131:      -400.47691791   -5.66638E-01    9.70237E+00
SCF Iter132:      -400.83964176   -3.62724E-01    9.22731E+00
SCF Iter133:      -400.70062749    1.39014E-01    9.12348E+00
SCF Iter134:      -400.70131269   -6.85204E-04    9.49110E+00
SCF Iter135:      -400.79922340   -9.79107E-02    9.75136E+00
SCF Iter136:      -400.70515897    9.40644E-02    1.03417E+01
SCF Iter137:      -400.81252794   -1.07369E-01    1.04695E+01
SCF Iter138:      -401.12116843   -3.08640E-01    1.04449E+01
SCF Iter139:      -401.67021737   -5.49049E-01    1.01459E+01
SCF Iter140:      -401.91523391   -2.45017E-01    1.01416E+01
SCF Iter141:      -402.08414494   -1.68911E-01    1.01854E+01
SCF Iter142:      -402.56407620   -4.79931E-01    9.62790E+00
SCF Iter143:      -402.77063944   -2.06563E-01    9.65150E+00
SCF Iter144:      -402.98303609   -2.12397E-01    9.64333E+00
SCF Iter145:      -403.15441626   -1.71380E-01    9.68274E+00
SCF Iter146:      -403.28543186   -1.31016E-01    9.87942E+00
SCF Iter147:      -403.33417778   -4.87459E-02    1.01143E+01
SCF Iter148:      -403.47310105   -1.38923E-01    1.02594E+01
SCF Iter149:      -403.56639063   -9.32896E-02    1.02874E+01
SCF Iter150:      -403.71802262   -1.51632E-01    1.02919E+01
SCF Iter151:      -403.85437887   -1.36356E-01    1.03089E+01
SCF Iter152:      -404.03018783   -1.75809E-01    1.02816E+01
SCF Iter153:      -404.22722029   -1.97032E-01    1.02503E+01
SCF Iter154:      -404.53288200   -3.05662E-01    1.01389E+01
SCF Iter155:      -405.05965993   -5.26778E-01    9.79279E+00
SCF Iter156:      -405.52359602   -4.63936E-01    9.48704E+00
SCF Iter157:      -405.98054195   -4.56946E-01    9.12677E+00
SCF Iter158:      -406.05039546   -6.98535E-02    9.12157E+00
SCF Iter159:      -406.16818584   -1.17790E-01    8.92151E+00
SCF Iter160:      -406.23572018   -6.75343E-02    8.97386E+00
SCF Iter161:      -406.30467809   -6.89579E-02    9.05875E+00
SCF Iter162:      -406.37936476   -7.46867E-02    9.12743E+00
SCF Iter163:      -406.37528794    4.07682E-03    9.26175E+00
SCF Iter164:      -406.52434563   -1.49058E-01    9.27706E+00
SCF Iter165:      -407.03043981   -5.06094E-01    8.95314E+00
SCF Iter166:      -407.43860506   -4.08165E-01    8.71625E+00
SCF Iter167:      -407.80400802   -3.65403E-01    8.49732E+00
SCF Iter168:      -408.20361346   -3.99605E-01    8.22983E+00
SCF Iter169:      -408.68132570   -4.77712E-01    7.69123E+00
SCF Iter170:      -408.73111909   -4.97934E-02    7.76957E+00
SCF Iter171:      -408.78290595   -5.17869E-02    7.83228E+00
SCF Iter172:      -408.94449452   -1.61589E-01    7.82646E+00
SCF Iter173:      -409.08787179   -1.43377E-01    7.90464E+00
SCF Iter174:      -409.21197074   -1.24099E-01    7.91806E+00
SCF Iter175:      -409.27207914   -6.01084E-02    7.95260E+00
SCF Iter176:      -409.34243775   -7.03586E-02    7.99499E+00
SCF Iter177:      -409.64194108   -2.99503E-01    7.79247E+00
SCF Iter178:      -409.79354593   -1.51605E-01    7.71118E+00
SCF Iter179:      -409.95150569   -1.57960E-01    7.65271E+00
SCF Iter180:      -410.08441344   -1.32908E-01    7.61211E+00
SCF Iter181:      -410.18755264   -1.03139E-01    7.60719E+00
SCF Iter182:      -410.32646059   -1.38908E-01    7.57529E+00
SCF Iter183:      -410.39074458   -6.42840E-02    7.62662E+00
SCF Iter184:      -410.83577451   -4.45030E-01    7.19378E+00
SCF Iter185:      -410.97493711   -1.39163E-01    7.09831E+00
SCF Iter186:      -411.13915995   -1.64223E-01    6.73935E+00
SCF Iter187:      -411.22081846   -8.16585E-02    6.82978E+00
SCF Iter188:      -411.30801751   -8.71990E-02    6.89818E+00
SCF Iter189:      -411.42440662   -1.16389E-01    6.85177E+00
SCF Iter190:      -411.37380056    5.06061E-02    6.94522E+00
SCF Iter191:      -411.36980937    3.99119E-03    7.01422E+00
SCF Iter192:      -411.47281534   -1.03006E-01    7.02594E+00
SCF Iter193:      -411.49723048   -2.44151E-02    7.07530E+00
SCF Iter194:      -411.92590024   -4.28670E-01    6.72331E+00
SCF Iter195:      -412.12791266   -2.02012E-01    6.64886E+00
SCF Iter196:      -412.33937000   -2.11457E-01    6.53128E+00
SCF Iter197:      -412.44577846   -1.06408E-01    6.49822E+00
SCF Iter198:      -412.53966574   -9.38873E-02    6.50049E+00
SCF Iter199:      -412.67347658   -1.33811E-01    6.44259E+00
SCF Iter200:      -412.80098580   -1.27509E-01    6.35546E+00
SCF Iter201:      -412.86674027   -6.57545E-02    6.35937E+00
SCF Iter202:      -412.89822999   -3.14897E-02    6.35714E+00
SCF Iter203:      -412.99774580   -9.95158E-02    6.30942E+00
SCF Iter204:      -413.22372033   -2.25975E-01    6.16986E+00
SCF Iter205:      -413.48025015   -2.56530E-01    5.99457E+00
SCF Iter206:      -413.80068284   -3.20433E-01    5.71182E+00
SCF Iter207:      -413.86318623   -6.25034E-02    5.74683E+00
SCF Iter208:      -413.91318539   -4.99992E-02    5.80727E+00
SCF Iter209:      -414.25434279   -3.41157E-01    5.33984E+00
SCF Iter210:      -414.54732550   -2.92983E-01    4.97644E+00
SCF Iter211:      -414.81306833   -2.65743E-01    4.61938E+00
SCF Iter212:      -414.98940639   -1.76338E-01    4.01257E+00
SCF Iter213:      -414.90648094    8.29254E-02    4.33313E+00
SCF Iter214:      -414.63027048    2.76210E-01    4.42385E+00
SCF Iter215:      -414.39972925    2.30541E-01    4.89384E+00
SCF Iter216:      -414.66758490   -2.67856E-01    4.70150E+00
SCF Iter217:      -414.87138824   -2.03803E-01    4.47861E+00
SCF Iter218:      -415.03171820   -1.60330E-01    4.39857E+00
SCF Iter219:      -415.13633840   -1.04620E-01    4.41027E+00
SCF Iter220:      -415.26710080   -1.30762E-01    4.34168E+00
SCF Iter221:      -415.35742062   -9.03198E-02    4.36701E+00
SCF Iter222:      -415.46884805   -1.11427E-01    4.31011E+00
SCF Iter223:      -415.58052624   -1.11678E-01    4.25058E+00
SCF Iter224:      -415.64118109   -6.06548E-02    3.90564E+00
SCF Iter225:      -415.68155842   -4.03773E-02    4.08573E+00
SCF Iter226:      -415.70766419   -2.61058E-02    4.28456E+00
SCF Iter227:      -415.78309789   -7.54337E-02    4.39206E+00
SCF Iter228:      -415.82370194   -4.06041E-02    4.45342E+00
SCF Iter229:      -415.85766528   -3.39633E-02    4.51070E+00
SCF Iter230:      -415.99144368   -1.33778E-01    4.44089E+00
SCF Iter231:      -416.20864372   -2.17200E-01    4.23519E+00
SCF Iter232:      -416.32008445   -1.11441E-01    4.19682E+00
SCF Iter233:      -416.53920467   -2.19120E-01    3.91393E+00
SCF Iter234:      -416.55686168   -1.76570E-02    3.62883E+00
SCF Iter235:      -416.51418658    4.26751E-02    3.42770E+00
SCF Iter236:      -416.59482246   -8.06359E-02    3.50157E+00
SCF Iter237:      -416.65024483   -5.54224E-02    3.56187E+00
SCF Iter238:      -416.70337249   -5.31277E-02    3.61512E+00
SCF Iter239:      -416.64984414    5.35284E-02    3.82439E+00
SCF Iter240:      -416.64484926    4.99488E-03    3.96841E+00
SCF Iter241:      -416.60404354    4.08057E-02    4.07927E+00
SCF Iter242:      -416.59761366    6.42988E-03    4.24260E+00
SCF Iter243:      -416.60676924   -9.15558E-03    4.23701E+00
SCF Iter244:      -416.63373950   -2.69703E-02    4.13777E+00
SCF Iter245:      -416.63561453   -1.87503E-03    4.15479E+00
SCF Iter246:      -416.69311402   -5.74995E-02    4.08664E+00
SCF Iter247:      -416.72593851   -3.28245E-02    4.07653E+00
SCF Iter248:      -416.74087265   -1.49341E-02    4.09203E+00
SCF Iter249:      -416.76622554   -2.53529E-02    4.10678E+00
SCF Iter250:      -416.82733566   -6.11101E-02    4.07768E+00
SCF Iter251:      -416.92096017   -9.36245E-02    4.04721E+00
SCF Iter252:      -417.01817262   -9.72125E-02    4.01536E+00
SCF Iter253:      -417.07861748   -6.04449E-02    3.99218E+00
SCF Iter254:      -417.14569739   -6.70799E-02    3.96045E+00
SCF Iter255:      -417.42962890   -2.83932E-01    3.71647E+00
SCF Iter256:      -417.49940412   -6.97752E-02    3.73439E+00
SCF Iter257:      -417.46906216    3.03420E-02    3.60852E+00
SCF Iter258:      -417.52127095   -5.22088E-02    3.62938E+00
SCF Iter259:      -417.58406140   -6.27904E-02    3.65702E+00
SCF Iter260:      -417.65214394   -6.80825E-02    3.69699E+00
SCF Iter261:      -417.72170520   -6.95613E-02    3.82000E+00
SCF Iter262:      -417.78279132   -6.10861E-02    3.96060E+00
SCF Iter263:      -417.98078353   -1.97992E-01    3.44314E+00
SCF Iter264:      -417.94527182    3.55117E-02    3.32275E+00
SCF Iter265:      -418.03976555   -9.44937E-02    3.40073E+00
SCF Iter266:      -418.11110099   -7.13354E-02    3.59581E+00
SCF Iter267:      -418.15934092   -4.82399E-02    3.84521E+00
SCF Iter268:      -418.22208843   -6.27475E-02    4.05482E+00
SCF Iter269:      -418.27094174   -4.88533E-02    4.18756E+00
SCF Iter270:      -418.37412546   -1.03184E-01    4.14086E+00
SCF Iter271:      -418.49151192   -1.17386E-01    4.08937E+00
SCF Iter272:      -418.72010944   -2.28598E-01    3.78544E+00
SCF Iter273:      -418.79760995   -7.75005E-02    3.64024E+00
SCF Iter274:      -418.82109032   -2.34804E-02    3.60126E+00
SCF Iter275:      -418.87630915   -5.52188E-02    3.60580E+00
SCF Iter276:      -418.92506448   -4.87553E-02    3.57516E+00
SCF Iter277:      -418.97340580   -4.83413E-02    3.58561E+00
SCF Iter278:      -419.00548929   -3.20835E-02    3.65218E+00
SCF Iter279:      -419.03310095   -2.76117E-02    3.75262E+00
SCF Iter280:      -419.08117550   -4.80745E-02    3.76886E+00
SCF Iter281:      -419.11482535   -3.36499E-02    3.80215E+00
SCF Iter282:      -419.16673070   -5.19053E-02    3.76484E+00
SCF Iter283:      -419.20486829   -3.81376E-02    3.69349E+00
SCF Iter284:      -419.21049012   -5.62183E-03    3.69318E+00
SCF Iter285:      -419.22247202   -1.19819E-02    3.70336E+00
SCF Iter286:      -419.24515869   -2.26867E-02    3.71155E+00
SCF Iter287:      -419.24774144   -2.58274E-03    3.76432E+00
SCF Iter288:      -419.27737216   -2.96307E-02    3.71984E+00
SCF Iter289:      -419.26906403    8.30813E-03    3.46066E+00
SCF Iter290:      -419.28543976   -1.63757E-02    3.56486E+00
SCF Iter291:      -419.30162811   -1.61883E-02    3.64983E+00
SCF Iter292:      -419.30471806   -3.08995E-03    3.71850E+00
SCF Iter293:      -419.32423232   -1.95143E-02    3.71646E+00
SCF Iter294:      -419.32837769   -4.14537E-03    3.77287E+00
SCF Iter295:      -419.31718452    1.11932E-02    3.88251E+00
SCF Iter296:      -419.33649642   -1.93119E-02    3.97030E+00
SCF Iter297:      -419.35037033   -1.38739E-02    3.90284E+00
SCF Iter298:      -419.40679362   -5.64233E-02    3.79591E+00
SCF Iter299:      -419.43324901   -2.64554E-02    3.81405E+00
SCF Iter300:      -419.45679356   -2.35445E-02    3.85102E+00
SCF Iter301:      -419.46602231   -9.22875E-03    3.90675E+00
SCF Iter302:      -419.50876213   -4.27398E-02    3.94636E+00
SCF Iter303:      -419.52845386   -1.96917E-02    3.99321E+00
SCF Iter304:      -419.57619108   -4.77372E-02    4.03237E+00
SCF Iter305:      -419.73559949   -1.59408E-01    3.95310E+00
SCF Iter306:      -419.92017487   -1.84575E-01    3.75253E+00
SCF Iter307:      -420.00932071   -8.91458E-02    3.67522E+00
SCF Iter308:      -420.10973741   -1.00417E-01    3.60646E+00
SCF Iter309:      -420.18213025   -7.23928E-02    3.58823E+00
SCF Iter310:      -420.28345936   -1.01329E-01    3.50095E+00
SCF Iter311:      -420.35004121   -6.65819E-02    3.45895E+00
SCF Iter312:      -420.41551182   -6.54706E-02    3.41350E+00
SCF Iter313:      -420.51899556   -1.03484E-01    3.29158E+00
SCF Iter314:      -420.60673093   -8.77354E-02    3.20826E+00
SCF Iter315:      -420.71212534   -1.05394E-01    3.08931E+00

KeyboardInterrupt:

In [35]:
df.to_csv(csv_file, index=False)
df

,Method,Atom,Basis,Grid_Sph,Grid_Rad,"Energy,Ha",Iterations,DIIS,Damp_Start,Damp_End,Damp_Cutoff
0,TFW LDA,Na,UGBS_S,6,1000,-108.912083,284,True,0.90,0.90,0.00009
1,TFW LDA,Mg,UGBS_S,6,1000,-135.553609,237,True,0.90,0.90,0.00009
2,TFW LDA,Al,UGBS_S,6,1000,-165.669941,387,True,0.90,0.90,0.00009
3,TFW LDA,Si,UGBS_S,6,1000,-199.392286,517,True,0.90,0.90,0.00009
4,TFW LDA,P,UGBS_S,6,1000,-236.833553,342,True,0.90,0.90,0.00009
...,...,...,...,...,...,...,...,...,...,...,...
139,TF0.111111W LDA,Na,UGBS_S,6,1000,-175.220390,4870,True,0.99,0.99,0.00003
140,TF0.111111W LDA,Mg,UGBS_S,6,1000,-215.265035,4402,True,0.99,0.99,0.00003
141,TF0.111111W LDA,Al,UGBS_S,6,1000,-260.117429,14370,True,0.99,0.99,0.00003
142,TF0.111111W LDA,Si,UGBS_S,6,1000,-309.909768,8732,True,0.99,0.90,0.00005
143,TF0.111111W LDA,P,UGBS_S,6,1000,-364.755320,13406,True,0.99,0.99,0.00005

In [ ]:
## TF0.111111W PBE for O and F used TF0.111111W FA densities of O and F as initial guesses
## TF0.111111W FA for Si, Kr used TF0.166666W FA initial guess
## TF0.2W FA for Cl used TF0.333333W FA initial guess
## TF0.166666W FA for Cl used TF0.2W FA initial guess
## TF0.111111W LDA for Si, P used TF0.111111W LDA density of a previous atom

In [ ]:
ATOMS = {
    'He':  {'mult': 1}, 
    'Be': {'mult': 1},
    'Ne': {'mult': 1}, 
    'Mg': {'mult': 1},
    'Ar':  {'mult': 1}, 
    'Ca':  {'mult': 1},
    'Zn':  {'mult': 1}, 
    'Kr':  {'mult': 1}
}
psi4.core.set_output_file('output.dat', False)
psi4.set_options({'basis': 'UGBS',
                  'scf_type': 'PK'})
rhf_energies = {}
rhf_homos = {}
for atom in ATOMS:
    MOL = psi4.geometry(f"0 {ATOMS[atom]['mult']}\n {atom}\nsymmetry c1")
    E, wfn = psi4.energy('SCF', return_wfn=True)
    rhf_energies[atom] = round(E, 6)
    print(f"RHF/UGBS {atom} Energy: {E:.4f} Hartree")

RHF/UGBS He Energy: -2.8617 Hartree, IP: -0.9180
RHF/UGBS Be Energy: -14.5730 Hartree, IP: -0.3093
RHF/UGBS Ne Energy: -128.5471 Hartree, IP: -0.8504
RHF/UGBS Mg Energy: -199.6146 Hartree, IP: -0.2530
RHF/UGBS Ar Energy: -526.8175 Hartree, IP: -0.5910
RHF/UGBS Ca Energy: -676.7582 Hartree, IP: -0.1955
RHF/UGBS Zn Energy: -1777.8481 Hartree, IP: -0.2925
RHF/UGBS Kr Energy: -2752.0549 Hartree, IP: -0.5242

In [26]:
atom_order = ['He', 'Be', 'Ne', 'Mg', 'Ar', 'Ca', 'Zn', 'Kr']
energy_table = df.pivot(index='Atom', columns='Method', values='Energy,Ha')
energy_table = energy_table.reindex(atom_order)
energy_table['RHF/UGBS'] = pd.Series(rhf_energies)
new_order = ['TFD0.166666W', 'TF0.166666W PBEx', 'TF0.166666W FA', 'RHF/UGBS']
energy_table = energy_table[new_order]

In [28]:
reference = energy_table['RHF/UGBS']

res = {}
for method, energies in energy_table.items():
    if method == 'RHF/UGBS': 
        continue 
    
    mae  = (energies - reference).abs().mean()
    rmae = (((energies - reference).abs()) / reference * -100).mean()
    res[method] = round(mae, 2), round(rmae, 2)

mae_row  = {method: values[0] for method, values in res.items()}
rmae_row = {method: values[1] for method, values in res.items()}
stats_df = pd.DataFrame([mae_row, rmae_row], index=['MAE(Ha)', 'rMAE(%)'])
energy_table = pd.concat([energy_table, stats_df], sort=False)

In [29]:
display(energy_table)

         TFD0.166666W  TF0.166666W PBEx  TF0.166666W FA     RHF/UGBS
He          -2.951247         -3.097069       -3.019526    -2.861680
Be         -15.040391        -15.388877      -14.660508   -14.573023
Ne        -132.508856       -133.573716     -128.291707  -128.547083
Mg        -204.540690       -205.864549     -198.305386  -199.614621
Ar        -537.208760       -539.346529     -522.928926  -526.817486
Ca        -690.396266       -692.814969     -672.808485  -676.758154
Zn       -1812.192490      -1816.067937    -1773.727670 -1777.848060
Kr       -2795.914635      -2800.696590    -2741.665221 -2752.054860
MAE(Ha)     13.960000         15.970000        3.020000          NaN
rMAE(%)      2.420000          3.690000        1.110000          NaN